### ISSUE TITLE
build error in ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by mtau87** [grpc/grpc#14624]
build failed after the following commands:

$ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ make

with the following errors:

[MAKE]    Generating cache.mk
[HOSTLD]  Linking /home/ubuntu/grpc/bins/opt/grpc_cpp_plugin
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufMethod::get_output_type_name[abi:cxx11]() const':
/home/ubuntu/grpc/./src/compiler/protobuf_plugin.h:55: undefined reference to `google::protobuf::MethodDescriptor::output_type() const'
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufMethod::get_input_type_name[abi:cxx11]() const':
/home/ubuntu/grpc/./src/compiler/protobuf_plugin.h:52: undefined reference to `google::protobuf::MethodDescriptor::input_type() const'
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufMethod::output_type_name[abi:cxx11]() const':
/home/ubuntu/grpc/./src/compiler/protobuf_plugin.h:48: undefined reference to `google::protobuf::MethodDescriptor::output_type() const'
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufMethod::input_type_name[abi:cxx11]() const':
/home/ubuntu/grpc/./src/compiler/protobuf_plugin.h:45: undefined reference to `google::protobuf::MethodDescriptor::input_type() const'
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufMethod::get_module_and_message_path_output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const':
/home/ubuntu/grpc/./src/compiler/protobuf_plugin.h:71: undefined reference to `google::protobuf::MethodDescriptor::output_type() const'
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o: In function `ProtoBufMethod::get_module_and_message_path_input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const':
/home/ubuntu/grpc/./src/compiler/protobuf_plugin.h:62: undefined reference to `google::protobuf::MethodDescriptor::input_type() const'
/home/ubuntu/grpc/objs/opt/src/compiler/cpp_plugin.o:(.data.rel.ro._ZTV16CppGrpcGenerator[_ZTV16CppGrpcGenerator]+0x28): undefined reference to `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
collect2: error: ld returned 1 exit status
Makefile:16017: recipe for target '/home/ubuntu/grpc/bins/opt/grpc_cpp_plugin' failed
make: *** [/home/ubuntu/grpc/bins/opt/grpc_cpp_plugin] Error 1

**Comment by matt-kwong** [comment]
Hi, sorry for the late response. Could you try running `make HAS_SYSTEM_PROTOBUF=false`? You might have an out of date protobuf installed on your system, and the above command will use our protobuf submodule in `third_party/protobuf`.

**Comment by jtattermusch** [comment]
We do have a continuous test for build on ubuntu16.04 and it is passing consistently:
https://source.cloud.google.com/results/invocations/d4b2de4d-e779-47f6-a923-e63b984cb7e2/targets

The issue you are seeing is probably due to what @matt-kwong  has mentioned.
