### ISSUE TITLE
pthread_mutex_lock assertion failure

### ISSUE THREAD

**Issue by noahdesu** [grpc/grpc#7830]
Install gRPC from homebrew using `brew tap grpc/grpc` and `brew install --with-plugins grpc`. Then I build `examples/cpp/hello_world` and ran the `./greeter_server` resulting in:

```
eduroam-169-233-225-116:helloworld nwatkins$ ./greeter_server 
E0822 15:00:41.676982000 140735224107008 sync_posix.c:51] assertion failed: pthread_mutex_lock(mu) == 0
Abort trap: 6
```

**Comment by GrgrLmml** [comment]
Can confirm this with github version 2a69139aa7f609e439c24a46754252a5f9d37500 (1.0.0 release) on OSX

**Comment by GrgrLmml** [comment]
The problem seems to be solved on master ( 0e43d67602096a5c4aeab4632579bc56cf692553 )

**Comment by bclermont** [comment]
confirm it's fixed on `0e43d67`

**Comment by noahdesu** [comment]
Anyway to force homebrew to upgrade to master since its stuck on the 1.0.0 cut?

**Comment by nicolasnoble** [comment]
So, master is 1.1.0-dev, and we won't release it for a while. Could you try with the current HEAD of the v1.0.x branch ? d7ff4ff40071d2b486a052183e3e9f9382afb745 that is. If it still happens there, we need to figure out which commit in master actually fixes it, and backport that to the v1.0.x branch.

**Comment by GrgrLmml** [comment]
Just tried it, it also fails with d7ff4ff

**Comment by nicolasnoble** [comment]
Can you describe a bit more what is it you're doing to test this from git directly ? I just tried building d7ff4ff40071d2b486a052183e3e9f9382afb745 on Mac, and the hello world's greeter server, and everything's fine on my end.

We need a bit more data.

**Comment by GrgrLmml** [comment]
alright.
    ➜  github gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
    Apple LLVM version 7.3.0 (clang-703.0.31)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
    ➜  github protoc --version
    libprotoc 3.0.0
    ➜  github git clone git@github.com:grpc/grpc.git
    Cloning into 'grpc'...
    remote: Counting objects: 194457, done.
    remote: Compressing objects: 100% (8/8), done.
    remote: Total 194457 (delta 0), reused 0 (delta 0), pack-reused 194449
    Receiving objects: 100% (194457/194457), 80.31 MiB | 138.00 KiB/s, done.
    Resolving deltas: 100% (146266/146266), done.
    Checking connectivity... done.
    ➜  github cd grpc
    ➜  grpc git:(master) git checkout d7ff4ff
    Note: checking out 'd7ff4ff'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at d7ff4ff... Merge pull request #7817 from stanley-cheung/php-update-composer-v1_0
    ➜  grpc git:(d7ff4ff) git submodule update --init
    [...]
     grpc git:(d7ff4ff) make -j8
    ➜  grpc git:(d7ff4ff) sudo make install
    [...]
    ➜  helloworld git:(d7ff4ff) make
    protoc -I ../../protos --cpp_out=. ../../protos/helloworld.proto
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o helloworld.pb.o helloworld.pb.cc
    protoc -I ../../protos --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ../../protos/helloworld.proto
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o helloworld.grpc.pb.o helloworld.grpc.pb.cc
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o greeter_client.o greeter_client.cc
    g++ helloworld.pb.o helloworld.grpc.pb.o greeter_client.o -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -lprotobuf -lpthread -ldl -o greeter_client
    ld: unknown option: --no-as-needed
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [greeter_client] Error 1
    ➜  helloworld git:(d7ff4ff) ✗

It compiles w/o --no-as-needed and --as-needed but then I get the pthread_mutex_lock assertion failure
    ➜  helloworld git:(d7ff4ff) ✗ vim Makefile 
    ➜  helloworld git:(d7ff4ff) ✗ make
    g++ helloworld.pb.o helloworld.grpc.pb.o greeter_client.o -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl -lgrpc++_reflection -Wl -lprotobuf -lpthread -ldl -o greeter_client
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o greeter_server.o greeter_server.cc
    g++ helloworld.pb.o helloworld.grpc.pb.o greeter_server.o -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl -lgrpc++_reflection -Wl -lprotobuf -lpthread -ldl -o greeter_server
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o greeter_async_client.o greeter_async_client.cc
    g++ helloworld.pb.o helloworld.grpc.pb.o greeter_async_client.o -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl -lgrpc++_reflection -Wl -lprotobuf -lpthread -ldl -o greeter_async_client
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o greeter_async_client2.o greeter_async_client2.cc
    g++ helloworld.pb.o helloworld.grpc.pb.o greeter_async_client2.o -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl -lgrpc++_reflection -Wl -lprotobuf -lpthread -ldl -o greeter_async_client2
    g++ -std=c++11 -I/usr/local/include -pthread  -c -o greeter_async_server.o greeter_async_server.cc
    g++ helloworld.pb.o helloworld.grpc.pb.o greeter_async_server.o -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl -lgrpc++_reflection -Wl -lprotobuf -lpthread -ldl -o greeter_async_server
    ➜  helloworld git:(d7ff4ff) ✗ ./greeter_server
    E0825 11:17:15.768300000 140735216762880 sync_posix.c:51] assertion failed: pthread_mutex_lock(mu) == 0
    [1]    8910 abort      ./greeter_server
    ➜  helloworld git:(d7ff4ff) ✗

**Comment by amerry** [comment]
I've also run into this. The issue doesn't seem to exist in the common parent of 0e43d67 and the v1.0.0 tag. Git bisect suggests it was introduced in a469e5d, which just changes library links.

In fact, it also happens on current master (c931305). So there doesn't seem to be a fix already created. Perhaps it's something to do with grpc_unsecure?

**Comment by amerry** [comment]
After some investigation, I believe the issue is that a469e5d adds the grpc library object files directly into the grpc++ library (so you don't have to link against grpc when using grpc++).

The problem is that some of the grpc object files have the same names as grpc++ object files (eg: time.o from time.c and time.o from time.cc). The linker only includes one of them (and warns about this). However, you don't get actual linker errors (unresolved symbols, etc) because it _also_ links to grpc. But you almost certainly get duplicate global variables this way, which is probably where the error on this ticket comes from (the mutex storage that is initialised is not the mutex storage that is used).

I've seen similar issues in the Windows build system (where it *does* cause linker errors), probably from the same commit. Partially reverting a469e5d (removing all the added "src/core/**/*.c" lines) fixes the issue. Renaming some of the C++ or C source files should also work (in which case, libgrpc++ should no longer link to libgrpc).

**Comment by liuempire** [comment]
I have this problem on Mac OS X 10.11.6, too. Neither the current master 7f936eaa379e88869fcdb187d084f9bd7300c792 nor the v1.0.0 tag works with the `./greeter_server` example.

The same code totally works on Ubuntu 16.04.1 LTS, though.

@amerry Could you please provide more information about your workaround? Thanks!

**Comment by nicolasnoble** [comment]
So if that's the case, we're making sure we have no more duplicated filenames at all, in the v1.0.x.

**Comment by amerry** [comment]
@liuempire if you just want a quick build fix, `git revert a469e5d` will do it. However, I think you may end up being unable to use grpc++_unsecure without OpenSSL.

@nicolasnoble that should fix both the Windows (vsprojects) and Mac (Makefile) build systems. Although the Makefile should also be changed to not link grpc++[_unsecure] to grpc[_unsecure].

**Comment by david9991** [comment]
I can confirm it exists on OS X El Captain, even in current 'master' branch. The workaround is to static link libgrpc++.a and libgrpc.a archive in Xcode, but I was failed to mix link static and dynamic libraries in CMake.

**Comment by advenioinc** [comment]
As of today, this issue does still exist in master. I'm not sure how to utilize the static link workaround with the current examples, is there any additional info on workarounds. Any ideas when a fix might get into the tree? We're trying to use this on Mac, Windows and Linux and right now the Mac can't even run the example "hello world" app.

**Comment by david9991** [comment]
@advenioinc Here is part of my CMakeLists.txt
`set(PROJ_DEPS ${BREW_HOME}/lib/libgrpc++.a ${BREW_HOME}/lib/libgrpc.a z protobuf 
  mongocxx bsoncxx mongoc-1.0 
  bson-1.0 ssl crypto iec61850 ${RT_LIB} pthread dl)`
that the variable PROJ_DEPS was putted in target's target_link_libraries()
`add_executable(${PROJECT_NAME} common/Variables.cpp main.cpp)`
`target_link_libraries(${PROJECT_NAME} ${PROJ_DEPS})`
We just use the absolute path of grpc static libraries and leave other dynamic library by use their name.

and for Xcode, you can set 'Other linker flags' in Project Settings like this
`/usr/local/lib/libgrpc++.a /usr/local/lib/libgrpc.a z protobuf 
  mongocxx bsoncxx mongoc-1.0`

**Comment by gfxcc** [comment]
this problem still exist on MacOS Sierra

**Comment by dongjian** [comment]
$ ./route_guide_server &
[1] 14383
DB parsed, loaded 100 features.
E1020 10:14:11.448431000 140736310096832 sync_posix.c:51] assertion failed: pthread_mutex_lock(mu) == 0
[1]  + 14383 abort      ./route_guide_server
macOS Sierra 10.12

**Comment by sab24** [comment]
I have successfully compiled the route_guide_server example with the current master at f89a4a1 on MacOS Sierra.

**Comment by david9991** [comment]
Confirmed, it fixed in current master commit.

**Comment by athei** [comment]
Did you try to compile the latest master with brew? For me the building it fails with the following error:
`[CXX]     Compiling src/cpp/ext/proto_server_reflection.cc
In file included from src/cpp/ext/proto_server_reflection.cc:39:
In file included from ./src/cpp/ext/proto_server_reflection.h:56:
In file included from include/grpc++/ext/reflection.grpc.pb.h:73:
include/grpc++/ext/reflection.pb.h:46:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
include/grpc++/ext/reflection.pb.h:47:2: error: incompatible with your Protocol Buffer headers.  Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
include/grpc++/ext/reflection.pb.h:48:2: error: your headers.
#error your headers.
 ^
include/grpc++/ext/reflection.pb.h:268:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ServerReflectionRequest> ServerReflectionRequest_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:268:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ServerReflectionRequest> ServerReflectionRequest_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:366:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ExtensionRequest> ExtensionRequest_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:366:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ExtensionRequest> ExtensionRequest_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:529:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ServerReflectionResponse> ServerReflectionResponse_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:529:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ServerReflectionResponse> ServerReflectionResponse_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:625:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<FileDescriptorResponse> FileDescriptorResponse_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:625:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<FileDescriptorResponse> FileDescriptorResponse_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:730:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ExtensionNumberResponse> ExtensionNumberResponse_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:730:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ExtensionNumberResponse> ExtensionNumberResponse_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:822:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ListServiceResponse> ListServiceResponse_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:822:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ListServiceResponse> ListServiceResponse_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:913:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ServiceResponse> ServiceResponse_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:913:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ServiceResponse> ServiceResponse_default_instance_;
                                                          ^
include/grpc++/ext/reflection.pb.h:1011:38: error: no type named 'ExplicitlyConstructed' in namespace 'google::protobuf::internal'
extern ::google::protobuf::internal::ExplicitlyConstructed<ErrorResponse> ErrorResponse_default_instance_;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
include/grpc++/ext/reflection.pb.h:1011:59: error: expected unqualified-id
extern ::google::protobuf::internal::ExplicitlyConstructed<ErrorResponse> ErrorResponse_default_instance_;
                                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
`

**Comment by sab24** [comment]
I compiled with the make command. You need to be sure to run make uninstall or something to remove all old versions of your system. If you do not then you get this kind of error. It took me all weekend to find that out.

**Comment by athei** [comment]
So you installed manually or with brew?

**Comment by fengli79** [comment]
Has it been released with v1.0.1?

**Comment by Toldy** [comment]
I have the same problem on my MacOSX Sierra.

```
./greeter_server&
[1] 12371
E1116 15:47:04.625304000 140736051999680 sync_posix.c:51] assertion failed: pthread_mutex_lock(mu) == 0
[1]  + 12371 abort      ./greeter_server
```

**Comment by hsaliak** [comment]
I've re-opened the issue - we should verify before closing.
@Toldy can you provide more details of your installation? Is this from brew or manually, also which version of gRPC are you using?
Per @sab24's comment can you confirm if this is due to older versions of libgrpc in your system?

**Comment by sab24** [comment]
1. Dowload protobuf, extract it cd into it
./configure
make uninstall

2. Install grpc
git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
rm -r ./third_party/nanopb
git checkout f89a4a1
cd third_party
cd protobuf
git checkout master
cd ../..
make
su
make install
cd third_party/protobuf
make install
exit
cd examples/cpp/helloworld
make

This works. When trying for the current master branch of grpc then the error is:

Undefined symbols for architecture x86_64:
  "_grpc_global_wakeup_fd", referenced from:
      _grpc_init_poll_posix in ev_poll_posix.o
      _grpc_init_poll_cv_posix in ev_poll_posix.o
      _pollset_work in ev_poll_posix.o
      _kick_poller in ev_poll_posix.o
      _shutdown_engine in ev_poll_posix.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by y-zeng** [comment]
These seem to be different issues.
@athei The problem is caused by the version number of protobuf. We've removed those generated files in #8380.
@sab24 The problem seems to be caused by #8680. We are working on a fix for it.

**Comment by ncteisen** [comment]
@sab24, the related issue and PR for the problem you are seeing are in #8766 and #8832 respectively

**Comment by hadils** [comment]
I followed the instructions from @sab24 above.
I get the following error when I try to make grpc:

make: *** No rule to make target `/Users/hadilsabbagh/grpc/objs/opt/third_party/boringssl/crypto/asn1/a_bytes.o', needed by `/Users/hadilsabbagh/grpc/libs/opt/libboringssl.a'.  Stop.

**Comment by ncteisen** [comment]
Ensure everything is cleaned out first then try again.
```
git foreach submodule git clean -xfd
git clean -xfd
```

**Comment by laurent-code8** [comment]
git clean -xfd
git submodule foreach --recursive git clean -xfd
git reset --hard
git submodule foreach --recursive git reset --hard
git submodule update --init --recursive

**Comment by laurent-code8** [comment]
git rev-parse --short HEAD
60e9dac236


./greeter_client 
E0528 18:45:24.882480000 140735864529856 sync_posix.c:60]              assertion failed: pthread_mutex_lock(mu) == 0
Abort trap: 6
