### ISSUE TITLE
gRPC 1.74.0 doesn't compile on Rhel 7

### ISSUE THREAD

**Issue by varkey98** [grpc/grpc#41085]
### What version of gRPC and what language are you using?
1.74.0

### What operating system (Linux, Windows,...) and version?
Linux, RHEL 7
Linux 5e710ae64945 6.11.11-linuxkit #1 SMP Wed Oct 22 09:37:46 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
### What runtime / compiler are you using (e.g. python version or version of gcc)
[root@5e710ae64945 project]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-8/root/usr/libexec/gcc/aarch64-redhat-linux/8/lto-wrapper
Target: aarch64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-8/root/usr --mandir=/opt/rh/devtoolset-8/root/usr/share/man --infodir=/opt/rh/devtoolset-8/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-aarch64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --build=aarch64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 

### What did you do?
I have a cpp project built using bazel imports grpc as a bazel module. The project builds on my ubuntu 20.04 image but doesnt build on my rhel 7 image

### What did you expect to see?
The project compiles fine on rhel 7

### What did you see instead?

BoringSSL fails to compile on my RHEL 7 image with the following stack trace

```
ERROR: /tmp/external/boringssl+/BUILD.bazel:92:16: Compiling ssl/tls_record.cc failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@boringssl+//:ssl_internal) /opt/rh/devtoolset-8/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/boringssl+/ssl/tls_record.cc: In function 'bssl::ssl_open_record_t bssl::tls_open_record(SSL*, uint8_t*, bssl::Span<unsigned char>*, size_t*, uint8_t*, bssl::Span<unsigned char>)':
external/boringssl+/ssl/tls_record.cc:251:69: error: no matching function for call to 'bssl::Span<const unsigned char>::Span(<brace-enclosed initializer list>)'
       Span<const uint8_t>(body) == Span<const uint8_t>({SSL3_MT_CCS})) {
                                                                     ^
In file included from external/boringssl+/include/openssl/bytestring.h:20,
                 from external/boringssl+/include/openssl/obj.h:62,
                 from external/boringssl+/include/openssl/x509.h:81,
                 from external/boringssl+/include/openssl/pem.h:67,
                 from external/boringssl+/include/openssl/ssl.h:149,
                 from external/boringssl+/ssl/tls_record.cc:109:
external/boringssl+/include/openssl/span.h:146:22: note: candidate: 'template<class C, class, class> constexpr bssl::Span<T>::Span(C&)'
   constexpr explicit Span(C &container)
                      ^~~~
external/boringssl+/include/openssl/span.h:146:22: note:   template argument deduction/substitution failed:
external/boringssl+/ssl/tls_record.cc:251:69: note:   couldn't deduce template parameter 'C'
       Span<const uint8_t>(body) == Span<const uint8_t>({SSL3_MT_CCS})) {
                                                                     ^
In file included from external/boringssl+/include/openssl/bytestring.h:20,
                 from external/boringssl+/include/openssl/obj.h:62,
                 from external/boringssl+/include/openssl/x509.h:81,
                 from external/boringssl+/include/openssl/pem.h:67,
                 from external/boringssl+/include/openssl/ssl.h:149,
                 from external/boringssl+/ssl/tls_record.cc:109:
external/boringssl+/include/openssl/span.h:141:13: note: candidate: 'template<class C, class, class> constexpr bssl::Span<T>::Span(const C&)'
   constexpr Span(const C &container)
             ^~~~
external/boringssl+/include/openssl/span.h:141:13: note:   template argument deduction/substitution failed:
external/boringssl+/ssl/tls_record.cc:251:69: note:   couldn't deduce template parameter 'C'
       Span<const uint8_t>(body) == Span<const uint8_t>({SSL3_MT_CCS})) {
                                                                     ^
In file included from external/boringssl+/include/openssl/bytestring.h:20,
                 from external/boringssl+/include/openssl/obj.h:62,
                 from external/boringssl+/include/openssl/x509.h:81,
                 from external/boringssl+/include/openssl/pem.h:67,
                 from external/boringssl+/include/openssl/ssl.h:149,
                 from external/boringssl+/ssl/tls_record.cc:109:
external/boringssl+/include/openssl/span.h:137:13: note: candidate: 'template<long unsigned int N> constexpr bssl::Span<T>::Span(T (&)[N])'
   constexpr Span(T (&array)[N]) : Span(array, N) {}
             ^~~~
external/boringssl+/include/openssl/span.h:137:13: note:   template argument deduction/substitution failed:
external/boringssl+/ssl/tls_record.cc:251:69: note:   mismatched types 'unsigned char' and 'int'
       Span<const uint8_t>(body) == Span<const uint8_t>({SSL3_MT_CCS})) {
                                                                     ^
In file included from external/boringssl+/include/openssl/bytestring.h:20,
                 from external/boringssl+/include/openssl/obj.h:62,
                 from external/boringssl+/include/openssl/x509.h:81,
                 from external/boringssl+/include/openssl/pem.h:67,
                 from external/boringssl+/include/openssl/ssl.h:149,
                 from external/boringssl+/ssl/tls_record.cc:109:
external/boringssl+/include/openssl/span.h:134:13: note: candidate: 'constexpr bssl::Span<T>::Span(T*, size_t) [with T = const unsigned char; size_t = long unsigned int]'
   constexpr Span(T *ptr, size_t len) : data_(ptr), size_(len) {}
             ^~~~
external/boringssl+/include/openssl/span.h:134:13: note:   candidate expects 2 arguments, 1 provided
external/boringssl+/include/openssl/span.h:133:13: note: candidate: 'constexpr bssl::Span<T>::Span() [with T = const unsigned char]'
   constexpr Span() : Span(nullptr, 0) {}
             ^~~~
external/boringssl+/include/openssl/span.h:133:13: note:   candidate expects 0 arguments, 1 provided
external/boringssl+/include/openssl/span.h:118:7: note: candidate: 'constexpr bssl::Span<const unsigned char>::Span(const bssl::Span<const unsigned char>&)'
 class Span : private internal::SpanBase<const T> {
       ^~~~
external/boringssl+/include/openssl/span.h:118:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const bssl::Span<const unsigned char>&'
external/boringssl+/include/openssl/span.h:118:7: note: candidate: 'constexpr bssl::Span<const unsigned char>::Span(bssl::Span<const unsigned char>&&)'
external/boringssl+/include/openssl/span.h:118:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'bssl::Span<const unsigned char>&&'
```

**Comment by yuanweiz** [comment]
Hi there. Per our open source policy we only support RHEL >=9 https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md
