### ISSUE TITLE
module 'grpc' has no attribute 'experimental'

### ISSUE THREAD

**Issue by josiahlaivins** [grpc/grpc#27682]
### What version of gRPC and what language are you using?
Name: grpcio
Version: 1.41.0

Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux

### What operating system (Linux, Windows,...) and version?
Ubuntu 1804 running container continuumio/miniconda3

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux

### What did you do?
Below is a dockerfile demoing the problem start to finish:
```docker
FROM continuumio/miniconda3

RUN pip install grpcio-tools

# Switching to proto3 doesnt remove the experimental refs
RUN echo 'syntax = "proto2"; '>> test.proto
RUN echo 'package some_package;'>> test.proto
RUN echo 'message TestItem {'>> test.proto
RUN echo '    optional uint64 item_id =            1 [default=0];'>> test.proto
RUN echo '    optional string cust =               2 [default="svi"];'>> test.proto
RUN echo '    optional string cust_item_id =       3;'>> test.proto
RUN echo '    optional string site =               4;'>> test.proto
RUN echo '    optional string cust_item_name =     5;'>> test.proto
RUN echo '}'>> test.proto
RUN echo 'message TestItemRequest {'>> test.proto
RUN echo '  required uint64 item_id = 1;'>> test.proto
RUN echo '  optional string meta_json = 2;'>> test.proto
RUN echo '  optional string item_uuid = 3;'>> test.proto
RUN echo '}'>> test.proto
RUN echo 'service DataModelCoreBackend {'>> test.proto
RUN echo '  rpc get_test_item (TestItem) returns (TestItemRequest) {}'>> test.proto
RUN echo '}'>> test.proto

RUN cat test.proto
RUN python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. test.proto # \
CMD python

# Build: docker build -f test.Dockerfile -t test_grpc .
# Run:   docker run -it --rm test_grpc
```
The problem is in the python generation of `  rpc get_test_item (TestItem) returns (TestItemRequest) {}'`

`docker build -f test.Dockerfile -t test_grpc .`
`docker run -it --rm test_grpc`
`python`
```python
>>> import grpc
>>> from grpc.experimental import unary_unary
>>> grpc.experimental.unary_unary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'grpc' has no attribute 'experimental'
```

Note the line: `grpc.experimental.unary_unary` outputs an attribute error. When we build `test.proto` we see this used:

`docker run -it --rm test_grpc`
```bash
cat test_pb2_grpc.py | grep grpc.experimental

        return grpc.experimental.unary_unary(request, target, '/some_package.DataModelCoreBackend/get_test_item',
```

**grpc_tools.protoc produces fundamentally incompatible proto.py files. This will error out saying there was an attribute missing.**

### What did you expect to see?
Either:
`grpc.experimental.unary_unary` should not raise an error, can grab the attribute as expected 
**or**
`grpc_tools.protoc`  should not output any `.py` files with `grpc.experimental.unary_unary` in them.

### What did you see instead?
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'grpc' has no attribute 'experimental'
```
and 
`        return grpc.experimental.unary_unary(request, target, '/some_package.DataModelCoreBackend/get_test_item',`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Nope! The dockerfile demos this really nicely. I have tried toggling the package versions also, it doesnt seem to work. It is possible grpcio has a dep that is not compatible, in which case we would want to restrict versions.

I have also tried locally on my system which uses python 3.7, so it cant be a python version issue either.

Let me know if there is any additional information you need from me. The dockerfile should demo the problem though.
You can try adding `RUN conda install python=3.6` and you will still get the same errors.

**Comment by SumanthDatta-Kony** [comment]
Seeing  the similar issue on version1.43.0 . Currently running with python 3.7.9. So basically creating gRPC server with python you will run into this issue.

**Comment by VadeveSi** [comment]
Running 1.43.0 on Python 3.10, I had a similar issue. Initially I assumed that it was an issue with the module, like you suggested, but https://github.com/grpc/grpc/pull/28464 did not work as a fix for me. Furthermore, I _was_ able to run the example in the [Python Quickstart](https://grpc.io/docs/languages/python/quickstart/) without any issues, even though this also contained the `grpc.experimental.unary_unary` in the generated files.

In the end, I discovered that there was a mismatch in my client and server -- in my protofile I defined `create_kb`, but in my server I implemented `create_KB`. For whatever reason this resulted in the `Exception calling application: module 'grpc' has no attribute 'experimental'` error.

Ideally, this error can be traced further down so that the error message can be changed into something more helpful.

**Comment by TomaszBorczyk** [comment]
@VadeveSi 
I run into the same issue when I tried to use generated files form python quickstart (the HelloWorld example).
Files commited to grpc repo contain generated files that do not contain this experimental piece of code (https://github.com/grpc/grpc/blob/master/examples/python/helloworld/helloworld_pb2_grpc.py)
Files generated using `grpc_tools.protoc` in version `libprotoc 3.19.4` generate experimental class that is introduced in #22218

When simply trying to use it in hand-writted client script, it throws error `AttributeError: module 'grpc' has no attribute 'experimental'`
Adding `import grpc.experimental` to generated file fixes the issue - which should not be the solution, as modifying generated files is a bad idea.

I think user should have an option to switch off this experimental code generation via argument, eg `python -m grpc_tools.protoc [... usual aruments here] --experimental-features=false`

**Comment by NanoBjorn** [comment]
Btw adding `import grpc.experimental` to the generated file still does not help: `'_Context' object has no attribute 'encode'`

I was too lazy to dig deeper in the library as I do not know the code, but I can assume that it is somewhat related to this class: https://github.com/grpc/grpc/blob/8d3914f7745646dc8ad84222e6c59abb4bf1e699/src/python/grpcio/grpc/_server.py#L306C1-L306C11

Traceback:
```
Traceback (most recent call last):
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/gleb-novikov/Downloads/02-practice-grpc/messenger/proto/messenger_pb2_grpc.py", line 80, in SendMessage
    return grpc.experimental.unary_unary(request, target, '/mes_grpc.MessengerServer/SendMessage',
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/experimental/__init__.py", line 81, in _wrapper
    return f(*args, **kwargs)
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/_simple_stubs.py", line 275, in unary_unary
    channel = ChannelCache.get().get_channel(
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/_simple_stubs.py", line 188, in get_channel
    channel = _create_channel(
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/_simple_stubs.py", line 86, in _create_channel
    return grpc.secure_channel(
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/__init__.py", line 2100, in secure_channel
    return _channel.Channel(
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/_channel.py", line 1974, in __init__
    _common.encode(target),
  File "/Users/gleb-novikov/Library/Python/3.9/lib/python/site-packages/grpc/_common.py", line 71, in encode
    return s.encode("utf8")
AttributeError: '_Context' object has no attribute 'encode'
```

**Comment by HollrayChan** [comment]
I also encountered the same problem. I found that a certain function on the server side was written incorrectly, which caused this problem. It has nothing to do with the grpc version, and there is no need to `import grpc.experimental` and `--experimental-features=false`

**Comment by gnossen** [comment]
I'm not able to reproduce using the reproduction case provided in the original post. I'm guessing this was resolved? Interestingly enough, the `grpcio` version was pinned, but the _Conda_ version was not, so I'm guessing this was actually fixed on Conda's end.

@HollrayChan If you're still able to reproduce, please file a new issue with the reproduction steps.

**Comment by jeremyschlatter** [comment]
I found my way here because my grpc file failed to typecheck for, I believe, the same reason as OP:

> error: "experimental" is not a known attribute of module "grpc"

The generated code uses the `grpc.experimental` module without ever importing it.

OP's repro still demonstrates the problem, provided you execute the relevant code:

(from within the container):

```
(base) root@92043c9d7268:/# python -c 'from test_pb2_grpc import DataModelCoreBackend; DataModelCoreBackend.get_test_item(None, None)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from test_pb2_grpc import DataModelCoreBackend; DataModelCoreBackend.get_test_item(None, None)
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/test_pb2_grpc.py", line 83, in get_test_item
    return grpc.experimental.unary_unary(
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'grpc' has no attribute 'experimental'
```

I've opened a new issue with clearer steps: #39555
