### ISSUE TITLE
Build c++ helloworld example failed, with bazel on Windows 11 Pro

### ISSUE THREAD

**Issue by rubuslab** [grpc/grpc#33323]
### What version of gRPC and what language are you using?
gRPC branch: v1.56.0-pre1
language: C++

### What operating system (Linux, Windows,...) and version?
Windows 11 Pro

### What runtime / compiler are you using (e.g. python version or version of gcc)
bazel.exe ver: 7.0.0-pre.20230517.4
python.exe ver:3.11
Visual Studio 2022

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

In a new folder:
step 1: git clone -b v1.56.0-pre1 https://github.com/grpc/grpc
step 2: cd grpc/examples/cpp/helloworld
step 3: bazel build :greeter_client

### What did you expect to see?
Build binary greeter_client success.

### What did you see instead?
--------------------------------------
Loading: 0 packages loaded
Analyzing: target //examples/cpp/helloworld:greeter_client (0 packages loaded, 0 targets configured)
ERROR: G:/git-projects/z3/grpc/src/core/BUILD:34:14: Label '//src/core:ext/transport/binder/java/WORKSPACE' is invalid because '@binder_transport_android_helper//' is a subpackage
ERROR: G:/git-projects/z3/grpc/BUILD:863:16: Target '//src/core:gpr_atm' contains an error and its package is in error and referenced by '//:grpc++'
ERROR: G:/git-projects/z3/grpc/BUILD:863:16: Target '//src/core:slice' contains an error and its package is in error and referenced by '//:grpc++'
ERROR: Analysis of target '//examples/cpp/helloworld:greeter_client' failed; build aborted:
INFO: Elapsed time: 1.199s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
--------------------------------------

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by rubuslab** [comment]
step 1.5 is:
cd grpc
git submodule update --init

**Comment by yashykt** [comment]
We are suspecting that the bazel version 7 has issues. Can you try it with bazel version 5 or 6 please?

**Comment by rubuslab** [comment]
step 1: git clone -b v1.56.0-pre1 https://github.com/grpc/grpc
step 2: cd grpc
step 3: git submodule update --init
step 4: bazel version
        // output > Build label: 7.0.0-pre.20230517.4
step 5: cd examples/cpp/helloworld/
step 6: fix Windows build, add below 2 lines in file grpc/.bazelrc
       startup --output_user_root=G:/tmp --windows_enable_symlinks
       build:windows --enable_runfiles
step 6: bazel build :greeter_client
       // build failed, screen output as below
// ----------------------
$ bazel build :greeter_client
Loading:
Loading:
Loading: 0 packages loaded
Analyzing: target //examples/cpp/helloworld:greeter_client (0 packages loaded, 0 targets configured)
ERROR: G:/temp/grpc/src/core/BUILD:34:14: Label '//src/core:ext/transport/binder/java/WORKSPACE' is invalid because '@binder_transport_android_helper//' is a subpackage
ERROR: G:/temp/grpc/BUILD:843:16: Target '//src/core:gpr_atm' contains an error and its package is in error and referenced by '//:grpc++_public_hdrs'
ERROR: Analysis of target '//examples/cpp/helloworld:greeter_client' failed; build aborted:
INFO: Elapsed time: 0.354s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
// ----------------------

step 7: rename file grpc/src/core/ext/transport/binder/java/WORKSPACE to "--WORKSPACE"
step 8: bazel build :greeter_client
        // build failed, screen output error info as below:
// ----------------------
src/core/lib/gprpp/time.cc(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
src/core/lib/gprpp/time.cc(191): error C2001: newline in constant
src/core/lib/gprpp/time.cc(192): error C2143: syntax error: missing ';' before '}'
src/core/lib/gprpp/time.cc(194): error C2001: newline in constant
src/core/lib/gprpp/time.cc(195): error C2143: syntax error: missing ';' before '}'
src/core/lib/gprpp/time.cc(209): error C2001: newline in constant
src/core/lib/gprpp/time.cc(210): error C2143: syntax error: missing ';' before '}'
src/core/lib/gprpp/time.cc(212): error C2001: newline in constant
src/core/lib/gprpp/time.cc(213): error C2143: syntax error: missing ';' before '}'
// ----------------------
step 9: Setting Windows system support utf8
step 10: bazel build :greeter_client
      build successed.
// ---------------------
Target //examples/cpp/helloworld:greeter_server up-to-date:
  bazel-bin/examples/cpp/helloworld/greeter_server.exe
INFO: Elapsed time: 8.807s, Critical Path: 6.79s
INFO: 18 processes: 7 internal, 11 local.
INFO: Build completed successfully, 18 total actions
// ---------------------

It seems the java WORKSPACE problem still exist.

**Comment by rubuslab** [comment]
I tried build with bazel 6.2.1 was ok.
Thank you.

**Comment by rubuslab** [comment]
I close this thread.
