### ISSUE TITLE
Rubygem Build Error under Ruby 2.0

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#4132]
We are unable to get the grpc ruby gem to build/install under ruby 2.0 on Ubuntu 14.04 (Trusty). We are able to get the grpc lib to install, but not the ruby gem. It looks to be an incompatibility between ruby versions. Ruby 2.1 and 2.2 build/install just fine.

```
vagrant@trusty64:~$ gem install grpc
Building native extensions.  This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

    /home/vagrant/.rvm/rubies/ruby-2.0.0-p643/bin/ruby -r ./siteconf20151116-4682-8thf23.rb extconf.rb
checking for dlopen() in -ldl... yes
checking for inflate() in -lz... yes
checking for gpr_now() in -lgpr... yes
checking for grpc_channel_destroy() in -lgrpc... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_grpc.c
rb_grpc.c:58:5: error: 'RUBY_TYPED_FREE_IMMEDIATELY' undeclared here (not in a function)
     RUBY_TYPED_FREE_IMMEDIATELY};
     ^
rb_grpc.c:58:5: error: excess elements in struct initializer [-Werror]
rb_grpc.c:58:5: error: (near initialization for 'grpc_rb_timespec_data_type') [-Werror]
cc1: all warnings being treated as errors
make: *** [rb_grpc.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/grpc-0.11.0 for inspection.
Results logged to /home/vagrant/.rvm/gems/ruby-2.0.0-p643/extensions/x86_64-linux/2.0.0/grpc-0.11.0/gem_make.out
```

Being able to get the grpc lib and gem installed on trusty is important for us as this is what Travis-CI is using for our CI environment. I have a proof-of-concept project showing grpc working on travis with ruby 2.2 and 2.1, but failing on 2.0 [here](https://travis-ci.org/blowmage/grpc-travis/builds/91417010).

**Comment by murgatroid99** [comment]
This is the same problem as #4020.

**Comment by blowmage** [comment]
Ah, I searched for an existing issue before opening this one but my search-fu was weak. Thanks!
