### ISSUE TITLE
C#  MacOS x86 artifact build broken by converting lame client to c++

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11039]
Likely caused by #10427.

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/architecture=x86,language=csharp,platform=macos/3392/console

```
/Users/jenkins/workspace/gRPC_build_artifacts/architecture/x86/language/csharp/platform/macos/objs/opt/src/core/lib/surface/lame_client.o
Undefined symbols for architecture i386:
  "_grpc_lame_client_channel_create", referenced from:
      _grpc_secure_channel_create in secure_channel_create.o
      _grpc_insecure_channel_create in channel_create.o
      _grpc_insecure_channel_create_from_fd in channel_create_posix.o
  "_grpc_lame_filter", referenced from:
      _grpc_init in init.o
ld: symbol(s) not found for architecture i386
```
