### ISSUE TITLE
CMake builds broken

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#12872]
Looks to be caused by #12677

https://sponge.corp.google.com/invocation?id=25ba6f0d-d166-4ebd-a051-c9043bd78897&searchFor=
https://sponge.corp.google.com/invocation?id=25ba6f0d-d166-4ebd-a051-c9043bd78897&searchFor=

For Windows CMake:
```
"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\buildtests_c.vcxproj" (default target) (1) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\badreq_bad_client_test.vcxproj" (default target) (60) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\bad_client_test.vcxproj" (default target) (61) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_test_util_unsecure.vcxproj" (default target) (62) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj" (default target) (63) ->

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(404): error C2059: syntax error: '.' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(410): error C2059: syntax error: ')' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(413): error C2065: 'target': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(413): error C2065: 'tfc': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(413): error C2227: left of '->pid_controller' must point to class/struct/union/generic type [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(414): error C2065: 'now': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(414): error C2065: 'tfc': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(414): error C2227: left of '->last_pid_update' must point to class/struct/union/generic type [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(416): error C2065: 'tfc': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(416): error C2227: left of '->pid_controller' must point to class/struct/union/generic type [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C3927: '->': trailing return type is not allowed after a non-function declarator [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C3613: missing return type after '->' ('int' assumed) [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C2146: syntax error: missing ';' before identifier 'last_pid_update' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(418): error C2059: syntax error: 'return' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(419): error C2059: syntax error: '}' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(419): error C2143: syntax error: missing ';' before '}' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(423): error C2143: syntax error: missing ';' before '{' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(423): error C2447: '{': missing function header (old-style formal list?) [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(472): error C3861: 'get_target_under_memory_pressure': identifier not found [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_cmake_vs2017_buildonly\cmake\build\grpc_unsecure.vcxproj]



    8 Warning(s)

    40 Error(s)



Time Elapsed 00:05:08.48


2017-10-06 12:26:01,125 FAILED: cmake [ret=1, pid=3260, time=308.8sec]
```

Linux CMake:
```
"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\buildtests_c.vcxproj" (default target) (1) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\badreq_bad_client_test.vcxproj" (default target) (60) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\bad_client_test.vcxproj" (default target) (61) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_test_util_unsecure.vcxproj" (default target) (62) ->

"T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj" (default target) (63) ->

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(404): error C2059: syntax error: '.' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(410): error C2059: syntax error: ')' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(413): error C2065: 'target': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(413): error C2065: 'tfc': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(413): error C2227: left of '->pid_controller' must point to class/struct/union/generic type [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(414): error C2065: 'now': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(414): error C2065: 'tfc': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(414): error C2227: left of '->last_pid_update' must point to class/struct/union/generic type [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(416): error C2065: 'tfc': undeclared identifier [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(416): error C2227: left of '->pid_controller' must point to class/struct/union/generic type [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C3927: '->': trailing return type is not allowed after a non-function declarator [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C3613: missing return type after '->' ('int' assumed) [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(417): error C2146: syntax error: missing ';' before identifier 'last_pid_update' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(418): error C2059: syntax error: 'return' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(419): error C2059: syntax error: '}' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(419): error C2143: syntax error: missing ';' before '}' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(423): error C2143: syntax error: missing ';' before '{' [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(423): error C2447: '{': missing function header (old-style formal list?) [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]

  T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\src\core\ext\transport\chttp2\transport\flow_control.cc(472): error C3861: 'get_target_under_memory_pressure': identifier not found [T:\src\github\grpc\workspace_c_windows_dbg_native_x64_default_buildonly\cmake\build\grpc_unsecure.vcxproj]



    38 Warning(s)

    40 Error(s)



Time Elapsed 00:04:52.76


2017-10-06 12:25:13,048 FAILED: cmake [ret=1, pid=3044, time=292.9sec]
```

**Comment by yashykt** [comment]
I think this was caused by a git merge, but the fix should be just to remove the designated initializers usage in flow_control.cc

**Comment by jtattermusch** [comment]
Just to clarify, this the PR #12677 broke all our windows builds:
(https://sponge.corp.google.com/target?id=dd5f2e76-563e-4410-968f-6757de9a52e8&target=github/grpc/aggregate_tests&searchFor=&show=ALL&sortBy=STATUS)
This really needs to be fixed ASAP. 
I checked and PR #12677 cannot be autoreverted, so we either need a quick real fix or revert manually.

**Comment by yashykt** [comment]
These should be fixed as of #12885

**Comment by matt-kwong** [comment]
The issue isn't a compilation issue anymore. Now, a lot of Windows CMake tests are failing. These are the test results from #12885 Windows - https://sponge.corp.google.com/invocation?id=cec2d2e1-1657-4e1d-845e-bab8f89dc01b&searchFor=

C: It looks like all CMake tests are timing out
C#: About half of the tests are timing out
Python: All tests, except 1, time out

I'm not saying your PR is bad; it's great that we can compile under CMake again. But there still needs more work to be done to fix CMake.

**Comment by ctiller** [comment]
Suggest closing and filing a new bug.

**Comment by ctiller** [comment]
I'm unable to log into my Windows machine currently, so there's no hope of me looking at this.

**Comment by matt-kwong** [comment]
Opened #12918 as the new bug
