### ISSUE TITLE
bin_encoder.c failed to build with GCC 6.0.0

### ISSUE THREAD

**Issue by guoxiao** [grpc/grpc#6198]
I met the following problem while building `grpc` with gcc 6.0.0
```
src/core/ext/transport/chttp2/transport/bin_encoder.c: In function ‘grpc_chttp2_base64_encode_and_huffman_compress_impl’:
src/core/ext/transport/chttp2/transport/bin_encoder.c:197:32: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
     enc_add2(&out, in[0] >> 2, (uint8_t)((in[0] & 0x3) << 4) | (in[1] >> 4));
                                ^
src/core/ext/transport/chttp2/transport/bin_encoder.c:198:20: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
     enc_add2(&out, (uint8_t)((in[1] & 0xf) << 2) | (in[2] >> 6),
                    ^
src/core/ext/transport/chttp2/transport/bin_encoder.c:213:16: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
                (uint8_t)((in[0] & 0x3) << 4) | (uint8_t)(in[1] >> 4));
                ^
```

**Comment by ctiller** [comment]
Which compiler and version are you using, and on which platform?

**Comment by guoxiao** [comment]
@ctiller I'm on Fedora 24 with gcc 6.0.0.

**Comment by dgquintas** [comment]
I'll install fedora 24 and try to repro, bearing in mind that Fedora 24 is an alpha release of the distro.

**Comment by ctiller** [comment]
Is there a dockerhub image available?

Might be worth adding to our portability suite.

**Comment by dgquintas** [comment]
Not yet: https://github.com/docker-library/official-images/blob/master/library/fedora

**Comment by dgquintas** [comment]
I don't even make it that far:

```
third_party/boringssl/crypto/pem/pem_lib.c: In function ‘PEM_get_EVP_CIPHER_INFO’:
third_party/boringssl/crypto/pem/pem_lib.c:470:33: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
  if (*header != '4') return(0); header++;
                                 ^~~~~~
third_party/boringssl/crypto/pem/pem_lib.c:470:2: note: ...this ‘if’ clause, but it is not
  if (*header != '4') return(0); header++;
  ^~
third_party/boringssl/crypto/pem/pem_lib.c:471:33: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
  if (*header != ',') return(0); header++;
                                 ^~~~~~
third_party/boringssl/crypto/pem/pem_lib.c:471:2: note: ...this ‘if’ clause, but it is not
  if (*header != ',') return(0); header++;
  ^~
cc1: all warnings being treated as errors
```

@guoxiao didn't you run into that too?

**Comment by dgquintas** [comment]
Note that in addition the the changes from #6224 , two trivial ones are also required for boringssl (to be followed up with the boringssl maintainers).
