### ISSUE TITLE
grpc 1.0.0 does not build with protobuf 3.1.0

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#8201]
I think grpc 1.0.0 ships with some proto headers that should better be auto-generated:
```
[CXX]     Compiling src/cpp/ext/reflection.pb.cc
In file included from src/cpp/ext/reflection.grpc.pb.cc:39:0:
include/grpc++/ext/reflection.pb.h:51:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
include/grpc++/ext/reflection.pb.h:52:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
include/grpc++/ext/reflection.pb.h:53:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
```
