### ISSUE TITLE
v1.37.0 include error

### ISSUE THREAD

**Issue by francky06l** [grpc/grpc#26122]
### What version of gRPC and what language are you using?

1.37.0
### What operating system (Linux, Windows,...) and version?

Both
### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC 7.5
MSVC 2019 16.9.4

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

#include <grpcpp/server.h>

### What did you expect to see?
Compiling

### What did you see instead?
In file included from /home/franck/Extra/grpcfinal/include/grpcpp/impl/codegen/completion_queue.h:43:0,
                 from /home/franck/Extra/grpcfinal/include/grpcpp/channel.h:28,
                 from /home/franck/Extra/grpcfinal/include/grpcpp/server.h:30,
                 from grpc_server.h:7,
                 from grpccalamari.cpp:8:
/home/franck/Extra/grpcfinal/include/grpcpp/impl/codegen/sync.h:35:10: fatal error: absl/synchronization/mutex.h: No such file or directory
 #include "absl/synchronization/mutex.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by drfloob** [comment]
It does seem like either the submodules have not been initialized, or your include path is somehow incorrect. Given that the "project is quite big", I'm curious if you can build a minimal example that suffers from the same problems, maybe one of the include example projects.

**Comment by francky06l** [comment]
Well, the same code compile and works on 1.36.4
My include path points to the install path / include. 
I can reproduce in a simple cpp using a single header file:

```
#pragma once
#include <string>
#include <map>
#include <future>

#include <grpc/grpc.h>
#include <grpcpp/server.h>
#include <grpcpp/server_builder.h>
#include <grpcpp/server_context.h>
#include <grpcpp/security/server_credentials.h>
```
However I did not chek if grpcpp is still valid in 1.37, but I do not find this file 'absl/synchronization/mutex.h' in the installed include folder.
Maybe I am doing something wrong, I just surprised since this is the code of the route guide (example)

```
#include <grpc/grpc.h>
#include <grpcpp/security/server_credentials.h>
#include <grpcpp/server.h>
#include <grpcpp/server_builder.h>
#include <grpcpp/server_context.h>

```
quite the same right ?
Thanks

**Comment by francky06l** [comment]
Hello
I did reproduce the problem from the beginning.
First step getting the source 

```
franck@franckhp:~/dev> git clone -b v1.37.0 https://github.com/grpc/grpc grpc_1.37.0
Cloning into 'grpc_1.37.0'...
remote: Enumerating objects: 578983, done.
remote: Counting objects: 100% (322/322), done.
remote: Compressing objects: 100% (233/233), done.
remote: Total 578983 (delta 145), reused 192 (delta 88), pack-reused 578661
Receiving objects: 100% (578983/578983), 280.83 MiB | 6.19 MiB/s, done.
Resolving deltas: 100% (459585/459585), done.
Note: switching to '44c40ac23023b7b3dd82744372c06817cc203898'.


franck@franckhp:~/dev/grpc_1.37.0 ((v1.37.0))> git submodule update --init
Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'
Submodule 'third_party/opencensus-proto' (https://github.com/census-instrumentation/opencensus-proto.git) registered for path 'third_party/opencensus-proto'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
Submodule 'third_party/re2' (https://github.com/google/re2.git) registered for path 'third_party/re2'
Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/abseil-cpp'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/benchmark'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/bloaty'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/boringssl-with-bazel'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/cares/cares'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/envoy-api'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/googleapis'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/googletest'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/libuv'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/opencensus-proto'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/protobuf'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/protoc-gen-validate'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/re2'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/udpa'...
Cloning into '/home/franck/dev/grpc_1.37.0/third_party/zlib'...
Submodule path 'third_party/abseil-cpp': checked out '6f9d96a1f41439ac172ee2ef7ccd8edf0e5d068c'
Submodule path 'third_party/benchmark': checked out '73d4d5e8d6d449fc8663765a42aa8aeeee844489'
Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
Submodule path 'third_party/boringssl-with-bazel': checked out '1a7359455220f7010def8c63f7c7e041ce6707c6'
Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
Submodule path 'third_party/envoy-api': checked out '18b54850c9b7ba29a4ab67cbd7ed7eab7b0bbdb2'
Submodule path 'third_party/googleapis': checked out '82944da21578a53b74e547774cf62ed31a05b841'
Submodule path 'third_party/googletest': checked out 'c9ccac7cb7345901884aabf5d1a786cfa6e2f397'
Submodule path 'third_party/libuv': checked out '15ae750151ac9341e5945eb38f8982d59fb99201'
Submodule path 'third_party/opencensus-proto': checked out '4aa53e15cbf1a47bc9087e6cfdca214c1eea4e89'
Submodule path 'third_party/protobuf': checked out 'd7e943b8d2bc444a8c770644e73d090b486f8b37'
Submodule path 'third_party/protoc-gen-validate': checked out '872b28c457822ed9c2a5405da3c33f386ac0e86f'
Submodule path 'third_party/re2': checked out 'aecba11114cf1fac5497aeb844b6966106de3eb6'
Submodule path 'third_party/udpa': checked out 'cc1b757b3eddccaaaf0743cbb107742bb7e3ee4f'
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'

```
Building, note that I want to use the existing Openssl and zlib:

```
franck@franckhp:~/dev/grpc_1.37.0 ((v1.37.0))> mkdir ~/Extra/grpcfinal
franck@franckhp:~/dev/grpc_1.37.0 ((v1.37.0))> mkdir cmake/build
franck@franckhp:~/dev/grpc_1.37.0 ((v1.37.0))> cd cmake/build/
franck@franckhp:~/dev/grpc_1.37.0/cmake/build ((v1.37.0))>
franck@franckhp:~/dev/grpc_1.37.0/cmake/build ((v1.37.0))> cmake -DgRPC_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DgRPC_SSL_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package gRPC_BUILD_CSHARP_EXT=OFF -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/Extra/grpcfinal ../..
# many lines here, this is the last one ....
-- Build files have been written to: /home/franck/dev/grpc_1.37.0/cmake/build
franck@franckhp:~/dev/grpc_1.37.0/cmake/build ((v1.37.0))> make -j 6
# last line of building
[100%] Built target grpcpp_channelz
franck@franckhp:~/dev/grpc_1.37.0/cmake/build ((v1.37.0))> make install
# Last line from install
-- Installing: /home/franck/Extra/grpcfinal/lib64/cmake/re2/re2Config-release.cmake

```
Getting some infos from pkg-config

```
franck@franckhp:~/dev/grpcbug> export PKG_CONFIG_PATH=$HOME/Extra/grpcfinal/lib64/pkgconfig:$HOME/Extra/grpcfinal/lib/pkgconfig
franck@franckhp:~/dev/grpcbug> pkg-config --cflags grpc++
-DOPENSSL_LOAD_CONF -I/home/franck/Extra/grpcfinal/include

franck@franckhp:~/dev/grpcbug> pkg-config --cflags protobuf
-I/home/franck/Extra/grpcfinal/include

franck@franckhp:~/dev/grpcbug> pkg-config --libs protobuf
-L/home/franck/Extra/grpcfinal/lib64 -lprotobuf -lpthread

franck@franckhp:~/dev/grpcbug> pkg-config --libs grpc++
-L/home/franck/Extra/grpcfinal/lib -lgrpc++ -labsl_statusor -labsl_status -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_synchronization -labsl_time -labsl_time_zone -labsl_civil_time -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_malloc_internal -labsl_stacktrace -labsl_debugging_internal -labsl_exponential_biased -labsl_cord -labsl_str_format_internal -labsl_hash -labsl_bad_variant_access -labsl_bad_optional_access -labsl_strings -labsl_strings_internal -labsl_base -labsl_spinlock_wait -labsl_int128 -labsl_city -labsl_throw_delegate -labsl_raw_logging_internal -labsl_log_severity -lgrpc -laddress_sorting -lre2 -lupb -lcares -lz -labsl_statusor -labsl_status -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_synchronization -labsl_time -labsl_time_zone -labsl_civil_time -labsl_graphcycles_internal -labsl_symbolize -labsl_demangle_internal -labsl_malloc_internal -labsl_stacktrace -labsl_debugging_internal -labsl_exponential_biased -labsl_cord -labsl_str_format_internal -labsl_hash -labsl_bad_variant_access -labsl_bad_optional_access -labsl_strings -labsl_strings_internal -labsl_base -labsl_spinlock_wait -labsl_int128 -labsl_city -labsl_throw_delegate -labsl_raw_logging_internal -labsl_log_severity -lgpr -labsl_synchronization -labsl_time -labsl_time_zone -labsl_civil_time -labsl_graphcycles_internal -labsl_status -labsl_cord -labsl_str_format_internal -labsl_bad_optional_access -labsl_symbolize -labsl_strings -labsl_strings_internal -labsl_int128 -labsl_demangle_internal -labsl_malloc_internal -labsl_stacktrace -labsl_debugging_internal -labsl_throw_delegate -labsl_base -labsl_spinlock_wait -labsl_raw_logging_internal -labsl_log_severity -lssl -lcrypto

franck@franckhp:~/dev/grpcbug> g++ --version
g++ (SUSE Linux) 7.5.0

```
Simple cpp file:

```
#include <iostream>
#include <grpc/grpc.h>
#include <grpcpp/server.h>

int main(int argc, char **argv)
{
    std::cout << "Here we are" << std::endl;
    exit(0);
}

```
Make file

```
#
CXX = g++

CPPFLAGS := -Wall -std=c++14 `pkg-config --cflags grpc++`
GRPCLIB := `pkg-config --libs protobuf-lite` `pkg-config --libs grpc++` 

all:
	g++ $(CPPFLAGS) $(GRPCLIB) -c tstmain.cpp -o tstmain

```
Trying to build

```
franck@franckhp:~/dev/grpcbug> make
g++ -Wall -std=c++14 `pkg-config --cflags grpc++` `pkg-config --libs protobuf-lite` `pkg-config --libs grpc++`  -c tstmain.cpp -o tstmain
In file included from /home/franck/Extra/grpcfinal/include/grpcpp/impl/codegen/completion_queue.h:43:0,
                 from /home/franck/Extra/grpcfinal/include/grpcpp/channel.h:28,
                 from /home/franck/Extra/grpcfinal/include/grpcpp/server.h:30,
                 from tstmain.cpp:6:
/home/franck/Extra/grpcfinal/include/grpcpp/impl/codegen/sync.h:35:10: fatal error: absl/synchronization/mutex.h: No such file or directory
 #include "absl/synchronization/mutex.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:8: all] Error 1
franck@franckhp:~/dev/grpcbug> 

```
This line in grpcc/impl/codegen/sync.h
    #include "absl/synchronization/mutex.h"
is causing the problem, there is no  /absl folder in the include folder installed, maybe I miss a switch or directive to install the absl include ?

Thanks
F.

**Comment by mtorromeo** [comment]
I can confirm the issue. I'm holding out on updating the grpc package on Arch Linux due to this.

Seems to have been introduced in commit 6468d8a69de44ddea82cec7227837374f9be6081

**Comment by francky06l** [comment]
Right, that what I thought, the install it not copying the abseil needed header file.
Let me know if you want me to test a patch or a change.

Thank to have spent time on this.
F.

**Comment by drfloob** [comment]
Excellent, thanks for diagnosing it! @veblush I think you're working on Mutex right now, PTAL.

**Comment by veblush** [comment]
Since gRPC++ public headers started to include absl files, those files should be installed properly. Abseil C++ library needs a separate installation (it won't be installed automatically by gRPC) so you need to install it in advance. You can check the example [here](https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake_pkgconfig.sh)

**Comment by francky06l** [comment]
Hello,
You mean that the abseil C++ is compiled (the static lib are built and set in install/lib - not properly ?) when installing gRPC, but I need to install abseil separately just to have the header files for gRpc to work in C++ ?  Sounds strange to me ..
Also you have to review the "Building from source" instructions :)
Thanks

**Comment by mtorromeo** [comment]
> Abseil C++ library needs a separate installation (it won't be installed automatically by gRPC) so you need to install it in advance.

That's not really how abseil is meant to be used. The developers of the library are advocating not depending on precompiled versions of the library [1] and basically it should only be used by embedding the source code.

Developers are encouraged to always use master [2] and so applications will end up depending on arbitrary commits which is a PITA for packagers.

[1] https://abseil.io/about/compatibility
[2] https://github.com/abseil/abseil-cpp/#releases

**Comment by veblush** [comment]
@francky06l When you install Abseil with pkg-config, you'd better using `-DgRPC_ABSL_PROVIDER=package` so that gRPC uses the installed one. Can you give me a pointer to the doc to be updated? 

@mtorromeo Actually this is what we got after having a discussion with the Abseil team. If you're using pkg-config for gRPC, it actually uses prebuilt Abseil library no matter abseil is installed explicitly or implicitly. So it doesn't change it much. Actually installing pkg-config separately is better because it allows for the application developer to choose the exact version of Abseil library particularly when they're using it too.

**Comment by francky06l** [comment]
I understand all this, it is just do not make my life easier :)
I have also a team (that might not understand the deep reason), for now I'll stick to 1.36.4 and will reorganize.
About the "build from source", better to say that from 1.37 onward,  for C++ user (must be very few), they have to manage abseil separately  => https://github.com/grpc/grpc/blob/master/BUILDING.md

Usually, when version are increasing it easier, it's not bullet proof apparently !   

Thanks guys, do not get me wrong, I much appreciate your work !!

**Comment by nanonyme** [comment]
There are indeed C++ projects building against grpcio, eg buildbox-common. At the moment when grpc is installed, the resultant header files are plain broken since they refer to other headers which do not exist when grpc is built using abseil as git submodule.

**Comment by francky06l** [comment]
But if abseil is only use for grpc in this project, it should not be any problem right ?
I could simply copy the header of abseil-cpp/absl  to install/include/absl something like

```
cd third_party/abseil-cpp/absl
find . -name '*.h' | cpio -pdm grpcfinal/include/absl

```
Not sure how I would do this on windows though ..
Thanks
F.

**Comment by nanonyme** [comment]
I would suggest that abseil is bundled and installed under subdirectory when grpc is built using it as submodule. Then grpc is free to ship these headers without conflicting with external abseil. Grpc headers should be adjusted to work with both flows. When Grpc is built against external abseil, then that should also be used when Grpc is linked against.

**Comment by veblush** [comment]
@nanonyme That's mainly for the development or some build setup using submodules. Once it's installed, those directories won't matter.

**Comment by francky06l** [comment]
So, at the end Grpc C++ MUST install / build abseil separately, best to specify this in "Build from source".
Thanks

**Comment by FMeinicke** [comment]
Hi, so I just stumbled across this issue as well and I find gRPC's install behaviour a bit weird.  
@veblush, you say that users are expected to install protobuf and abseil themselves. I agree with you on that if the user set `-DgRPC_PROTOBUF_PROVIDER=package` and `-DgRPC_ABSL_PROVIDER=package`. However, when I don't explicitly set the provider to `package` gRPC will take the bundled protobuf and abseil versions from the third-party directory and compile those. At least in the case of protobuf all library and header files are installed properly. That is what I would expect to see.  
Now since gRPC started to include abseil headers in their own public headers I believe that gRPC should also install abseil's public headers. The built abseil libraries are already installed by gRPC anyway so I don't see any reason why the header files shouldn't be installed as well.

Looking at the CMakeLists.txt files for protobuf and abseil explains the different behaviour: protobuf will always install itself properly even when it's used as a submodule and gRPC does not need to do any additional steps. abseil on the other hand will not. It will detect if it's used as a submodule and disable its install steps. That's why gRPC added an install step for abseil in `cmake/abseil-cpp.cmake`. But this only installs the built library files and not the headers (which at least IMHO should be done since gRPC's public headers require abseil's). I also think that it wouldn't be that big of a deal to add an install step to install abseil's headers.

Just wanted to put my opinion out there. For now, I can live with having to install abseil first before building/installing gRPC, I just think it's inconsistent with the behaviour of the protobuf dependency and not really user friendly.

**Comment by veblush** [comment]
FYI, I'm revisiting this issue and coming up with a way to install abseil along with gRPC when installing it from modules.
