### ISSUE TITLE
Please backport PR 42918 to the v1.83.x branch and make a v1.83.1

### ISSUE THREAD

**Issue by acmorrow** [grpc/grpc#43261]
### What version of gRPC and what language are you using?
1.83.0

### What operating system (Linux, Windows,...) and version?
Linux, multiple distros / versions

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Conan upgraded to grpc 1.83 and our builds pulled it, but it no longer compiles due to the issue addressed in #42918  

### What did you expect to see?
A passing compile of gRPC

### What did you see instead?
```
 78%] Building CXX object CMakeFiles/grpc.dir/src/core/lib/transport/error_utils.cc.o
/Users/runner/.conan2/p/b/grpc4fd204d3a3518/b/src/src/core/lib/surface/legacy_channel.cc:183:28: error: object of type 'std::optional<absl::FunctionRef<void (grpc_core::Arena *)>>' cannot be assigned because its copy assignment operator is implicitly deleted
  183 |   args.arena_init_function = arena_init_function;
      |                            ^
/Applications/Xcode_26.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/optional:730:45: note: explicitly defaulted function was implicitly deleted here
  730 |   _LIBCPP_HIDE_FROM_ABI constexpr optional& operator=(const optional&) = default;
      |                                             ^
/Applications/Xcode_26.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/optional:586:7: note: copy assignment operator of 'optional<absl::FunctionRef<void (grpc_core::Arena *)>>' is implicitly deleted because base class '__optional_sfinae_assign_base_t<absl::FunctionRef<void (grpc_core::Arena *)>>' (aka '__sfinae_assign_base<(is_copy_constructible<absl::FunctionRef<void (grpc_core::Arena *)>>::value && is_copy_assignable<absl::FunctionRef<void (grpc_core::Arena *)>>::value), (is_move_constructible<absl::FunctionRef<void (grpc_core::Arena *)>>::value && is_move_assignable<absl::FunctionRef<void (grpc_core::Arena *)>>::value)>') has a deleted copy assignment operator
  586 |       private __optional_sfinae_assign_base_t<_Tp> {
      |       ^
/Applications/Xcode_26.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/c++/v1/__tuple/sfinae_helpers.h:119:25: note: 'operator=' has been explicitly marked deleted here
  119 |   __sfinae_assign_base& operator=(__sfinae_assign_base const&) = delete;
      |                         ^
```
