### ISSUE TITLE
Unable to install grpcio on pypy:3.9 base image 

### ISSUE THREAD

**Issue by Rossco8** [grpc/grpc#29517]
### What version of gRPC and what language are you using?
1.44.0

### What operating system (Linux, Windows,...) and version?
debian base image pypy:3.9-slim-bullseye

### What runtime / compiler are you using (e.g. python version or version of gcc)
 pypy:3.9

### What did you do?
Unable to install grpcio (a dependency of google-auth)
```
FROM pypy:3.9-slim-bullseye

RUN apt-get update -y \
    && apt-get install devscripts build-essential cargo -y \
    && pypy3 -m pip install --upgrade setuptools \
    && pypy3 -m pip install --no-cache-dir \
    google-auth google-cloud-tasks \
    && apt-get remove devscripts build-essential -y
```

### What did you see instead?
Warnings and errors are too numerous, 1000's of lines, difficult to see which is the root error message

```
 gcc -pthread -DNDEBUG -O2 -fPIC -I/opt/pypy/include/pypy3.9 -c /tmp/tmp4njm0j5n/a.c -o None/tmp/tmp4njm0j5n/a.o
      Traceback (most recent call last):
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 173, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/tmp/pip-install-51in7ieq/grpcio_73fa8248b06f4e14944a74af58684e5d/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/ccompiler.py", line 917, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

Traceback (most recent call last):
        File "/tmp/pip-install-51in7ieq/grpcio_73fa8248b06f4e14944a74af58684e5d/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/tmp/pip-install-51in7ieq/grpcio_73fa8248b06f4e14944a74af58684e5d/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/opt/pypy/lib/pypy3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/opt/pypy/lib/pypy3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/opt/pypy/lib/pypy3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/opt/pypy/lib/pypy3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/tmp/pip-install-51in7ieq/grpcio_73fa8248b06f4e14944a74af58684e5d/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 176, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

```

**Comment by gnossen** [comment]
Looks like this is the actual error:

```
      gcc -pthread -DNDEBUG -O2 -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.46.1\" -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/opt/pypy/include/pypy3.9 -c src/core/lib/slice/b64.cc -o python_build/temp.linux-x86_64-pypy39/src/core/lib/slice/b64.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
      cc1plus: warning: command-line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
      src/python/grpcio/grpc/_cython/cygrpc.cpp: In function ‘int __Pyx_async_gen_init_hooks(__pyx_PyAsyncGenObject*)’:
      src/python/grpcio/grpc/_cython/cygrpc.cpp:134650:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘async_gen_finalizer’
      134650 |     finalizer = tstate->async_gen_finalizer;
             |                         ^~~~~~~~~~~~~~~~~~~
      src/python/grpcio/grpc/_cython/cygrpc.cpp:134655:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘async_gen_firstiter’
      134655 |     firstiter = tstate->async_gen_firstiter;
             |                         ^~~~~~~~~~~~~~~~~~~

```

It looks like the [PyPy team is aware of an incompatibility between Cython and PyPy](https://foss.heptapod.net/pypy/pypy/-/issues/3280) but haven't acted on it.

Fixing this is going to require more than just the gRPC team.

**Comment by gnossen** [comment]
[Related](https://github.com/grpc/grpc/issues/4221)

**Comment by Rossco8** [comment]
I suppose I'm the only person in the world trying to use grpcio on pypy if the issue has been around for that long

**Comment by maestrx** [comment]
Im impaced by this as well trying to use pypy with gcloud packages

**Comment by JunpingHe** [comment]
When will this problem be resolved?

**Comment by XuanWang-Amos** [comment]
We need either Cython or Pypy to resolve the issue on their side first before we can help with it.

**Comment by mattip** [comment]
Cython and PyPy have improved support for asyncio semantics. But the changes were only released for Cython3.0.0, not for the recent Cython 0.29.35. Unfortunately grpc does not build with Cython3.0.0, some small changes are needed. More (too much?) info is on the [PyPy issue](https://foss.heptapod.net/pypy/pypy/-/issues/3280#note_297288). Is there a plan for gprc to support Cython 3?

**Comment by gnossen** [comment]
[Cython 3.0 is still in pre-release](https://pypi.org/project/Cython/3.0.0b3/). We'll work on integrating with it once it is no longer a pre-release.

**Comment by mattip** [comment]
According to [this comment](https://foss.heptapod.net/pypy/pypy/-/issues/3280#note_299743),
> I've been testing with pypy3.9-v7.3.12 in Docker and running (with cython HEAD) `pip install GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install grpcio --no-build-isolation` Everything is stable ... Note that I am currently using `grpcio==1.56.0`. I tested with `grpcio<1.43` and still experienced some instability, hence why I opted for the latest version.

there is room for some optimism.

**Comment by wbarnha** [comment]
I figure now is a good time to clarify on instability. `grpcio<1.43` segfaulted regularly, but I never got the opportunity to do a traceback.
