### ISSUE TITLE
compiling for php 8.0.1 on latest alpine image throws errors

### ISSUE THREAD

**Issue by loomsen** [grpc/grpc#25250]
### What version of gRPC and what language are you using?
PHP 8.0.1 from the `php:8.0-fpm-alpine` image
grpc version: 1.35.0

### What operating system (Linux, Windows,...) and version?
Alpine Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
PEAR Version: 1.10.12
PHP Version: 8.0.1
Zend Engine Version: 4.0.1
Running on: Linux 9cc30c3b6ac7 5.9.11-200.fc33.x86_64 #1 SMP Tue Nov 24 18:18:01 UTC 2020 x86_64
```

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

In latest php:8.0-fpm-alpine container (at the time of this writing this is sha256:86d75bc1efb2dd7df36e73d2a7166ccacb3a8114dd66e5fea3e832fb15e29fa1)
```
$ apk add --no-cache --virtual .phpize \
        augeas-dev \
        autoconf \
        composer \
        curl-dev \
        cyrus-sasl-dev \
        dpkg-dev dpkg \
        fcgi \
        file \
        freetype \
        freetype-dev \
        g++ \
        gcc \
        gd \
        icu-dev \
        icu-libs \
        libc-dev \
        libc-utils \
        libevent \
        libevent-dev \
        libffi-dev \
        libidn \
        libjpeg-turbo-dev \
        libmemcached-dev \
        libmemcached-libs \
        libpng \
        libpng-dev \
        linux-headers \
        make \
        musl-dev \
        musl-utils \
        pkgconf \
        re2c \
        scanelf \
        zlib \
        zlib-dev
$ pecl install gRPC
```

### What did you expect to see?

successful build

### What did you see instead?

build failed:

```
Step #5: Starting to download grpc-1.35.0.tgz (4,254,087 bytes)
Step #5: .................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done: 4,254,087 bytes
Step #5: 1978 source files, building
Step #5: running: phpize
Step #5: Configuring for:
Step #5: PHP Api Version:         20200930
Step #5: Zend Module Api No:      20200930
Step #5: Zend Extension Api No:   420200930
Step #5: building in /tmp/pear/temp/pear-build-defaultuserdPbFHh/grpc-1.35.0
Step #5: running: /tmp/pear/temp/grpc/configure --with-php-config=/usr/local/bin/php-config
Step #5: checking for grep that handles long lines and -e... /bin/grep
Step #5: checking for egrep... /bin/grep -E
Step #5: checking for a sed that does not truncate output... /bin/sed
Step #5: checking for pkg-config... /usr/bin/pkg-config
Step #5: checking pkg-config is at least version 0.9.0... yes
Step #5: checking for cc... cc
Step #5: checking whether the C compiler works... yes
Step #5: checking for C compiler default output file name... a.out
Step #5: checking for suffix of executables...
Step #5: checking whether we are cross compiling... no
Step #5: checking for suffix of object files... o
Step #5: checking whether we are using the GNU C compiler... yes
Step #5: checking whether cc accepts -g... yes
Step #5: checking for cc option to accept ISO C89... none needed
Step #5: checking how to run the C preprocessor... cc -E
Step #5: checking for icc... no
Step #5: checking for suncc... no
Step #5: checking for system library directory... lib
Step #5: checking if compiler supports -R... no
Step #5: checking if compiler supports -Wl,-rpath,... yes
Step #5: checking build system type... x86_64-pc-linux-musl
Step #5: checking host system type... x86_64-pc-linux-musl
Step #5: checking target system type... x86_64-pc-linux-musl
Step #5: checking for PHP prefix... /usr/local
Step #5: checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
Step #5: checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20200930
Step #5: checking for PHP installed headers prefix... /usr/local/include/php
Step #5: checking if debug is enabled... no
Step #5: checking if zts is enabled... no
Step #5: checking for gawk... no
Step #5: checking for nawk... no
Step #5: checking for awk... awk
Step #5: checking if awk is broken... no
Step #5: checking whether to enable grpc support... yes, shared
Step #5: checking for g++... g++
Step #5: checking whether we are using the GNU C++ compiler... yes
Step #5: checking whether g++ accepts -g... yes
Step #5: checking how to run the C++ preprocessor... g++ -E
Step #5: checking for a sed that does not truncate output... /bin/sed
Step #5: checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
Step #5: checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
Step #5: checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
Step #5: checking for BSD-compatible nm... /usr/bin/nm -B
Step #5: checking whether ln -s works... yes
Step #5: checking how to recognize dependent libraries... pass_all
Step #5: checking for ANSI C header files... yes
Step #5: checking for sys/types.h... yes
Step #5: checking for sys/stat.h... yes
Step #5: checking for stdlib.h... yes
Step #5: checking for string.h... yes
Step #5: checking for memory.h... yes
Step #5: checking for strings.h... yes
Step #5: checking for inttypes.h... yes
Step #5: checking for stdint.h... yes
Step #5: checking for unistd.h... yes
Step #5: checking dlfcn.h usability... yes
Step #5: checking dlfcn.h presence... yes
Step #5: checking for dlfcn.h... yes
Step #5: checking how to run the C++ preprocessor... g++ -E
Step #5: checking the maximum length of command line arguments... 98304
Step #5: checking command to parse /usr/bin/nm -B output from cc object... ok
Step #5: checking for objdir... .libs
Step #5: checking for ar... ar
Step #5: checking for ranlib... ranlib
Step #5: checking for strip... strip
Step #5: checking if cc supports -fno-rtti -fno-exceptions... no
Step #5: checking for cc option to produce PIC... -fPIC
Step #5: checking if cc PIC flag -fPIC works... yes
Step #5: checking if cc static flag -static works... yes
Step #5: checking if cc supports -c -o file.o... yes
Step #5: checking whether the cc linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
Step #5: checking whether -lc should be explicitly linked in... no
Step #5: checking dynamic linker characteristics... GNU/Linux ld.so
Step #5: checking how to hardcode library paths into programs... immediate
Step #5: checking whether stripping libraries is possible... yes
Step #5: checking if libtool supports shared libraries... yes
Step #5: checking whether to build shared libraries... yes
Step #5: checking whether to build static libraries... no
Step #5: 
Step #5: creating libtool
Step #5: appending configuration tag "CXX" to libtool
Step #5: checking for ld used by g++... /usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64
Step #5: checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) is GNU ld... yes
Step #5: checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
Step #5: checking for g++ option to produce PIC... -fPIC
Step #5: checking if g++ PIC flag -fPIC works... yes
Step #5: checking if g++ static flag -static works... yes
Step #5: checking if g++ supports -c -o file.o... yes
Step #5: checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
Step #5: checking dynamic linker characteristics... GNU/Linux ld.so
Step #5: (cached) (cached) checking how to hardcode library paths into programs... immediate
Step #5: configure: patching config.h.in
Step #5: configure: creating ./config.status
Step #5: config.status: creating config.h
Step #5: running: make
[...]
Step #5: /bin/sh /tmp/pear/temp/pear-build-defaultuserdPbFHh/grpc-1.35.0/libtool --mode=compile cc -I. -I/tmp/pear/temp/grpc -I/tmp/pear/temp/pear-build-defaultuserdPbFHh/grpc-1.35.0/include -I/tmp/pear/temp/pear-build-defaultuserdPbFHh/grpc-1.35.0/main -I/tmp/pear/temp/grpc -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb  -DHAVE_CONFIG_H  -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -g -O2   -fvisibility=hidden     -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_
Step #5: LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0     -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -c /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c -o third_party/upb/upb/json_decode.lo
Step #5:  cc -I. -I/tmp/pear/temp/grpc -I/tmp/pear/temp/pear-build-defaultuserdPbFHh/grpc-1.35.0/include -I/tmp/pear/temp/pear-build-defaultuserdPbFHh/grpc-1.35.0/main -I/tmp/pear/temp/grpc -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -g -O2 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATF
Step #5: ORK=1 -c /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c  -fPIC -DPIC -o third_party/upb/upb/.libs/json_decode.o
Step #5: /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: In function 'jsondec_value':
Step #5: /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:774:10: error: '*((void *)&val+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
Step #5:   774 |   return val;
Step #5:       |          ^~~
Step #5: /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:738:10: error: '*((void *)&val+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
Step #5:   738 |   return val;
Step #5:       |          ^~~
Step #5: /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: At top level:
Step #5: cc1: note: unrecognized command-line option '-Wno-parentheses-equality' may have been intended to silence earlier diagnostics
Step #5: cc1: all warnings being treated as errors
Step #5: make: *** [Makefile:2111: third_party/upb/upb/json_decode.lo] Error 1
Step #5: ERROR: `make' failed
```

### Anything else we should know about your project / environment?

It works with the `php:8.0.0-fpm-alpine` image, so some change must have been introduced between php 8.0.0 and php 8.0.1.

**Comment by mjsambol** [comment]
I've got something very similar looking, in different circumstances. Trying to install grpc on debian, 
PEAR Version: 1.10.9
PHP Version: 7.4.11
Zend Engine Version: 3.4.0

Ran command:
sudo pecl install grpc

After many minutes of furious building, I got the same results as reported above:

/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: In function ‘jsondec_value’:
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:774:10: error: ‘*((void *)&val+8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  774 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:738:10: error: ‘*((void *)&val+8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  738 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:2094: third_party/upb/upb/json_decode.lo] Error 1
ERROR: `make' failed

**Comment by mlocati** [comment]
A temporary workaround is to set the `CPPFLAGS` environment variable to `-Wno-maybe-uninitialized`.

For example:

```sh
CPPFLAGS="-Wno-maybe-uninitialized" pickle install grpc
```

**Comment by mjsambol** [comment]
The CPPFLAGS workaround did not work for me, I got the same exact error.

**Comment by mlocati** [comment]
Yep, you can use both pecl and pickle. By starting a Docker container with `docker run --rm -it php:8.0.1-cli-alpine3.13 sh`:

- using pecl:
    ```sh
    apk add $PHPIZE_DEPS libstdc++ zlib-dev linux-headers
    CPPFLAGS="-Wno-maybe-uninitialized" pecl install grpc-1.35.0
    docker-php-ext-enable grpc
    php --ri grpc
    ```
- using pickle:
    ```sh
    apk add $PHPIZE_DEPS libstdc++ zlib-dev linux-headers
    curl -sSLf -o pickle.phar https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar
    CPPFLAGS="-Wno-maybe-uninitialized" php pickle.phar install grpc-1.35.0
    docker-php-ext-enable grpc
    php --ri grpc
    ```

**Comment by mlocati** [comment]
And PS: you can now use my [`install-php-extensions`](https://github.com/mlocati/docker-php-extension-installer) script to install grpc 1.35.0 (as well as tons of other PHP extensions), both on Debian-based and Alpine-based PHP docker images.

**Comment by stanley-cheung** [comment]
Will look into this. Funny how 8.0.1 wasn't listed as a release yet in the PHP [site](https://www.php.net/releases/index.php) itself. Or maybe they stop updating that.

**Comment by mlocati** [comment]
I think it's an issue with the gcc version that comes with Alpine Linux 3.13. With other distros there isn't any issue

**Comment by hotrush** [comment]
Getting the same issue with `php:7.4-cli-alpine`

```
 cc -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserabPCPN/grpc-1.35.0/include -I/tmp/pear/temp/pear-build-defaultuserabPCPN/grpc-1.35.0/main -I/tmp/pear/temp/grpc -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-v
alue -std=c11 -g -O2 -c /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c  -fPIC -DPIC -o third_party/upb/upb/.libs/json_decode.o
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: In function 'jsondec_value':
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:774:10: error: '*((void *)&val+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  774 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:738:10: error: '*((void *)&val+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  738 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: At top level:
cc1: note: unrecognized command-line option '-Wno-parentheses-equality' may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:2094: third_party/upb/upb/json_decode.lo] Error 1
ERROR: `make' failed
ERROR: Service 'charts-service' failed to build : The command '/bin/sh -c set -xe     && apk update     && apk add --no-cache         libzip-dev         unzip         autoconf         build-base         g++ make zlib-dev linux-headers     && pecl install          grpc protobuf     && docker-php-ext-enable grpc protobuf     && docker-php-ext-install intl zip opcache' returned a non-zero code: 1
```

**Comment by schleumer** [comment]
Same on:

PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )
Ubuntu 20.10

```
 cc -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootAoOrTP/grpc-1.35.0/include -I/tmp/pear/temp/pear-build-rootAoOrTP/grpc-1.35.0/main -I/tmp/pear/temp/grpc -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unus
ed-value -std=c11 -g -O2 -c /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c  -fPIC -DPIC -o third_party/upb/upb/.libs/json_decode.o
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: In function ‘jsondec_value’:
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:774:10: error: ‘*((void *)&val+8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  774 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:738:10: error: ‘*((void *)&val+8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  738 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:2094: third_party/upb/upb/json_decode.lo] Error 1
ERROR: `make' failed
```

**Comment by stanley-cheung** [comment]
Looks like the issue has already been fixed in upstream `upb`:

https://github.com/protocolbuffers/upb/blob/53f5d9f69b4d6ba6ca3149e1913bd9834f4d6c78/upb/json_decode.c#L708
and 
https://github.com/protocolbuffers/upb/blob/53f5d9f69b4d6ba6ca3149e1913bd9834f4d6c78/upb/json_decode.c#L745

This should be picked up by this repo the next time `third_party/upb` is being updated.

**Comment by kylerqws** [comment]
I have a similar problem, but with a different message error. Installing zlib-dev linux-headers packages helped.
