### ISSUE TITLE
gcc4.7 build failed in default_health_check_service.cc

### ISSUE THREAD

**Issue by starius** [grpc/grpc#10948]
```
src/cpp/server/health/default_health_check_service.cc: In constructor ‘grpc::DefaultHealthCheckService::DefaultHealthCheckService()’:
src/cpp/server/health/default_health_check_service.cc:135:17: error: ‘class std::map<std::basic_string<char>, bool>’ has no member named ‘emplace’
```

gcc version 4.7.2

This issue can be solved with this patch:

```diff
diff --git a/src/cpp/server/health/default_health_check_service.cc b/src/cpp/server/health/default_health_check_service.cc
index bc98ce7..a866af9 100644
--- a/src/cpp/server/health/default_health_check_service.cc
+++ b/src/cpp/server/health/default_health_check_service.cc
@@ -131,7 +131,7 @@ Status DefaultHealthCheckService::HealthCheckServiceImpl::Check(
 }
 
 DefaultHealthCheckService::DefaultHealthCheckService() {
-  services_map_.emplace("", true);
+  services_map_[""] = true;
 }
 
 void DefaultHealthCheckService::SetServingStatus(
```

Is this `emplace` important here? Can we use `[]` syntax to fix gcc 4.7 build?

**Comment by yang-g** [comment]
I am okay changing it to `[ ]`. Do you want to send a PR? Or I can do it. Thanks.

**Comment by vjpai** [comment]
I can believe that at the current time, no other features will fail on 4.7 . However: we are no longer claiming to support 4.7 as it doesn't support c++11 . The first gcc to support c++11 is 4.8 and that is our expected minimum. As we increase usage of c+11 features (in particular, certain memory model details that were first supported in 4.8), the code will no longer work on 4.7.

**Comment by starius** [comment]
> Do you want to send a PR? Or I can do it.

Can you do it, please?

**Comment by starius** [comment]
> As we increase usage of c+11 features (in particular, certain memory model details that were first supported in 4.8), the code will no longer work on 4.7.

`Makefile` has a detection of C++11 (grep by `HAS_CXX11`). I guess all those C++11 features we are going to use have C++03 alternatives that can be supported by conditional compilation.

**Comment by vjpai** [comment]
We should probably remove that check since we've been requiring C++11 since version 1.1 . We don't use the results anymore except for setting the -std=c++11 flag , and we no longer support alternatives like we used to (for example, the fake `nullptr` that used to live in `include/grpc++/impl/codegen/config.h` )

**Comment by yang-g** [comment]
Boris, as @vjpai mentioned we are no longer supporting pre-C++11 compilers. While making the change may re-enable the build for you, it can and will break at any time. After discussions I am not going to create the PR and you may want to make a local fork or pin to an earlier release to continue using 4.7. Thanks.
