### ISSUE TITLE
Does not build using VS2019 Toolset

### ISSUE THREAD

**Issue by william02210** [grpc/grpc#33689]
### What version of gRPC and what language are you using?
gRPC: 1.55.1 
Language: C++

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio Build Tools 16.5 (VS2019) (Toolset 142)

### What did you do?

- Followed the gRPC directions for[ building on Windows](https://github.com/grpc/grpc/blob/master/BUILDING.md#windows)
  - Built with OpenSSL
  - CMAKE v3.26.4
  - NASM: 2.16.01
  - Ninja: v1.11.1
  - Used x86 in call to vcvarsall.bat

### What did you expect to see?
The build complete successfully 

### What did you see instead?
The build fails 
`absl/functional/internal/any_invocable.h(563): error C2672: 'absl::lts_20230125::internal_any_invocable::CoreImpl<false,ReturnType>::InitializeStorage': no matching overloaded function found
`
### Anything else we should know about your project / environment?
- This also fails using vcpkg
- This works if building with VS2022 tooset

**Comment by janboelke** [comment]
Hello,
I am seeing the same issue.
I tried to build grpc-1.56.0 with toolset VC14.2 and also grpc-1.52.2 with toolset VC14.2.
I used x64 in the call to vcvarsall.bat.
The error message is the same.

Should I create a separate issue still?

**Comment by PavelKsdnv** [comment]
I have the same issue, with grpc 1.56.2, win 10, tried both vs19 and vs22 - no luck. Followed the same guide. My problem is it cannot find external symbols

**Comment by yashykt** [comment]
@PavelKsdnv That sounds like a linker error. It's probably unrelated to this.

**Comment by william02210** [comment]
@yashykt Verified building gRPC via vcpkg works with MS Toolset 16.11. I have not had a chance to try building outside of vcpkg; however, have no reason to believe the results will be different.

**Comment by william02210** [comment]
Closing as the build works in a later version of the build tools which conform to the same ABI.
