### PR TITLE
Update gflags in Bazel build

### PR DESCRIPTION
**Pull request by drigz**
The updated gflags no longer leaks an internal config.h header, which
can avoid problems like https://github.com/google/glog/issues/297.

### CODE REVIEW

**Comment by dgquintas** [comment]
The submodule commit would also need updating.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by drigz** [comment]
Thanks, done.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
There are a number of test failures. For the sanity one, you also need to update the tools/run_tests/sanity/check_submodules.sh file (sorry, forgot that one).

Then there's another, more mysterious one: https://sponge.corp.google.com/target?id=2595bcd4-a69b-495c-98eb-9cbfae162bfa&target=grpc/ubuntu/pull_request/grpc_portability_build_only&searchFor=&show=FAILED&sortBy=STATUS
```
CMakeFiles/interop_test.dir/test/cpp/interop/interop_test.cc.o: In function `__static_initialization_and_destruction_0':
/var/local/git/grpc/test/cpp/interop/interop_test.cc:43: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
libgrpc++_test_config.a(test_config_cc.cc.o): In function `grpc::testing::InitTest(int*, char***, bool)':
/var/local/git/grpc/test/cpp/util/test_config_cc.cc:33: undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/interop_test.dir/build.make:146: recipe for target 'interop_test' failed

```
It seems there's a conflict of some sort with the new gflags.

**Comment by drigz** [comment]
That is mysterious, particularly because not very much changed in gflags between the two versions - mostly related to the Bazel & Windows build.

The only thing I can think is that interop_test.cc finds a `gflags.h` that uses the `google` namespace, but the library passed to the linker uses the `gflags` namespace. But I don't know what would have caused that to change...

**Comment by drigz** [comment]
PS, any guidance on how I can reproduce this failure? I tried `tools/run_tests/run_tests.py --use_docker -l c++` but it's an hour or so in to running very many tests, so I think it has not reproduced the build failure.

**Comment by dgquintas** [comment]
@adelez / @matt-kwong , would you know how to run the failing test suite (grpc portability build only) locally?

**Comment by matt-kwong** [comment]
You can reproduce the portability failure with this: `python tools/run_tests/run_tests.py --use_docker -t -j 2 -l c++ -c dbg --iomgr_platform native --arch default --compiler cmake --build_only`

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by drigz** [comment]
I've bisected to find the gflags commit that breaks the build: gflags/gflags@21c7bcd895ac296e5395503b590bc74ceb0520a8. I don't have much experience with CMake, but it's not clear to me how that would cause this failure.

**Comment by drigz** [comment]
@randomguy3, you were working on gRPC (#11140) when you created https://github.com/gflags/gflags/commit/21c7bcd895ac296e5395503b590bc74ceb0520a8. I tried to update gflags in gRPC, but bringing in that change has broken the build. Do you have any idea why?

```
CMakeFiles/interop_test.dir/test/cpp/interop/interop_test.cc.o: In function `__static_initialization_and_destruction_0':
/var/local/git/grpc/test/cpp/interop/interop_test.cc:43: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
libgrpc++_test_config.a(test_config_cc.cc.o): In function `grpc::testing::InitTest(int*, char***, bool)':
/var/local/git/grpc/test/cpp/util/test_config_cc.cc:33: undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/interop_test.dir/build.make:146: recipe for target 'interop_test' failed
```

**Comment by randomguy3** [comment]
I would guess that https://github.com/gflags/gflags/commit/21c7bcd895ac296e5395503b590bc74ceb0520a8#diff-01de9067ac77e00c2f64922cadb78a1dR68 is the change that's caused/exposed this. `gflags_define` is used to set up configuration variables, and that change fixes some code that was supposed to give different default settings to variables depending on whether flags is being used in a subproject or not. However, before this commit was applied, grpc would get the "standalone" defaults, instead of the "subproject" defaults.

`git grep` suggests that the variables that are (supposed to be, and now are) different for subprojects are:

- `GFLAGS_NAMESPACE` (was `"google;${PACKAGE_NAME}"`, now `"${PACKAGE_NAME}"`)
- `GFLAGS_BUILD_STATIC_LIBS` (was `OFF`, now `ON`)
- `GFLAGS_BUILD_gflags_LIB` (was `ON`, now `OFF`)
- `GFLAGS_INSTALL_HEADERS` (was `ON`, now `OFF`)
- `GFLAGS_INSTALL_STATIC_LIBS` (was `ON`, now `OFF`)
- `GFLAGS_REGISTER_INSTALL_PREFIX` (was `ON`, now `OFF`)

I think gRPC was depending on the standalone value (eg: `GFLAGS_BUILD_gflags_LIB` being `ON`). The fix would be to override it in the gRPC `CMakeLists.txt`, and/or change the subproject default in gflags (the optional 5th argument to `gflags_define`)

**Comment by drigz** [comment]
@randomguy3 Thanks for the explanation! I would guess that gRPC wants the following settings:

```
GFLAGS_NAMESPACE = google;gflags
GFLAGS_BUILD_STATIC_LIBS true/false depending on if(TARGET gflags_static)
GFLAGS_BUILD_gflags_LIB ??? not sure
GFLAGS_INSTALL_HEADERS = OFF
GFLAGS_INSTALL_STATIC_LIBS = OFF
GFLAGS_REGISTER_INSTALL_PREFIX = OFF
```

And that these should be set in [cmake/gflags.cmake](https://github.com/grpc/grpc/blob/d5b1f9809202bf2338f94a9e1c07bc511b42d67d/cmake/gflags.cmake). Does that look good to you?

**Comment by randomguy3** [comment]
That looks reasonable, although the only thing I'm sure about is that the install settings should be OFF - I believe the install settings being wrong were why I found the bug in the first place.

**Comment by drigz** [comment]
I tried applying the following changes, but they haven't resolved the problem. I haven't been able to work out if this is because I'm applying the config incorrectly, or because this config change isn't actually the root cause.

```
diff --git a/cmake/gflags.cmake b/cmake/gflags.cmake
index f86a141c1d..9a4c0812ae 100644
--- a/cmake/gflags.cmake
+++ b/cmake/gflags.cmake
@@ -17,11 +17,15 @@ if("${gRPC_GFLAGS_PROVIDER}" STREQUAL "module")
     set(GFLAGS_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/third_party/gflags)
   endif()
   if(EXISTS "${GFLAGS_ROOT_DIR}/CMakeLists.txt")
-    add_subdirectory(${GFLAGS_ROOT_DIR} third_party/gflags)
+    set(GFLAGS_NAMESPACE "google;gflags")
     if(TARGET gflags_static)
+      set(GFLAGS_BUILD_STATIC_LIBS ON)
       set(_gRPC_GFLAGS_LIBRARIES gflags_static)
       set(_gRPC_GFLAGS_INCLUDE_DIR "${CMAKE_CURRENT_BINARY_DIR}/third_party/gflags/include")
     endif()
+    add_subdirectory(${GFLAGS_ROOT_DIR} third_party/gflags)
   else()
     message(WARNING "gRPC_GFLAGS_PROVIDER is \"module\" but GFLAGS_ROOT_DIR is wrong")
   endif()```
