### ISSUE TITLE
boringssl-with-bazel cannot compile shared lib

### ISSUE THREAD

**Issue by agudpp** [grpc/grpc#21733]
### What version of gRPC and what language are you using?
Latest master (commit https://github.com/grpc/grpc/commit/eba60d8dbe4099c34b8097b2c89998d4484740ac)

### What operating system (Linux, Windows,...) and version?
Linux ubuntu 16 / 18

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (any)

### What did you do?
try to compile with CMAKE using `-DBUILD_SHARED_LIBS=ON` will fail
even if you try to compile boring ssl with `-DBUILD_SHARED_LIBS=ON` will fail

### What did you expect to see?
to compile properly

### What did you see instead?
undefined references to ssl / crypto:
```bash
ciphers.cc:(.text+0xba): undefined reference to `TLS_method'
ciphers.cc:(.text+0xc2): undefined reference to `SSL_CTX_new'
ciphers.cc:(.text+0xfa): undefined reference to `SSL_CTX_set_strict_cipher_list'
ciphers.cc:(.text+0x130): undefined reference to `ERR_print_errors_fp'
ciphers.cc:(.text+0x14e): undefined reference to `SSL_CTX_get_ciphers'
ciphers.cc:(.text+0x197): undefined reference to `SSL_CTX_cipher_in_group'
ciphers.cc:(.text+0x1ff): undefined reference to `SSL_CIPHER_get_name'
ciphers.cc:(.text+0x20d): undefined reference to `SSL_CIPHER_standard_name'
CMakeFiles/bssl.dir/src/tool/ciphers.cc.o: In function `sk_SSL_CIPHER_num':
ciphers.cc:(.text.sk_SSL_CIPHER_num[sk_SSL_CIPHER_num]+0x14): undefined reference to `sk_num'
CMakeFiles/bssl.dir/src/tool/ciphers.cc.o: In function `sk_SSL_CIPHER_value':
ciphers.cc:(.text.sk_SSL_CIPHER_value[sk_SSL_CIPHER_value]+0x1f): undefined reference to `sk_value'
CMakeFiles/bssl.dir/src/tool/ciphers.cc.o: In function `bssl::internal::DeleterImpl<ssl_ctx_st, void>::Free(ssl_ctx_st*)':
ciphers.cc:(.text._ZN4bssl8internal11DeleterImplI10ssl_ctx_stvE4FreeEPS2_[_ZN4bssl8internal11DeleterImplI10ssl_ctx_stvE4FreeEPS2_]+0x14): undefined reference to `SSL_CTX_free'
CMakeFiles/bssl.dir/src/tool/client.cc.o: In function `LoadPrivateKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
client.cc:(.text+0x5b): undefined reference to `BIO_s_file'
client.cc:(.text+0x63): undefined reference to `BIO_new'
client.cc:(.text+0xae): undefined reference to `BIO_read_filename'
client.cc:(.text+0xf8): undefined reference to `PEM_read_bio_PrivateKey'
...
```

### Anything else we should know about your project / environment?
I tried in a VM and local machine, both fails the same, even if you pull the latest boringssl master-with-bazel branch it also fails to compile that library isolated.
I didn't have this issue before when compiling grpc on a previous version
Compiling statically works fine (but i need to use dynamic)

**Comment by jtattermusch** [comment]
This may have been caused by https://github.com/grpc/grpc/pull/21527

**Comment by agudpp** [comment]
@jtattermusch can be, I reported a issue to boringssl as well since the library itself doesn't compile properly for shared libs. Still, this can be fixed in grpc pointing to a previous version (that was compiling before)

**Comment by agudpp** [comment]
@jtattermusch they replied on the boringssl issue...

**Comment by agudpp** [comment]
@jtattermusch they already added the changes to be able to compile the shared the libraries, tested on the latest commit to compile boringssl (master-with-bazel -> https://github.com/google/boringssl/commit/3c4529d12a50f0266ba926eaa4967e492f43dab4) and works fine now with the `-DBUILD_SHARED_LIBS=ON` flag.
On `grpc` side, on the commit https://github.com/grpc/grpc/commit/eba60d8dbe4099c34b8097b2c89998d4484740ac (the one i was using before), and updating to the latest `master-with-bazel` on the boringssl side, seem that compiles properly now (for more information you can check the boringssl issue on the link above).

I would say should be fine to put ur changes in again and point the `boringssl` submodule to the latest commit of `master-with-bazel` branch.
