### PR TITLE
Fixes for older C++ compilers (remove lambdas, brace init, and nullptr ambiguity)

### LINKED ISSUE #2412: gRPC build failure with gcc 4.4 compiler [-stc=C++0x]
Trying to build the gRPC library on MIPS 64 machine with gcc 4.4 compiler, using "-std=C++0x" and it runs into build errors [see error logs below] although it builds fine on a linux box with "-std=c++11" with gcc 4.6

/1tb/image/kaushikgoa/Default/porfidio/tools/mipscross-xlp/linux/bin/mips64-nlm-linux-c++ -B/1tb/image/kaushikgoa/Default/porfidio/tools/mipscross-xlp/linux -B/1tb/image/kaushikgoa/Default/porfidio/tools/mipscross-xlp/linux/lib -D__EXPORTED_HEADERS__ -fdiagnostics-show-option -Wno-error=cast-align -mabi=32 -march=xlp -pipe -Wall -Werror -Wno-unused -fno-unit-at-a-time -Wno-strict-aliasing -ggdb -O2 -DGOOGLE_PROTOBUF_ARCH_MIPS -std=c++0x -O2 -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -fPIC -I. -Iinclude -I/1tb/image/kaushikgoa/Default/porfidio/cmn/grpc-release-0_10_0/gens -I/1tb/image/kaushikgoa/Default/porfidio/openssl-regular/openssl-1.0.2c/include -I/1tb/image/kaushikgoa/Default/porfidio/cmn/protobuf-3.0.0-alpha-3/src -I/1tb/image/kaushikgoa/Default/porfidio/tools/zlib-1.1.4 -DNDEBUG -DINSTALL_PREFIX="/usr/local" -MMD -MF /1tb/image/kaushikgoa/Default/porfidio/cmn/grpc-release-0_10_0/objs/opt/src/cpp/client/secure_credentials.dep -c -o /1tb/image/kaushikgoa/Default/porfidio/cmn/grpc-release-0_10_0/objs/opt/src/cpp/client/secure_credentials.o src/cpp/client/secure_credentials.cc
In file included from include/grpc++/channel_interface.h:40,
                 from ./src/cpp/client/channel.h:39,
                 from src/cpp/client/secure_credentials.cc:37:
include/grpc++/impl/call.h: In member function 'void grpc::CallOpGenericRecvMessage::RecvMessage(R*)':
include/grpc++/impl/call.h:181: error: expected primary-expression before '[' token
include/grpc++/impl/call.h:181: error: expected primary-expression before '*' token
include/grpc++/impl/call.h:181: error: 'buf' was not declared in this scope
include/grpc++/impl/call.h:182: error: expected primary-expression before 'int'
include/grpc++/impl/call.h:182: error: expected ';' before '{' token
make: *** [/1tb/image/kaushikgoa/Default/porfidio/cmn/grpc-release-0_10_0/objs/opt/src/cpp/client/secure_credentials.o] Error 1
make: Leaving directory `/1tb/image/kaushikgoa/Default/porfidio/cmn/grpc-release-0_10_0'
 
Source code for include/grpc++/impl/call.h
175 class CallOpGenericRecvMessage {
176  public:
177   CallOpGenericRecvMessage() : got_message(false) {}
178
179   template <class R>
180   void RecvMessage(R* message) {
181     deserialize_ = [message](grpc_byte_buffer* buf,
182                              int max_message_size) -> Status {
183       return SerializationTraits<R>::Deserialize(buf, message,
184                                                  max_message_size);
185     };
186   }
187
188   bool got_message;
189
190  protected:

*************
Issue is with L181 and 182 of include/grpc++/impl/call.h

### PR DESCRIPTION
**Pull request by vjpai**
Fixes #2412 .
Note that the qps family of tests will still not build, as these use numerous banned features (lambdas, local templates) . However, this should enable all of the other tests and C++ library to build in gcc 4.4 .

### CODE REVIEW

File: src/compiler/objective_c_generator.cc [hunk 1]
```diff
@@ -101,11 +101,13 @@ void PrintAdvancedSignature(Printer *printer,
 }
 
 inline map<string, string> GetMethodVars(const MethodDescriptor *method) {
```
Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: Should we make it return `map<string, string>&&`?

**Comment by jcanizales** [comment]
:+1:

File: include/grpc++/impl/call.h [hunk 2]
```diff
@@ -172,17 +172,31 @@ class CallOpRecvMessage {
...
 
-  template <class R>
-  void RecvMessage(R* message) {
-    deserialize_ = [message](grpc_byte_buffer* buf,
-                             int max_message_size) -> Status {
-      return SerializationTraits<R>::Deserialize(buf, message,
-                                                 max_message_size);
-    };
+  template <class R> void RecvMessage(R* message) {
+    deserialize_.reset(new CallOpGenericRecvMessageHelper::
```
Comment (yang-g) [inline include/grpc++/impl/call.h]: Would this allocation be a performance concern?

**Comment by yang-g** [comment]
Run clang-format?

File: include/grpc++/impl/call.h (hunk 2 above)
Comment (ctiller) [inline include/grpc++/impl/call.h]: It's exchanging one allocation for another, so no more concerning than what we had.

(Note that std::function<> will allocate something to hold the lambda, since lambda's can vary in size).

File: include/grpc++/impl/call.h [hunk 3]
```diff
@@ -172,17 +172,31 @@ class CallOpRecvMessage {
   grpc_byte_buffer* recv_buf_;
 };
 
+namespace CallOpGenericRecvMessageHelper {
+class DeserializeFunc {
+ public:
+  virtual Status deser(grpc_byte_buffer* buf,int max_message_size) = 0;
```
Comment (ctiller) [inline include/grpc++/impl/call.h]: s/deser/Deserialize

File: include/grpc++/impl/call.h [hunk 4]
```diff
@@ -172,17 +172,31 @@ class CallOpRecvMessage {
...
+ public:
+  DeserializeFuncType(R *message): message_(message) {}
+  Status deser(grpc_byte_buffer* buf,int max_message_size) {
+    return SerializationTraits<R>::Deserialize(buf, message_,
+					       max_message_size);
+  }
+ private:
+  R *message_; // Not a managed pointer because management is external to this
+};
+}; // namespace CallOpGenericRecvMessageHelper
```
Comment (yang-g) [inline include/grpc++/impl/call.h]: Remove the ";"

File: include/grpc++/impl/call.h (hunk 2 above)
Comment (vjpai) [inline include/grpc++/impl/call.h]: That was my assumption also, which is why I thought that it was ok to do it. I can revisit if indeed this is a problem.

File: include/grpc++/impl/call.h (hunk 4 above)
Comment (vjpai) [inline include/grpc++/impl/call.h]: coming.

File: include/grpc++/impl/call.h (hunk 3 above)
Comment (vjpai) [inline include/grpc++/impl/call.h]: ok.

File: src/compiler/objective_c_generator.cc (hunk 1 above)
Comment (vjpai) [inline src/compiler/objective_c_generator.cc]: I reverted to the original after Craig's comment, but please let me know if you feel strongly about it.

Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: Nope, I was just wondering :)

**Comment by yang-g** [comment]
LGTM

**Comment by vjpai** [comment]
It's super-green, but I forgot some important syntactic sugar.

**Comment by vjpai** [comment]
Green enough?
