### ISSUE TITLE
Building C++ 1.49.1 does not create grpc++*.lib files

### ISSUE THREAD

**Issue by StefanoBettega** [grpc/grpc#31181]
### What version of gRPC and what language are you using?
I'm using 1.49.1, C++

### What operating system (Linux, Windows,...) and version?
Windows 10 21H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019 with 2015 toolchain

### What did you do?
From VS2019 developer command prompt
cmake .. -G "Visual Studio 14 2015 Win64"
cmake --build . --config Debug

### What did you expect to see?
grpc++.lib and additional files created in the correct directory

### What did you see instead?
only four .lib files produced, and a lot of error on the output like:

```
C:\grpc\src\core\lib\channel\promise_based_filter.cc(1137): error C2440: 'return': cannot convert from 'grpc_core::MetadataHandle<grpc_core::ServerMetadata>' to 'absl::lts_20220623::variant<grpc_core::Pending,T>' [C:\grpc\.build\grpc.vcxproj]
```
or
```
C:\grpc\third_party\abseil-cpp\absl/functional/internal/any_invocable.h(230): error C2210: 'T' : pack expansions cannot be used as arguments to non-packed parameters in alias templates [C:\grpc\.build\grpc.vcxproj]
```
### Anything else we should know about your project / environment?
If I build in the same way the 1.49.0 version, it successfully build with no errors.

**Comment by StefanoBettega** [comment]
I think the problem is related to Visual Studio required version.
We are still using VS 2015 toolchain for our project, while library requires at least VS 2017 as compiler.
So this is mostly a our issue.
Thanks for your support.
