### ISSUE TITLE
Unable to compile application with GRPC support with GRPC 1.51.1

### ISSUE THREAD

**Issue by leragequit** [grpc/grpc#32746]
### What version of gRPC and what language are you using?
1.51.1

### What operating system (Linux, Windows,...) and version?
 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Debian 10.2.1-6) 10.2.1 20210110

### What did you do?

tried to compile a program i wrote that inludes grpc 

### What did you expect to see?

no error message an see the compile go through

### What did you see instead?

`In file included from /home/pi/.local/include/grpcpp/generic/async_generic_service.h:22,
                 from /home/pi/dev/libneon/cmake/build/neonapi.grpc.pb.h:10,
                 from /home/pi/dev/libneon/SubscriptionHandler.h:10:
/home/pi/.local/include/grpc/impl/codegen/log.h:62:46: error: expected primary-expression before ‘,’ token
   62 |                     const char* format, ...) GPR_PRINT_FORMAT_CHECK(4, 5);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~
/home/pi/.local/include/grpc/impl/codegen/log.h:62:46: error: unrecognized format specifier
   62 |                     const char* format, ...) GPR_PRINT_FORMAT_CHECK(4, 5);
`

### Anything else we should know about your project / environment?

editing include/grpc/impl/codegen/log.h:62:46:

from this
![image](https://user-images.githubusercontent.com/4532267/228531238-2721b01d-5c37-4795-bf33-fe0d22ae4870.png)

to this 
![image](https://user-images.githubusercontent.com/4532267/228531354-e203c557-1a7c-466a-9a92-34565156cd86.png)

fixes the issue and all GRPC versions starting at 1.52.0 have changed how logging works so the bug is no longer present.
all versions 1.51.x exhibit the bug

**Comment by drfloob** [comment]
> all GRPC versions starting at 1.52.0 have changed how logging works so the bug is no longer present.

The printf format check has been around for years, and I'm not familiar with any logging changes. Please share a link to the commit in 1.52 that you're talking about.

A few basic questions:
 * Does gRPC build on its own on your platform, separate from your application? Let's eliminate any issues with gRPC builds themselves.
  * Are you calling `gpr_log` in your code? If so, does your code build without those lines?
