### ISSUE TITLE
Ruby segfault at 1.74.0

### ISSUE THREAD

**Issue by ka2n** [grpc/grpc#40368]
### What version of gRPC and what language are you using?

grpc-ruby 1.74.0

### What operating system (Linux, Windows,...) and version?

Linux (running on Google Cloud Run with ruby:3.4.4-slim-bookworm base image)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby 3.4.4

### What did you do?

Executed Google Cloud Tasks client task creation operation using the `google-cloud-tasks` gem (version 3.0.2) in a Ruby application running on Google Cloud Run.

### What did you expect to see?

Normal communication with Google Cloud API and successful task creation.

### What did you see instead?

Application crashes with a segmentation fault. The crash occurs almost always but not 100% of the time.

**Stack trace:**
```
[BUG] Segmentation fault at 0x0000000000000001
ruby 3.4.4 (2025-05-14 revision a38531fd3f) +YJIT +PRISM [x86_64-linux]
-- Control frame information -----------------------------------------------
c:0001 p:---- s:0003 e:000002 DUMMY  [FINISH]
-- Threading information ---------------------------------------------------
Total ractor count: 1
Ruby thread count for this ractor: 22
-- Machine register context ------------------------------------------------
 RIP: 0x00003e04016cb7b3 RBP: 0x0000000000000000 RSP: 0x00003e03d91fe698
 RAX: 0x0000000000000d21 RBX: 0x00003e03e5b82168 RCX: 0x00003e03d91fe7f0
 RDX: 0x00003e03d91fe6c0 RDI: 0x0000000000000001 RSI: 0x0000000000000d21
  R8: 0x0000000000000000  R9: 0x00003e03d91fe6c0 R10: 0x0000000000000000
 R11: 0x0000000000000246 R12: 0x00003e03e5b82168 R13: 0x00003e03e5b82168
 R14: 0x0000000000000d21 R15: 0x00003e03d91fe6c0 EFL: 0x0000000000010202
-- C level backtrace information -------------------------------------------
/usr/local/lib/libruby.so.3.4(rb_print_backtrace+0x8) [0x3e040174725a] /usr/src/ruby/vm_dump.c:823
/usr/local/lib/libruby.so.3.4(rb_vm_bugreport) /usr/src/ruby/vm_dump.c:1155
/usr/local/lib/libruby.so.3.4(rb_bug_for_fatal_signal+0x100) [0x3e040152d680] /usr/src/ruby/error.c:1130
/usr/local/lib/libruby.so.3.4(sigsegv+0x42) [0x3e040168a4c2] /usr/src/ruby/signal.c:933
/lib/x86_64-linux-gnu/libc.so.6(0x3e040109f050) [0x3e040109f050]
/usr/local/lib/libruby.so.3.4(hash_table_index+0x0) [0x3e04016cb7b3] /usr/src/ruby/symbol.h:72
/usr/local/lib/libruby.so.3.4(rb_id_table_lookup) /usr/src/ruby/id_table.c:230
/usr/local/lib/libruby.so.3.4(lookup_method_table+0xf) [0x3e040171a7fb] /usr/src/ruby/vm_method.c:910
/usr/local/lib/libruby.so.3.4(search_method0) /usr/src/ruby/vm_method.c:1324
/usr/local/lib/libruby.so.3.4(search_method) /usr/src/ruby/vm_method.c:1343
/usr/local/lib/libruby.so.3.4(callable_method_entry_or_negative) /usr/src/ruby/vm_method.c:1504
/usr/local/lib/libruby.so.3.4(callable_method_entry+0xd) [0x3e040171b1cf] /usr/src/ruby/vm_method.c:1534
/usr/local/lib/libruby.so.3.4(rb_callable_method_entry) /usr/src/ruby/vm_method.c:1541
/usr/local/lib/libruby.so.3.4(vm_search_cc) /usr/src/ruby/vm_insnhelper.c:2140
/usr/local/lib/libruby.so.3.4(rb_vm_search_method_slowpath) /usr/src/ruby/vm_insnhelper.c:2189
/usr/local/lib/libruby.so.3.4(vm_search_method_slowpath0+0x5) [0x3e040171b509] /usr/src/ruby/vm_insnhelper.c:2210
/usr/local/lib/libruby.so.3.4(gccct_method_search_slowpath) /usr/src/ruby/vm_eval.c:418
/usr/local/lib/libruby.so.3.4(gccct_method_search+0x6f) [0x3e040173915f] /usr/src/ruby/vm_eval.c:483
/usr/local/lib/libruby.so.3.4(rb_funcallv_scope) /usr/src/ruby/vm_eval.c:1041
/usr/local/lib/libruby.so.3.4(rb_funcallv) /usr/src/ruby/vm_eval.c:1062
/app/vendor/bundle/ruby/3.4.0/gems/grpc-1.74.0-x86_64-linux-gnu/src/ruby/lib/grpc/3.4/grpc_c.so(0x3e03e291e513) [0x3e03e291e513]
/usr/local/lib/libruby.so.3.4(rb_vrescue2+0x10b) [0x3e0401538e7b] /usr/src/ruby/eval.c:990
/usr/local/lib/libruby.so.3.4(rb_rescue2+0x8a) [0x3e04015390ea] /usr/src/ruby/eval.c:971
/app/vendor/bundle/ruby/3.4.0/gems/grpc-1.74.0-x86_64-linux-gnu/src/ruby/lib/grpc/3.4/grpc_c.so(0x3e03e291e1b1) [0x3e03e291e1b1]
/app/vendor/bundle/ruby/3.4.0/gems/grpc-1.74.0-x86_64-linux-gnu/src/ruby/lib/grpc/3.4/grpc_c.so(0x3e03e2920f41) [0x3e03e2920f41]
/usr/local/lib/libruby.so.3.4(thread_do_start+0x78) [0x3e04016d966f] /usr/src/ruby/thread.c:636
/usr/local/lib/libruby.so.3.4(thread_start_func_2) /usr/src/ruby/thread.c:682
/usr/local/lib/libruby.so.3.4(nt_start+0x12b) [0x3e04016da68b] /usr/src/ruby/thread_pthread.c:2176
/lib/x86_64-linux-gnu/libc.so.6(0x3e04010ec1f5) [0x3e04010ec1f5]
/lib/x86_64-linux-gnu/libc.so.6(0x3e040116c89c) [0x3e040116c89c]
```

The segmentation fault appears to occur within the grpc_c.so native extension, specifically during method lookup operations.

### Anything else we should know about your project / environment?

- Running on Google Cloud Run with ruby:3.4.4-slim-bookworm base image
- Using google-cloud-tasks gem version 3.0.2
- The crash occurs almost always but not 100% of the time (intermittent issue)
- Ruby thread count shows 22 threads at crash time
- The fault occurs at memory address 0x0000000000000001, suggesting a null pointer dereference
- Stack trace indicates the crash happens during Ruby method resolution within the gRPC C extension

**Comment by ivgiuliani** [comment]
We have been observing the same problem, with grpc frequently segfaulting following an update from 1.73 to 1.74. In our case, we've been experiencing the problem by using the pubsub library but I suspect this is more widespread than that.

Recompiling grpc with debug symbols we have managed to get a full stack trace (this is against ruby 3.3, but we've seen the same exact problem with 3.4):

```
Thread 1 (Thread 0x7a8bd001f640 (LWP 359)):
#0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=134740908832320) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=11, threadid=134740908832320) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=134740908832320, signo=signo@entry=11) at ./nptl/pthread_kill.c:89
#3  0x00007a8c19db9476 in __GI_raise (sig=sig@entry=11) at ../sysdeps/posix/raise.c:26
#4  0x00007a8c1a6b26b5 in ruby_default_signal (sig=sig@entry=11) at signal.c:422
#5  0x00007a8c1a49260b in rb_bug_for_fatal_signal (default_sighandler=0x0, sig=sig@entry=11, ctx=ctx@entry=0x7a8bdc2212c0, fmt=fmt@entry=0x7a8c1a8c848b "Segmentation fault at %p") at error.c:1069
#6  0x00007a8c1a6b188d in sigsegv (sig=11, info=0x7a8bdc2213f0, ctx=0x7a8bdc2212c0) at signal.c:926
#7  <signal handler called>
#8  0x00007a8c1a6f2137 in hash_table_index (key=208, tbl=<optimized out>) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/id_table.c:136
#9  rb_id_table_lookup (tbl=<optimized out>, id=id@entry=3329, valp=valp@entry=0x7a8bd001ce60) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/id_table.c:230
#10 0x00007a8c1a73da4b in lookup_method_table (id=3329, klass=<optimized out>) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_method.c:898
#11 search_method0 (skip_refined=<optimized out>, defined_class_ptr=<optimized out>, id=<optimized out>, klass=<optimized out>) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_method.c:1307
#12 search_method (defined_class_ptr=<optimized out>, id=<optimized out>, klass=<optimized out>) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_method.c:1326
#13 callable_method_entry_or_negative (klass=134741298408016, mid=3329, defined_class_ptr=0x0) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_method.c:1487
#14 0x00007a8c1a73ddde in callable_method_entry (defined_class_ptr=0x0, mid=3329, klass=<optimized out>) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_method.c:1517
#15 rb_callable_method_entry (mid=3329, klass=<optimized out>) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_method.c:1524
#16 gccct_method_search_slowpath (vm=0x7a8c19659000, klass=134741298408016, mid=mid@entry=3329, argc=argc@entry=0, index=830) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_eval.c:456
#17 0x00007a8c1a75a76b in gccct_method_search (argc=0, mid=3329, recv=134740908933800, ec=0x7a8bdb854550) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_eval.c:505
#18 rb_funcallv_scope (scope=CALL_FCALL, argv=0x0, argc=0, mid=3329, recv=134740908933800) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_eval.c:1063
#19 rb_funcallv (recv=recv@entry=134740908933800, mid=3329, argc=argc@entry=0, argv=argv@entry=0x0) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/vm_eval.c:1084
#20 0x00007a8bf4445538 in grpc_rb_call_credentials_callback (args=args@entry=134740844262480) at /rbenv/versions/3.3.4/include/ruby-3.3.0/ruby/internal/symbol.h:296
#21 0x00007a8c1a56659e in rb_vrescue2 (b_proc=0x7a8bf44454a0 <grpc_rb_call_credentials_callback>, data1=134740844262480, r_proc=0x7a8bf4445290 <grpc_rb_call_credentials_callback_rescue>, data2=4, args=args@entry=0x7a8bd001d1c0) at eval.c:919
#22 0x00007a8c1a56682e in rb_rescue2 (b_proc=b_proc@entry=0x7a8bf44454a0 <grpc_rb_call_credentials_callback>, data1=data1@entry=134740844262480, r_proc=r_proc@entry=0x7a8bf4445290 <grpc_rb_call_credentials_callback_rescue>, data2=data2@entry=4) at eval.c:900
#23 0x00007a8c1a566868 in rb_rescue (b_proc=b_proc@entry=0x7a8bf44454a0 <grpc_rb_call_credentials_callback>, data1=data1@entry=134740844262480, r_proc=r_proc@entry=0x7a8bf4445290 <grpc_rb_call_credentials_callback_rescue>, data2=data2@entry=4) at eval.c:969
#24 0x00007a8bf44451bd in grpc_rb_call_credentials_callback_with_gil (param=0x7a8bbf415b00) at rb_call_credentials.c:154
#25 0x00007a8bf4448016 in grpc_rb_event_thread (arg=<optimized out>) at rb_event_thread.c:134
#26 0x00007a8c1a6ffdae in thread_do_start (th=0x7a8bdc1c9000) at thread.c:624
#27 thread_start_func_2 (th=0x7a8bdc1c9000, stack_start=<optimized out>) at thread.c:672
#28 0x00007a8c1a700cfd in call_thread_start_func_2 (th=0x7a8bdc1c9000) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/thread_pthread.c:2186
#29 nt_start (ptr=0x7a8bdc1dba00) at /tmp/ruby-build.20250721132246.774.RH1Q9R/ruby-3.3.4/thread_pthread.c:2231
#30 0x00007a8c19e0bac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#31 0x00007a8c19e9d850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

We also noticed some odd errors in our logs that only appear with 1.74, and usually just before the app crashes which I have a feeling are related:

```
#<Thread:0x00007ded6a194620 run> terminated with exception (report_on_exception is true):
method 'to_s' called on unexpected T_IMEMO object (0x00007ded6a1946c0 flags=0x501a) (NotImplementedError)
```

and

```
GRPC::Unavailable: 14:Getting metadata from plugin failed with error: #<NoMethodError: undefined method `source_location' for an instance of Array>. debug_error_string:{UNKNOWN:Error received from peer  {grpc_message:"Getting metadata from plugin failed with error: #<NoMethodError: undefined method `source_location\' for an instance of Array>", grpc_status:14}} (GRPC::Unavailable)
```

I have not been able to reproduce this locally using `:this_channel_is_insecure` yet, but usually only takes a few minutes in running a basic pubsub consumer in a non-dev environment with proper authentication to trigger the sigsegv.

I'd take this with a pinch of salt as I'm not familiar with the grpc codebase, but pointing an LLM at the stacktrace and the changes in 1.74.0 it refers to https://github.com/grpc/grpc/commit/69f229edd1 as a problematic change due to removing `grpc_rb_channel_mark` which was preventing objects from being GC'ed and that would explain a good chunk of what we're seeing above.

**Comment by ivgiuliani** [comment]
I have finally managed to reproduce this locally and have a repro script on https://github.com/ivgiuliani/grpc-40368, which works on 1.73 but segfaults on 1.74. I'm on OSX at the moment but looks like the same stacktrace:

```
$ bundle exec ruby ./grpc_client.rb
[client] versions grpc=1.74.0 ruby=3.4.1
Progress: 0 requests
Progress: 100 requests
Progress: 200 requests
Progress: 300 requests
Progress: 400 requests
Progress: 500 requests
Progress: 600 requests
Progress: 700 requests
[BUG] Segmentation fault at 0x0000000000000009
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
                                                                                                                                      
-- Crash Report log information --------------------------------------------
   See Crash Report log file in one of the following locations:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.
                                                                                                                                      
-- Control frame information -----------------------------------------------
c:0001 p:---- s:0003 e:000002 DUMMY  [FINISH]
                                                                                                                                      
                                                                                                                                      
-- Threading information ---------------------------------------------------
Total ractor count: 1
Ruby thread count for this ractor: 2
                                                                                                                                      
-- Machine register context ------------------------------------------------
  x0: 0x0000000000000009  x1: 0x0000000000000d21  x2: 0x000000016d17e8e0
  x3: 0x000000016d17e978  x4: 0x0000000000000001  x5: 0x0000000000000000
  x6: 0x0000000000000001  x7: 0x00000000000000a0 x18: 0x0000000000000000
 x19: 0x00000001069bc4c0 x20: 0x000000016d17e978 x21: 0x0000000000000000
 x22: 0x000000010303afa8 x23: 0x0000000000000d21 x24: 0x0000000000000009
 x25: 0x0000000103f06000 x26: 0x0000000120009000 x27: 0x000000000001b01a
 x28: 0x0000000000000000  lr: 0x0000000103c3e12c  fp: 0x000000016d17e930
  sp: 0x000000016d17e8d0
                                                                                                                                      
-- C level backtrace information -------------------------------------------
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_vm_bugreport+0xb6c) [0x103c6e26c]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_bug_for_fatal_signal+0x100) [0x103aa57e8]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(sigsegv+0x84) [0x103bce738]
/usr/lib/system/libsystem_platform.dylib(_sigtramp+0x38) [0x187a996a4]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_vm_search_method_slowpath+0x60) [0x103c3e12c]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(gccct_method_search_slowpath+0x24) [0x103c59714]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_funcallv_scope+0x17c) [0x103c4f514]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_funcall+0x88) [0x103c4f984]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/grpc-1.74.0-arm64-darwin/src/ruby/lib/grpc/3.4/grpc_c.bundle(0x1116db1f0) [0x1116db1f0]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_vrescue2+0xd8) [0x103ab136c]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_rescue2+0x2c) [0x103ab126c]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(rb_rescue+0x20) [0x103ab14e8]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/grpc-1.74.0-arm64-darwin/src/ruby/lib/grpc/3.4/grpc_c.bundle(0x1116db08c) [0x1116db08c]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/grpc-1.74.0-arm64-darwin/src/ruby/lib/grpc/3.4/grpc_c.bundle(0x1116dde54) [0x1116dde54]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(thread_start_func_2+0x358) [0x103c140ec]
/Users/[REDACTED]/.rbenv/versions/3.4.1/lib/libruby.3.4.dylib(nt_start+0xf8) [0x103c13c2c]
/usr/lib/system/libsystem_pthread.dylib(_pthread_start+0x88) [0x187a5fc0c]

```

**Comment by dazuma** [comment]
We've been seeing this in the Google client libraries integration tests as well.

**Comment by rwstauner** [comment]
grpc 1.74.1 was released which contains a fix for this.

**Comment by paracycle** [comment]
@ivgiuliani The repro you supplied has been super helpful and allowed us to identify the fix for the crash. I would like to note that we've been observing the same crash for a long while at Shopify but at a much much lower rate. Until 1.74.0 somehow made it more frequent and until your small repro, we didn't have a clue as to which object wasn't being marked.

Your repro really helped, so thank you very much! 🙏

**Comment by rwstauner** [comment]
@ivgiuliani Thank you for the repro, that was very helpful!
