### ISSUE TITLE
Parallel cmake builds may fail with .../reflection.pb.h: No such file or directory

### ISSUE THREAD

**Issue by tudor** [grpc/grpc#12379]
(See diagnosis below)

Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?

Yes.
 
### What version of gRPC and what language are you using?
 
gRPC 1.6.0, C++
 
### What operating system (Linux, Windows, …) and version?
 
Ubuntu 16.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 5.4.0

### What did you do?

Tried to build grpc with cmake, then do a parallel build (`make -j 16`)
 
### What did you expect to see?
 
I expected the build to succeed.
 
### What did you see instead?

``` 
/tmp/grpc/gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc:5:61: fatal error: src/proto/grpc/reflection/v1alpha/reflection.pb.h: No such file or directory
compilation terminated.
```

This happens because the `.proto` files are compiled with the `protobuf_generate_grpc_cpp` CMake function, which uses `add_custom_command` specifying the generated `.pb.h`, `.pb.cc`, `.grpc.pb.h`, and `grpc.pb.cc` files as `OUTPUT`.

The `*.pb.h` and `*.pb.cc` files are then compiled separately in more than one `add_library` target.

This is explicitly forbidden for `add_custom_command`, however. See https://cmake.org/cmake/help/v3.0/command/add_custom_command.html: "Do not list the output in more than one independent target that may build in parallel or the two instances of the rule may conflict (instead use add_custom_target to drive the command and make the other targets depend on that one)."

`add_custom_command` does not create a separate target; it ensures that the command is run every time the `OUTPUT`ed files are required, so, if they're required from more than one target, the `.proto` files are built more than once. If these builds happen in parallel, they clobber each other.

**Comment by jtattermusch** [comment]
@tudor  any ideas how to fix this?

**Comment by jtattermusch** [comment]
I believe this is still an issue.

**Comment by jtattermusch** [comment]
@zackgalbreath it seems that this item requires a lot of cmake expertise - any suggestions what would be the right way of generating from .proto files (without misusing add_custom_command as mentioned above)?
The right way of generating .cc from .proto files is important, because the grpc c++ users will also need to generate code from .proto files, so we should be providing a good example how to do that with cmake correctly.

**Comment by KyleFromKitware** [comment]
As an alternative, would it be possible to only compile the `.cc` files once in a static library (or even an object library) and then link to them from targets that need them?

**Comment by zackgalbreath** [comment]
@tudor posted a good quote from the CMake documentation on what the issue here is and the right way to fix it:

> Do not list the output (from add_custom_command) in more than one independent target that may build in parallel or the two instances of the rule may conflict (instead use add_custom_target to drive the command and make the other targets depend on that one)

Kyle's idea of compiling these files into a single static / object library is also a good one. This would save us a little bit of build time because these object files would only have to be built once each, instead of having to build them separately for each library that needs them.

If it turns out that isn't feasible for some reasson, the "right way" to do what you're trying to do is to use a [custom target](https://cmake.org/cmake/help/latest/command/add_custom_target.html). This custom target would depend on the generated source files, and the libraries that actually need these source files would then depend on the custom target.

Somewhat related, why do you define your own `protobuf_generate_grpc_cpp()` CMake function, rather than using the `protobuf_generate_cpp()` function that's provided in FindProtobuf.cmake?

**Comment by KyleFromKitware** [comment]
So far, I have not been able to reproduce the parallel build issue with either Make or Ninja. However, I am going to implement the object library fix anyway, as it seems like the right thing to do. Perhaps someone else who has been able to reproduce this issue can verify that the object library will fix it.

**Comment by tudor** [comment]
The object library fix seems right to me. Thanks for doing this!

**Comment by jtattermusch** [comment]
> @tudor posted a good quote from the CMake documentation on what the issue here is and the right way to fix it:
> 
> > Do not list the output (from add_custom_command) in more than one independent target that may build in parallel or the two instances of the rule may conflict (instead use add_custom_target to drive the command and make the other targets depend on that one)
> 
> Kyle's idea of compiling these files into a single static / object library is also a good one. This would save us a little bit of build time because these object files would only have to be built once each, instead of having to build them separately for each library that needs them.
> 
> If it turns out that isn't feasible for some reasson, the "right way" to do what you're trying to do is to use a [custom target](https://cmake.org/cmake/help/latest/command/add_custom_target.html). This custom target would depend on the generated source files, and the libraries that actually need these source files would then depend on the custom target.
> 
> Somewhat related, why do you define your own `protobuf_generate_grpc_cpp()` CMake function, rather than using the `protobuf_generate_cpp()` function that's provided in FindProtobuf.cmake?

I'm not 100% sure but it could be for one of these reasons:
- historic reasons and we never revisited this
- unlike protobuf which only generates the protobuf messages C++ code (`.pb.h`, `.ph.cc`, gRPC also generates its own stubs via protoc plugins `.grpc.h`  and `grpc.cc`, which is something that protobuf doesn't support of of the box - mostly because protobuf doesn't know anything about gRPC).
