### ISSUE TITLE
Python artifact build broken on upstream/master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11038]
Possibly caused by #10427?

https://grpc-testing.appspot.com/view/All/job/jtattermusch_build_artifacts_linux/6/testReport/(root)/build_artifacts/build_artifact_python_linux_x64_cp27_cp27m/

maybe we just need to switch the build to C99.
```
src/core/lib/support/env_linux.c: In function gpr_getenv:
src/core/lib/support/env_linux.c:63:3: error: for loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; getenv_func == NULL && i < GPR_ARRAY_SIZE(names); i++) {
   ^
src/core/lib/support/env_linux.c:63:3: note: use option -std=c99 or -std=gnu99 to compile your code
```

**Comment by jtattermusch** [comment]
Adding -std=c99 to here https://github.com/grpc/grpc/pull/10427/files#diff-2eeaed663bd0d25b7e608891384b7298R119 results in:
```
src/core/lib/support/time_posix.c:50:24: error: return type is an incomplete type
 static struct timespec timespec_from_gpr(gpr_timespec gts) {
                        ^
src/core/lib/support/time_posix.c: In function ‘timespec_from_gpr’:
src/core/lib/support/time_posix.c:51:19: error: storage size of ‘rv’ isn’t known
   struct timespec rv;
                   ^
src/core/lib/support/time_posix.c:58:3: warning: ‘return’ with a value, in function returning void [enabled by default]
   return rv;
   ^
src/core/lib/support/time_posix.c:51:19: warning: unused variable ‘rv’ [-Wunused-variable]
   struct timespec rv;
                   ^
```

**Comment by jtattermusch** [comment]
On mac:
```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 308, in <module>
    cmdclass=COMMAND_CLASS,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/Cython/Distutils/build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/private/var/folders/g4/3ppgfd8x4274zrnf_tf60_8h0000gn/T/pygrpc.4hhz0R/src/python/grpcio/commands.py", line 289, in build_extensions
    sys.stderr.write(make_err + '\n')
TypeError: can't concat bytes to str
+ rm -rf /var/folders/g4/3ppgfd8x4274zrnf_tf60_8h0000gn/T//pygrpc.4hhz0R
```
