### ISSUE TITLE
PHP distribtest  php_linux_x64_jessie broken (on Kokoro)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14761]
https://sponge.corp.google.com/target?id=9251c3a1-83ac-4e7e-ab80-0c3a5a0ede10&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

Most likely broken on Jenkins as well.

```
libtool: compile:  cc -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserjS50Xp/grpc-1.11.0dev/include -I/tmp/pear/temp/pear-build-defaultuserjS50Xp/grpc-1.11.0dev/main -I/tmp/pear/temp/grpc -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/boringssl/include -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -c /tmp/pear/temp/grpc/src/core/tsi/alts/handshaker/handshaker.pb.c  -fPIC -DPIC -o src/core/tsi/alts/handshaker/.libs/handshaker.o
/tmp/pear/temp/grpc/src/core/tsi/alts/handshaker/handshaker.pb.c:68:5: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
     PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, grpc_gcp_HandshakerReq, server_start, client_start, &grpc_gcp_StartServerHandshakeReq_fields),
     ^
In file included from /tmp/pear/temp/grpc/src/core/tsi/alts/handshaker/handshaker.pb.h:6:0,
                 from /tmp/pear/temp/grpc/src/core/tsi/alts/handshaker/handshaker.pb.c:4:
/tmp/pear/temp/grpc/third_party/nanopb/pb.h:123:51: error: size of array 'pb_static_assertion_YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_grpc_gcp_Endpoint_grpc_gcp_Identity_grpc_gcp_StartClientHandshakeReq_grpc_gcp_ServerHandshakeParameters_grpc_gcp_StartServerHandshakeReq_grpc_gcp_StartServerHandshakeReq_HandshakeParametersEntry_grpc_gcp_NextHandshakeMessageReq_grpc_gcp_HandshakerReq_grpc_gcp_HandshakerResult_grpc_gcp_HandshakerStatus_grpc_gcp_HandshakerResp1193' is negative
 #define PB_STATIC_ASSERT_MSG_(MSG, LINE, COUNTER) pb_static_assertion_##MSG##LINE##COUNTER
                                                   ^
/tmp/pear/temp/grpc/third_party/nanopb/pb.h:122:50: note: in expansion of macro 'PB_STATIC_ASSERT_MSG_'
 #define PB_STATIC_ASSERT_MSG(MSG, LINE, COUNTER) PB_STATIC_ASSERT_MSG_(MSG, LINE, COUNTER)
                                                  ^
/tmp/pear/temp/grpc/third_party/nanopb/pb.h:121:49: note: in expansion of macro 'PB_STATIC_ASSERT_MSG'
 #define PB_STATIC_ASSERT(COND,MSG) typedef char PB_STATIC_ASSERT_MSG(MSG, __LINE__, __COUNTER__)[(COND)?1:-1];
                                                 ^
/tmp/pear/temp/grpc/src/core/tsi/alts/handshaker/handshaker.pb.c:119:1: note: in expansion of macro 'PB_STATIC_ASSERT'
 PB_STATIC_ASSERT((pb_membersize(grpc_gcp_StartClientHandshakeReq, target_identities) < 256 && pb_membersize(grpc_gcp_StartClientHandshakeReq, local_identity) < 256 && pb_membersize(grpc_gcp_StartClientHandshakeReq, local_endpoint) < 256 && pb_membersize(grpc_gcp_StartClientHandshakeReq, remote_endpoint) < 256 && pb_membersize(grpc_gcp_StartClientHandshakeReq, rpc_versions) < 256 && pb_membersize(grpc_gcp_ServerHandshakeParameters, local_identities) < 256 && pb_membersize(grpc_gcp_StartServerHandshakeReq, handshake_parameters[0]) < 256 && pb_membersize(grpc_gcp_StartServerHandshakeReq, local_endpoint) < 256 && pb_membersize(grpc_gcp_StartServerHandshakeReq, remote_endpoint) < 256 && pb_membersize(grpc_gcp_StartServerHandshakeReq, rpc_versions) < 256 && pb_membersize(grpc_gcp_StartServerHandshakeReq_HandshakeParametersEntry, value) < 256 && pb_membersize(grpc_gcp_HandshakerReq, client_start) < 256 && pb_membersize(grpc_gcp_HandshakerReq, server_start) < 256 && pb_membersize(grpc_gcp_HandshakerReq, next) < 256
 && pb_membersize(grpc_gcp_HandshakerResult, peer_identity) < 256 && pb_membersize(grpc_gcp_HandshakerResult, local_identity) < 256 && pb_membersize(grpc_gcp_HandshakerResult, peer_rpc_versions) < 256 && pb_membersize(grpc_gcp_HandshakerResp, result) < 256 && pb_membersize(grpc_gcp_HandshakerResp, status) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_grpc_gcp_Endpoint_grpc_gcp_Identity_grpc_gcp_StartClientHandshakeReq_grpc_gcp_ServerHandshakeParameters_grpc_gcp_StartServerHandshakeReq_grpc_gcp_StartServerHandshakeReq_HandshakeParametersEntry_grpc_gcp_NextHandshakeMessageReq_grpc_gcp_HandshakerReq_grpc_gcp_HandshakerResult_grpc_gcp_HandshakerStatus_grpc_gcp_HandshakerResp)
 ^
cc1: error: unrecognized command line option "-Wno-parentheses-equality" [-Werror]
cc1: all warnings being treated as errors
Makefile:738: recipe for target 'src/core/tsi/alts/handshaker/handshaker.lo' failed
make: *** [src/core/tsi/alts/handshaker/handshaker.lo] Error 1
ERROR: `make' failed
+ FAILED=true
+ '[' '' '!=' '' ']'
+ docker rm -f build_and_run_docker_6d7daab0-c26a-4cef-8ecb-dfc38cdc818d
build_and_run_docker_6d7daab0-c26a-4cef-8ecb-dfc38cdc818d
+ '[' true '!=' '' ']'
+ exit 1
```

**Comment by jtattermusch** [comment]
The original issue has been fixed by #14807.

Now there is a new breakage, that has probably been introduced by https://github.com/grpc/grpc/pull/13290

https://sponge.corp.google.com/target?id=6595407e-b94b-4f10-9fac-39d8604564c2&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS
```
In file included from /tmp/pear/temp/grpc/third_party/address_sorting/address_sorting.c:41:0:
/tmp/pear/temp/grpc/third_party/address_sorting/address_sorting_internal.h:65:45: fatal error: address_sorting/address_sorting.h: No such file or directory
 #include <address_sorting/address_sorting.h>
                                             ^
compilation terminated.
Makefile:200: recipe for target 'third_party/address_sorting/address_sorting.lo' failed
make: *** [third_party/address_sorting/address_sorting.lo] Error 1
ERROR: `make' failed
```

**Comment by ZhouyihaiDing** [comment]
Seems it works: `2018-03-28 08:32:10,769 PASSED: distribtest.php_linux_x64_jessie`

**Comment by ZhouyihaiDing** [comment]
I guess php extension on windows should also be updated too.
`generate_projects.sh` only update `config.m4`, not `config.w32`. I guess I need to update `config.w32` manually.

**Comment by jtattermusch** [comment]
I confirm both linux & macos php distribtests are now passing:
https://source.cloud.google.com/results/invocations/caf7d25c-5b71-4e81-a8d7-bb95f91875bd/targets/github%2Fgrpc/tests;passed=true
https://source.cloud.google.com/results/invocations/f5957079-f146-4147-bff9-114b40bc1933/targets/github%2Fgrpc/tests
sorry for confusion.
