### ISSUE TITLE
Python windows artifacts build broken: undefined reference to grpc_polling_trace

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11111]
Probably caused by https://github.com/grpc/grpc/pull/11010/

```
2.7\Release\third_party\zlib\gzwrite.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\infback.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\inffast.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\inflate.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\inftrees.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\trees.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\uncompr.o python_build\temp.win-amd64-2.7\Release\third_party\zlib\zutil.o python_build\temp.win-amd64-2.7\Release\src\python\grpcio\grpc\_cython\cygrpc.def -LC:\Python27\libs -LC:\Python27\PCbuild\amd64 -ladvapi32 -lws2_32 -lpython27 -lmsvcr90 -o python_build\lib.win-amd64-2.7\grpc\_cython\cygrpc.pyd -static-libgcc -static-libstdc++ -mcrtdll=msvcr90 -static
C:\msys64\mingw64\bin\g++.exe @c:\temp\tmpzzwzpo\command
python_build\temp.win-amd64-2.7\Release\src\core\lib\iomgr\lockfree_event.o:lockfree_event.c:(.rdata$.refptr.grpc_polling_trace[.refptr.grpc_polling_trace]+0x0): undefined reference to `grpc_polling_trace'
collect2.exe: error: ld returned 1 exit status
Found cython-generated files...
Traceback (most recent call last):
  File "setup.py", line 308, in <module>
    cmdclass=COMMAND_CLASS,
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "C:\Python27\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "C:\Windows\Temp\pygrpc-HPMQCOKIZN\src\python\grpcio\commands.py", line 308, in build_extensions
    support.diagnose_build_ext_error(self, error, formatted_exception)
  File "C:\Windows\Temp\pygrpc-HPMQCOKIZN\src\python\grpcio\support.py", line 122, in diagnose_build_ext_error
    "\n\n{}".format(formatted))
commands.CommandError: 
```

**Comment by jtattermusch** [comment]
CC @kpayson64  @ctiller

**Comment by jtattermusch** [comment]
`python_build\temp.win-amd64-3.4\Release\src\core\lib\iomgr\lockfree_event.o:lockfree_event.c:(.rdata$.refptr.grpc_polling_trace[.refptr.grpc_polling_trace]+0x0): undefined reference to `grpc_polling_trace'`

**Comment by jtattermusch** [comment]
Fixed by #11113
