### ISSUE TITLE
Build fails against protobuf v34

### ISSUE THREAD

**Issue by strophy** [grpc/grpc#41755]
### What version of gRPC and what language are you using?
1.78.1

### What operating system (Linux, Windows,...) and version?
Alpine Linux 3.23.3

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.12.12, gcc 15.2.0

### What did you do?
Attempt to build grpc against protobuf v34

### What did you expect to see?
Build success

### What did you see instead?
```
2026-02-28 10:03:36,229 root INFO c++ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -fno-plt -flto=auto -DNDEBUG -O2 -fPIC -DHAVE_PTHREAD=1 -I. -Igrpc_root -Igrpc_root/include -I/usr/include/python3.12 -c grpc_tools/main.cc -o build/temp.linux-x86_64-cpython-312/grpc_tools/main.o -std=c++17 -DPROTOBUF_USE_DLLS -DNOMINMAX
grpc_tools/main.cc:20:10: fatal error: google/protobuf/compiler/python/generator.h: No such file or directory
   20 | #include <google/protobuf/compiler/python/generator.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
### Anything else we should know about your project / environment?
It looks like this is a breaking change in protobuf v34 introduced in https://github.com/protocolbuffers/protobuf/pull/25326

**Comment by yuanweiz** [comment]
Hi there, could you provide the exact command (bazel or cmake) with which you build gRPC, and how you specified protobuf version?

**Comment by strophy** [comment]
@yuanweiz I came across this while attempting to package protobuf 34 for Alpine Linux, so my process was to build the protobuf 34 package first, then try to build grpc using it as a dependency. You can see the build steps for packaging grpc on Alpine using cmake [here](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/grpc/APKBUILD), the relevant command is:
```
	export CFLAGS="$CFLAGS -flto=auto -DNDEBUG -O2"
	export CXXFLAGS="$CXXFLAGS -flto=auto -DNDEBUG -O2"
	cmake -B _build -G Ninja \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_CXX_STANDARD=17 \
		-DBUILD_SHARED_LIBS=True \
		-DgRPC_INSTALL=ON \
		-DgRPC_CARES_PROVIDER=package \
		-DgRPC_PROTOBUF_PROVIDER=package \
		-DgRPC_SSL_PROVIDER=package \
		-DgRPC_ZLIB_PROVIDER=package \
		-DgRPC_ABSL_PROVIDER=package \
		-DgRPC_BENCHMARK_PROVIDER=package \
		-DgRPC_RE2_PROVIDER=package \
		-DgRPC_USE_SYSTEMD=OFF \
		-DgRPC_BUILD_TESTS=ON
	cmake --build _build
```

**Comment by ash2k** [comment]
I'm seeing this error with Bazel 9.0.1, protobuf 34.0.bcr.1, grpc 1.78.0:

```
(10:20:44) ERROR: error loading package '@@grpc+//src/compiler': at /home/ci/.cache/bazel/_bazel_ci/91775ae2710972ea74be93308706df81/external/grpc+/bazel/grpc_build_system.bzl:34:6: cannot load '@@protobuf+//bazel:upb_proto_library.bzl': no such file
(10:20:44) ERROR: .../build/BUILD.bazel:73:13: error loading package '@@grpc+//src/compiler': at /home/ci/.cache/bazel/_bazel_ci/91775ae2710972ea74be93308706df81/external/grpc+/bazel/grpc_build_system.bzl:34:6: cannot load '@@protobuf+//bazel:upb_proto_library.bzl': no such file and referenced by '//build:ruby_grpc_plugin'
```

It's being loaded here:

https://github.com/grpc/grpc/blob/260c6fd37c502e984836a446c5d90e4a1298036d/bazel/grpc_build_system.bzl#L34

But there is no such file there: https://github.com/protocolbuffers/protobuf/tree/main/bazel.

Full log: https://gitlab.com/gitlab-renovate-forks/gitlab-agent/-/jobs/13447182289#L140

**Comment by ash2k** [comment]
It was moved in this commit: https://github.com/protocolbuffers/protobuf/commit/3a3560bb87058b31ac5f094fcd4dbbf6f90dddaf#diff-fdfef4a54757c155ce74b6556eca574fbd952232ba84cf64d21e8651d12ac395

New place: https://github.com/protocolbuffers/protobuf/blob/main/upb/bazel/upb_proto_library.bzl

**Comment by zifeitong** [comment]
With this patch, I can get grpc compiled with protobuf 34.
```
diff --git a/bazel/grpc_build_system.bzl b/bazel/grpc_build_system.bzl
index 39d621b1ca..d07f4ec04e 100644
--- a/bazel/grpc_build_system.bzl
+++ b/bazel/grpc_build_system.bzl
@@ -31,7 +31,8 @@ load("@build_bazel_apple_support//rules:universal_binary.bzl", "universal_binary
 load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")
 load("@build_bazel_rules_apple//apple/testing/default_runner:ios_test_runner.bzl", "ios_test_runner")
 load("@com_google_protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
-load("@com_google_protobuf//bazel:upb_proto_library.bzl", "upb_proto_library", "upb_proto_reflection_library")
+load("@com_google_protobuf//bazel:upb_c_proto_library.bzl", "upb_c_proto_library")
+load("@com_google_protobuf//bazel:upb_proto_reflection_library.bzl", "upb_proto_reflection_library")
 load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
 load("@rules_cc//cc:cc_library.bzl", "cc_library")
 load("@rules_cc//cc:cc_test.bzl", "cc_test")
@@ -821,7 +822,7 @@ def grpc_objc_library(
     )
 
 def grpc_upb_proto_library(name, deps):
-    upb_proto_library(name = name, deps = deps)
+    upb_c_proto_library(name = name, deps = deps)
 
 def grpc_upb_proto_reflection_library(name, deps):
     upb_proto_reflection_library(name = name, deps = deps)
```

**Comment by lfos** [comment]
At Arch Linux, this is currently blocking us from adopting the most recent protobuf and grpc releases. We're facing the issue reported originally (the most recent comments seem address different symptoms/variants of protobuf incompatibility):
```
building 'grpc_tools._protoc_compiler' extension
[...]
g++ -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/grpc/src=/usr/src/debug/grpc -flto=auto -fPIC -DHAVE_PTHREAD=1 -I. -Igrpc_root -Igrpc_root/include -I/usr/include/python3.14 -c grpc_root/src/compiler/proto_parser_helper.cc -o build/temp.linux-x86_64-cpython-314/grpc_root/src/compiler/proto_parser_helper.o -fno-wrapv -frtti -DPROTOBUF_USE_DLLS -DNOMINMAX
grpc_tools/main.cc:20:10: fatal error: google/protobuf/compiler/python/generator.h: No such file or directory
   20 | #include <google/protobuf/compiler/python/generator.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/g++' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

As @strophy pointed out, the root cause seems to be protobuf [making generator headers private in protobuf 34](https://github.com/protocolbuffers/protobuf/commit/3a2af3510f0d454dbe3e4dc281674b61c4d20b9e) which are still used in `tools/distrib/python/grpcio_tools/grpc_tools/main.cc`:
https://github.com/grpc/grpc/blob/892af433eed19bc42d514db05448d8e5b381f810/tools/distrib/python/grpcio_tools/grpc_tools/main.cc#L32

@sergiitk @yuanweiz - Could you please take a look? We'd appreciate help in getting our Arch Linux rebuilds unblocked.

**Comment by h-vetinari** [comment]
Unrelated to the other problems mentioned so far, but still due to protobuf v34, I'm seeing the following with grpc 1.80:
```
$SRC_DIR/src/core/ext/upb-gen/cel/expr/checked.upb_minitable.c:21:27: error: initialization of 'const struct upb_MiniTable *' from incompatible pointer type 'const upb_MiniTable **' [-Wincompatible-pointer-types]
   21 |   {.UPB_PRIVATE(submsg) = &cel__expr__CheckedExpr__ReferenceMapEntry_msg_init_ptr},
      |                           ^
$SRC_DIR/src/core/ext/upb-gen/cel/expr/checked.upb_minitable.c:21:27: note: (near initialization for 'cel_expr_CheckedExpr__submsgs[0].submsg_dont_copy_me__upb_internal_use_only')
```

**Comment by yuanweiz** [comment]
Hi there, may I ask which language/build system are you using? Since 1.78.1 we upgraded from protobuf 31->33->34->35 on current master. On 1.78 the vendored version (protobuf 31) is what we "implicitly" support.

I think the challenge here is that depending on the build system our customers use (setuptools, cmake, etc) they may need to re-generate those project files using `tools/buildgen/generate_projects.sh` and it's still not guaranteed to work.

**Comment by h-vetinari** [comment]
I'm [trying](https://github.com/conda-forge/grpc-cpp-feedstock/pull/430) to build grpc v1.82.0-pre1 against protobuf v35.1 using CMake, and running into the same issue due -- not for building `libgrpc`, but for building `grpcio-tools`, whose sources still include
https://github.com/grpc/grpc/blob/be12928f61923ae4d5142d4b0b3c1b4564a8fc65/tools/distrib/python/grpcio_tools/grpc_tools/main.cc#L20

This simply cannot work anymore, as after https://github.com/protocolbuffers/protobuf/commit/3a2af3510f0d454dbe3e4dc281674b61c4d20b9e, this header is not exposed anymore (for an already-installed libprotobuf).

**Comment by lfos** [comment]
> I'm [trying](https://github.com/conda-forge/grpc-cpp-feedstock/pull/430) to build grpc v1.82.0-pre1 against protobuf v35.1 using CMake, and running into the same issue due -- not for building `libgrpc`, but for building `grpcio-tools`, whose sources still include
> 
> [grpc/tools/distrib/python/grpcio_tools/grpc_tools/main.cc](https://github.com/grpc/grpc/blob/be12928f61923ae4d5142d4b0b3c1b4564a8fc65/tools/distrib/python/grpcio_tools/grpc_tools/main.cc#L20)
> 
> Line 20 in [be12928](/grpc/grpc/commit/be12928f61923ae4d5142d4b0b3c1b4564a8fc65)
> 
>  #include <google/protobuf/compiler/python/generator.h> 
> This simply cannot work anymore, as after [protocolbuffers/protobuf@3a2af35](https://github.com/protocolbuffers/protobuf/commit/3a2af3510f0d454dbe3e4dc281674b61c4d20b9e), this header is not exposed anymore (for an already-installed libprotobuf).

FYI, this is the workaround we've currently adopted for Arch Linux packages: https://gitlab.archlinux.org/archlinux/packaging/packages/grpc/-/blob/c9ba99f655cb76273f1baaf386c4d7004c3584ff/PKGBUILD#L74-79

**Comment by sergiitk** [comment]
Thank you for the info, this fell of my radar. Added it to Python team's sync agenda next week.

**Comment by sergiitk** [comment]
Note: from what I remember, this only works for us because grpcio-tools package relies on the info from bazel - and in bazel the protobuf made a specific exceptions for us and allowed to still see these helpers:

https://github.com/protocolbuffers/protobuf/blob/77eb569b424235fcb54c31a766126f13ac80b827/src/google/protobuf/compiler/python/BUILD.bazel#L47

```
    visibility = [
        "//pkg:__pkg__",
        "//src/google/protobuf/compiler:__pkg__",
        "@com_github_grpc_grpc//tools/distrib/python/grpcio_tools:__subpackages__",
    ],
```

This is most definitely a tech debt that needs to be solved, and now I see we should prioritize this higher.

**Comment by sergiitk** [comment]
A quick update here: unfortunately, the solution won't be as straightforward as migrating off of these private headers. The reason grpcio-tools is using them is the [gRPC Python Runtime Proto Parsing](https://github.com/grpc/grpc/tree/master/examples/python/no_codegen) feature. Despite being marked as experimental, [the gRFC](https://github.com/grpc/proposal/blob/master/L64-python-runtime-proto-parsing.md) went it, and the community uses it in the wild.

I'm in touch with the Protobuf team - we're brainstorming potential solutions to this problem that works both for Protobuf and gRPC.
