### ISSUE TITLE
Compilation fails on Mac, linking error, undefined symbols

### ISSUE THREAD

**Issue by kolmodin** [grpc/grpc#3148]
My setup has previously been able to build grpc, now I've synced to 68e63c7fc7f9cef30053e56de149b43685451199 and can no longer compile.

```
[LD]      Linking libs/opt/libgrpc++.dylib
Undefined symbols for architecture x86_64:
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      grpc::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, grpc::string_ref const&) in string_ref.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/opt/libgrpc++.dylib] Error 1
```

**Comment by kolmodin** [comment]
https://github.com/grpc/grpc/commits/master/src/cpp/util/string_ref.cc

Issue introduced by 47ec9a40ade6cf5b205b035b1142e0cc539c4f70.

**Comment by nicolasnoble** [comment]
That's pretty odd. Would you care sharing more details about your mac ? Which version of XCode more specifically. `clang++ --version` should do.

**Comment by Synno** [comment]
I am getting the same issue, with this error when running make, I have also use a Mac:

Undefined symbols for architecture x86_64:
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      grpc::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, grpc::string_ref const&) in string_ref.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/opt/libgrpc++.dylib] Error 1

Here's my clang++ version output:
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Comment by ctiller** [comment]
I get it on my Mac also. Will investigate tomorrow.

**Comment by kolmodin** [comment]
```
$ clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by yang-g** [comment]
I am able to reproduce it.

**Comment by yang-g** [comment]
Fixed by #3185
