### ISSUE TITLE
nodejs client doesn't seem to work with include path, anymore

### ISSUE THREAD

**Issue by konsumer** [grpc/grpc#12135]
### What version of gRPC and what language are you using?

NodeJS:
grpc: 1.4.1 
node: 8.2.1
npm: 5.3.0

### What operating system (Linux, Windows, …) and version?

OSX 10.12.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 

### What did you do?

I wrote very simple node-code, like in examples, with the addition of the path params, as they used to be:

```js
const grpc = require('grpc')

const proto = grpc.load({file: 'helloworld.proto', root: `${__dirname}/proto`})
const client = new proto.helloworld.Greeter('localhost:50051', grpc.credentials.createInsecure())

client.SayHello({name: 'World'}, function(err, msg){
  if(err) {
    console.error(err)
  }
  console.log(msg)
})
```
 
My protobuf looks like this:

```proto
syntax = "proto3";
package helloworld;

import "google/api/annotations.proto";

// The request message containing the user's name.
message GreeterRequest {
  string name = 1;
}

// The response message containing the greetings
message GreeterReply {
  string message = 1;
}

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (GreeterRequest) returns (GreeterReply) {}

  // Sends a farewell
  rpc SayGoodbye (GreeterRequest) returns (GreeterReply) {}
}
```

I have included all imported protos in same path (ie `protos/google/api/annotations.proto`)

### What did you expect to see?
 
```json
{
  "message": "Hello World"
}
```
 
### What did you see instead?

```
/Users/konsumer/WORKSPACE/grpc-demo/client.js:6
client.SayHello({name: 'World'}, function(err, msg){
       ^

TypeError: client.SayHello is not a function
    at Object.<anonymous> (/Users/konsumer/WORKSPACE/grpc-demo/client.js:6:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
 
### Anything else we should know about your project / environment?

This used to work with grpc v1.1.2. I rewrote the server code to follow new API (no `children` in services, for example,) and it seems to be working correctly on the server-side. I am pretty sure this is a client-side issue as the error says the method is undefined.

**Comment by konsumer** [comment]
Attached is the full proto/server/client that recreates the error. As a sidenote, in the server, I get this warning when I follow [the documentation](https://grpc.io/docs/tutorials/basic/node.html) which I fix by changing `addProtoService` to `addService`:

```
Server#addProtoService is deprecated. Use addService instead
```

[grpc-issue.zip](https://github.com/grpc/grpc/files/1213101/grpc-issue.zip)

**Comment by murgatroid99** [comment]
The methods are added to the client object in camelCase, so you should call `sayHello`, not `SayHello`.

**Comment by konsumer** [comment]
Ah! That was it. I keep forgetting little non-self-documenting gotchas like this. Is there a flag to not mangle the case of the proto file methods? I could also just make it lower-first in proto, but then it doesn't lint (as this against the style recommendations.)
