### PR TITLE
Implement C++ API for defining channel filters.

### PR DESCRIPTION
**Pull request by markdroth**
This compiles, but that's about all I can say for it thus far.  My next step will be to add a test, but I wanted to get your feedback on my overall approach first.

### CODE REVIEW

File: include/grpc++/channel_filter.h [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+
+// Defines static members for passing to C core.
+template<typename ChannelDataType, typename CallDataType>
+class ChannelFilter {
+  static const size_t call_data_size = sizeof(CallDataType);
+
+  static void InitCallElement(
+      grpc_exec_ctx *exec_ctx, grpc_call_element *elem,
+      grpc_call_element_args *args) {
+    CallDataType* call_data = elem->call_data;
```
Comment (ctiller) [inline include/grpc++/channel_filter.h]: This method should be just:

```c
new (elem->call_data) CallDataType();
```

... there's no guarantee that the data pointed to is initialized, so we want to avoid calling the destructor (or that might crash)

File: include/grpc++/channel_filter.h [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+    *call_data = CallDataType();
+  }
+
+  static void DestroyCallElement(
+      grpc_exec_ctx *exec_ctx, grpc_call_element *elem,
+      const grpc_call_stats *stats, void *and_free_memory) {
+    CallDataType* call_data = elem->call_data;
```
Comment (ctiller) [inline include/grpc++/channel_filter.h]: Similarly, this should just be:

reinterpret_cast<CallDataType*>(elem->call_data)->~CallDataType();

File: include/grpc++/channel_filter.h [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+
+// Represents call data.
+// Note: Must be copyable.
+class CallData {
+ public:
+  // Do not override the destructor.  Instead, put clean-up code in the
+  // Destroy() method.
+  virtual ~CallData() {}
+
+  virtual void Destroy() {}
```
Comment (ctiller) [inline include/grpc++/channel_filter.h]: No need for Destroy

File: include/grpc++/channel_filter.h [hunk 4]
```diff
@@ -0,0 +1,211 @@
...
+    CallDataType* call_data = elem->call_data;
+    return call_data->GetPeer(exec_ctx);
+  }
+
+  static const size_t channel_data_size = sizeof(ChannelDataType);
+
+  static void InitChannelElement(
+      grpc_exec_ctx *exec_ctx, grpc_channel_element *elem,
+      grpc_channel_element_args *args) {
+    ChannelDataType* channel_data = elem->channel_data;
```
Comment (ctiller) [inline include/grpc++/channel_filter.h]: s/CallDataType/ChannelDataType/g for my above comments :)

File: include/grpc++/channel_filter.h [hunk 5]
```diff
@@ -0,0 +1,211 @@
...
+
+void ChannelFilterPluginInit();
+void ChannelFilterPluginShutdown() {}
+
+}  // namespace internal
+
+// Registers a new filter.
+// Must be called by only one thread at a time.
+template<typename ChannelDataType, typename CallDataType>
+void RegisterChannelFilter(const char* name,
```
Comment (ctiller) [inline include/grpc++/channel_filter.h]: We might want to add the argument:
```
std::function<bool(grpc_channel_args*)> should_this_filter_be_included
```
to allow runtime decisions to be made about this filter

**Comment by ctiller** [comment]
I think I'm done on the first pass here... looking good.

File: include/grpc++/channel_filter.h (hunk 1 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Very cool -- I didn't know "new" was able to construct an object in previously-allocated memory.

Done.

File: include/grpc++/channel_filter.h (hunk 2 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Duh -- it also didn't occur to me that I could explicitly call the destructor, but it probably should have.

Done.

File: include/grpc++/channel_filter.h (hunk 3 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Done.

File: include/grpc++/channel_filter.h (hunk 4 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Yup, done.

File: include/grpc++/channel_filter.h (hunk 5 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Done.

**Comment by markdroth** [comment]
As we discussed, I've changed it to pass the channel args to the ChannelData ctor and the ChannelData object to the CallData ctor.

I've added a test that demonstrates how this works.

Please let me know what you think.  Thanks!

File: include/grpc++/channel_filter.h [hunk 6]
```diff
@@ -0,0 +1,200 @@
...
+#ifndef GRPCXX_CHANNEL_FILTER_H
+#define GRPCXX_CHANNEL_FILTER_H
+
+#include <grpc/grpc.h>
+
+#include <functional>
+#include <vector>
+
+#include "src/core/lib/channel/channel_stack.h"
+#include "src/core/lib/surface/channel_init.h"
```
Comment (vjpai) [inline include/grpc++/channel_filter.h]: I think "include/grpc++" files should not include "src/..." anything since installations will have the include/ directory but not necessarily the src

Comment (markdroth) [inline include/grpc++/channel_filter.h]: Yup.  Craig and I talked about this earlier today.  The intent is to move the necessary headers from src to include, thus making them part of the public API.  But Craig wanted to iron out some details of API versioning before we do that.

This PR won't be merged until we have resolved the API versioning issues.

Comment (ctiller) [inline include/grpc++/channel_filter.h]: Yeah we've been chatting about that offline a little. It forces the issue
of versioning for core. I'll write up a little blurb later on and finally
put a nail in this.

File: src/cpp/common/channel_filter.cc [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+  grpc_channel_next_op(exec_ctx, elem, op);
+}
+
+//
+// RegisterChannelFilter()
+//
+
+namespace internal {
+
+std::vector<FilterRecord> *channel_filters = nullptr;
```
Comment (vjpai) [inline src/cpp/common/channel_filter.cc]: Omit the " = nullptr" - it's more compatible.

File: src/cpp/common/channel_filter.cc [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+
+namespace {
+
+bool MaybeAddFilter(grpc_channel_stack_builder *builder, void *arg) {
+  const FilterRecord &filter = *(FilterRecord *)arg;
+  if (filter.include_filter != nullptr) {
```
Comment (vjpai) [inline src/cpp/common/channel_filter.cc]: Omit the "!= nullptr"

File: test/cpp/end2end/filter_end2end_test.cc [hunk 9]
```diff
@@ -0,0 +1,327 @@
...
+    server_address_ << server_host_ << ":" << port;
+    // Setup server
+    ServerBuilder builder;
+    builder.AddListeningPort(server_address_.str(),
+                             InsecureServerCredentials());
+    builder.RegisterAsyncGenericService(&generic_service_);
+    // Include a second call to RegisterAsyncGenericService to make sure that
+    // we get an error in the log, since it is not allowed to have 2 async
+    // generic services
+    builder.RegisterAsyncGenericService(&generic_service_);
```
Comment (vjpai) [inline test/cpp/end2end/filter_end2end_test.cc]: The above seems unneeded, since that's already handled in end2end_test

File: src/cpp/common/channel_filter.cc (hunk 7 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: What's the compatibility issue?

I think this needs to be initialized, since the code in RegisterChannelFilter() depends on the value being nullptr to know whether or not to allocate a new vector object.

File: src/cpp/common/channel_filter.cc (hunk 8 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: I tend to find the code more readable this way, because it makes it obvious to the reader than the variable is a pointer (as opposed to, say, a bool).  Is there some compatibility reason to change this?  (For example, if the problem is using nullptr instead of NULL, I could change to the latter.)

File: test/cpp/end2end/filter_end2end_test.cc (hunk 9 above)
Comment (markdroth) [inline test/cpp/end2end/filter_end2end_test.cc]: Done.  (This was copied from generic_end2end_test.cc, which is what I used as the base of this file.)

File: src/cpp/common/channel_filter.cc (hunk 7 above)
Comment (vjpai) [inline src/cpp/common/channel_filter.cc]: Some nullptr issues are discussed in https://github.com/grpc/grpc/blob/master/doc/cpp-style-guide.md . I have added this particular one to the big compatibility issue in #6863 . This initialization is not needed because channel_filters here has static lifetime, and all pointers with static lifetime are implicitly initialized to nullptr.

File: src/cpp/common/channel_filter.cc (hunk 8 above)
Comment (vjpai) [inline src/cpp/common/channel_filter.cc]: The problem is discussed in https://github.com/grpc/grpc/blob/master/doc/cpp-style-guide.md :
nullptr wasn't accepted by gcc until 4.6. We can't use NULL as a substitute for nullptr (it's just the numerical value 0)

File: src/cpp/common/channel_filter.cc (hunk 7 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: Got it.  I think I knew that about variables declared as "static", but I somehow didn't realize that it also applied to those defined in an anonymous namespace.

File: src/cpp/common/channel_filter.cc (hunk 8 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: Done.

File: src/cpp/common/channel_filter.cc (hunk 7 above)
Comment (vjpai) [inline src/cpp/common/channel_filter.cc]: Right - it applies to anything that has static storage, not just the keyword `static`.

**Comment by markdroth** [comment]
This now depends on #7024.

File: include/grpc++/channel_filter.h [hunk 10]
```diff
@@ -0,0 +1,365 @@
...
+
+#include <functional>
+#include <vector>
+
+#include "src/core/lib/channel/channel_stack.h"
+#include "src/core/lib/security/context/security_context.h"
+#include "src/core/lib/surface/channel_init.h"
+#include "src/core/lib/transport/metadata_batch.h"
+
+//
```
Comment (dgquintas) [inline include/grpc++/channel_filter.h]: Let's use `///` for comments so that Doxygen picks them up. It's also advisable to use Doxygen tags (https://www.stack.nl/~dimitri/doxygen/manual/commands.html) where appropriate (we use the \ convention).

File: include/grpc++/channel_filter.h [hunk 11]
```diff
@@ -0,0 +1,365 @@
...
+// An interface to define filters.
+//
+// To define a filter, implement a subclass of each of CallData and
+// ChannelData.  Then register the filter using something like this:
```
Comment (dgquintas) [inline include/grpc++/channel_filter.h]: as a nit/pet-peeve (and with no written rule for nor against it) we've also been use single-space-after-period in docstrings.

File: include/grpc++/channel_filter.h [hunk 12]
```diff
@@ -0,0 +1,365 @@
...
+//
+
+namespace grpc {
+
+// A C++ wrapper for the grpc_metadata_batch struct.
+class MetadataBatch {
+ public:
+  explicit MetadataBatch(grpc_metadata_batch *batch) : batch_(batch) {}
+
+  grpc_metadata_batch *batch() const { return batch_; }
```
Comment (dgquintas) [inline include/grpc++/channel_filter.h]: maybe we'd want a version of `batch()` returning a constant pointer? That'd allow for const instances of `MetadataBatch`.

File: include/grpc++/channel_filter.h [hunk 13]
```diff
@@ -0,0 +1,365 @@
...
+  // FIXME: find a way to avoid passing elem into these methods
+  // (same for CallData below)
+  virtual void StartTransportOp(grpc_exec_ctx *exec_ctx,
+                                grpc_channel_element *elem, TransportOp *op);
+
+ protected:
+  ChannelData(const grpc_channel_args &args, const char *peer) : peer_(peer) {}
+
+ private:
+  const char *peer_;  // Do not own.
```
Comment (dgquintas) [inline include/grpc++/channel_filter.h]: s/Do/Does? sounds imperative otherwise.

File: include/grpc++/channel_filter.h (hunk 10 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Done.

File: include/grpc++/channel_filter.h (hunk 11 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Sorry, I'm incapable of not typing two spaces after a period. :)  Fixed.

File: include/grpc++/channel_filter.h (hunk 12 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: I don't anticipate this being used anywhere other than a filter, and since we don't know whether or not a given filter will want to modify metadata, we need to pass it in as non-const.  So it doesn't seem like there's any immediate benefit in a const method.

File: include/grpc++/channel_filter.h (hunk 13 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: Actually, in this particular case, the comment was just plain wrong, so I've removed it and changed the dtor to free the memory. :)

I have updated the wording in several other places, though.

File: include/grpc++/channel_filter.h (hunk 6 above)
Comment (markdroth) [inline include/grpc++/channel_filter.h]: As per my discussion with Craig this afternoon, we're not going to make this a public API right now.  So I've moved the header file into the src tree.

**Comment by markdroth** [comment]
@vjpai It looks like the gcc-4.4 compatibility test is failing due to a use of nullptr.  Looking at https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/4433/language=c++,scenario=linux_x64_gcc4.4_bo/console, the error is:

```
[CXX]     Compiling test/cpp/end2end/generic_end2end_test.cc
test/cpp/end2end/filter_end2end_test.cc: In function 'int main(int, char**)':
test/cpp/end2end/filter_end2end_test.cc:347: error: 'nullptr' was not declared in this scope
make: *** [/var/local/git/grpc/objs/dbg/test/cpp/end2end/filter_end2end_test.o] Error 1
```

In this case, what's happening is that we're got a function that takes a std::function<> as a parameter, and we're calling the function with nullptr as the value for that parameter.  What's the right way to deal with this to make gcc-4.4 happy?  Should I just use NULL instead of nullptr, or is something else needed?

**Comment by vjpai** [comment]
I did add a typecast for `nullptr`->`std::function` in PR #6863  so it's definitely feasible. Looking at the error, though, I think I know the issue. Remember that `nullptr` is a defined thing so you have to explicitly `#include <grpc++/support/config.h>` or else `nullptr` won't be understood. Does that work?

**Comment by vjpai** [comment]
Also, FWIW, `NULL` won't work. That's just the number 0, and it is not convertible to unique_ptr, function. etc. That was how we got into that hacked-up definition of `nullptr` to begin with.

**Comment by markdroth** [comment]
Unfortunately, it looks like adding that include didn't fix the problem.  I'm still seeing exactly the same error:

```
test/cpp/end2end/filter_end2end_test.cc: In function 'int main(int, char**)':
test/cpp/end2end/filter_end2end_test.cc:348: error: 'nullptr' was not declared in this scope
make: *** [/var/local/git/grpc/objs/dbg/test/cpp/end2end/filter_end2end_test.o] Error 1
```

I'm not sure why this isn't working, since I do see the definition of nullptr in config.h.  Any ideas?

**Comment by markdroth** [comment]
Oh!  I think the problem is that the definition of nullptr in config.h is in the grpc namespace, and this function call is not.  I'll try moving the call into the grpc namespace and see if that fixes it.

**Comment by pgrosu** [comment]
Hi Mark,

GCC 4.4 does not include `nullptr`, and was only introduced in GCC 4.6 as noted in the following link:

https://gcc.gnu.org/gcc-4.6/changes.html

Try using `__null` instead which should work, or define it with something like this:

```C
# define nullptr __null
```

Or more elaborately like this:

```C
#ifndef HAVE_NULLPTR
#if defined(_WIN64)
# define nullptr 0LL
#elif defined(__GNUC__)
# define nullptr __null
#else
# define nullptr 0L
#endif
#endif /* defined(HAVE_NULLPTR) */
```

There are many choices :)

Hope it helps,
Paul

**Comment by markdroth** [comment]
@pgrosu, thanks for the info.  I know about the lack of nullptr in gcc-4.4, and @vjpai has created a nullptr implementation that works in gcc-4.4 for cases like this, so the issue here was trying to figure out why that wasn't working.

**Comment by pgrosu** [comment]
@markdroth Maybe my eyes are playing tricks on me, but could you please point me to the definition by @vjpai?  I'm looking at [include/grpc++/impl/codegen/config.h](https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/config.h#L52-65) at lines 52-65, and not seeing `nullptr`  being specifically defined: 

```
#ifndef __clang__
#ifdef __GNUC__
// nullptr was added in gcc 4.6
#if (__GNUC__ * 100 + __GNUC_MINOR__ < 406)
#define GRPC_CXX0X_NO_NULLPTR 1
#define GRPC_CXX0X_LIMITED_TOSTRING 1
#endif
// final and override were added in gcc 4.7
#if (__GNUC__ * 100 + __GNUC_MINOR__ < 407)
#define GRPC_CXX0X_NO_FINAL 1
#define GRPC_CXX0X_NO_OVERRIDE 1
#endif
#endif
#endif
```

Thanks,
~p

**Comment by markdroth** [comment]
@pgrosu, it's here:

https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/config.h#L81-109

**Comment by pgrosu** [comment]
@markdroth Thank you, but doesn't `#ifdef GRPC_CXX0X_NO_NULLPTR` mean that it will include it if and only if the macro is already defined according to the following:

https://gcc.gnu.org/onlinedocs/cpp/Ifdef.html

I don't believe `GRPC_CXX0X_NO_NULLPTR` is defined anywhere else.

Thanks,
~p

**Comment by markdroth** [comment]
@pgrosu, the code you originally pointed to (lines 52-65) cause `GRPC_CXX0X_NO_NULLPTR` to be defined.  Specifically, see line 56.  Thus, when we get to line 81, the definition is present and the `#ifdef` will evaluate to true.

**Comment by pgrosu** [comment]
@markdroth Thank you for helping me, up 404 < 406 :)

**Comment by markdroth** [comment]
It looks like the portability tests now pass, so moving the use of nullptr into the grpc namespace solved the problem.

**Comment by pgrosu** [comment]
Super!

File: include/grpc++/channel_filter.h (hunk 12 above)
Comment (dgquintas) [inline include/grpc++/channel_filter.h]: Agreed.

**Comment by markdroth** [comment]
retest this please

**Comment by ctiller** [comment]
This seems good... I'm not going to get time to do a thorough review (so hoping someone else can pull out the comb), but I have no objections.

**Comment by markdroth** [comment]
retest this please

**Comment by markdroth** [comment]
David, can you take over this review from Craig, since you've already looked at the code?  Thanks!

**Comment by markdroth** [comment]
retest this please

**Comment by markdroth** [comment]
retest this please

**Comment by markdroth** [comment]
retest this please

File: src/core/lib/channel/context.h [hunk 14]
```diff
@@ -34,10 +34,19 @@
 #ifndef GRPC_CORE_LIB_CHANNEL_CONTEXT_H
 #define GRPC_CORE_LIB_CHANNEL_CONTEXT_H
 
-/* Call object context pointers */
+// Call object context pointers.
```
Comment (dgquintas) [inline src/core/lib/channel/context.h]: Could you use triple slashes so that Doxygen can pick up the comments?

File: src/cpp/common/channel_filter.cc [hunk 15]
```diff
@@ -0,0 +1,120 @@
...
+ */
+
+#include <string.h>
+
+#include "src/core/lib/channel/channel_stack.h"
+#include "src/cpp/common/channel_filter.h"
+
+namespace grpc {
+
+//
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.cc]: Not personally against this type of banner comments, but we don't use them across the codebase. If anything, I'd reduce them to a single line with no empty lines in between, viz:

````
// MetadataBatch
grpc_linked_mdelem moar codez ...
```

File: src/cpp/common/channel_filter.cc [hunk 16]
```diff
@@ -0,0 +1,120 @@
...
+    FilterRecord &filter = (*channel_filters)[i];
+    grpc_channel_init_register_stage(filter.stack_type, filter.priority,
+                                     MaybeAddFilter, (void *)&filter);
+  }
+}
+
+void ChannelFilterPluginShutdown() {}
+
+}  // namespace internal
+
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.cc]: weak nit: remove empty line

File: src/cpp/common/channel_filter.h [hunk 17]
```diff
@@ -0,0 +1,373 @@
...
+
+#include <functional>
+#include <vector>
+
+#include "src/core/lib/channel/channel_stack.h"
+#include "src/core/lib/security/context/security_context.h"
+#include "src/core/lib/surface/channel_init.h"
+#include "src/core/lib/transport/metadata_batch.h"
+
+///
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: Similar comment as before: we don't usually wrap comments in extra whitespace. You use an extra empty line plus an empty comment line. Perhaps we should standardize on one style on the styleguide :)

File: src/cpp/common/channel_filter.h [hunk 18]
```diff
@@ -0,0 +1,373 @@
...
+namespace grpc {
+
+/// A C++ wrapper for the \c grpc_metadata_batch struct.
+class MetadataBatch {
+ public:
+  explicit MetadataBatch(grpc_metadata_batch *batch) : batch_(batch) {}
+
+  grpc_metadata_batch *batch() const { return batch_; }
+
+  // Adds metadata and returns the newly allocated storage.
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: why not `///`?

File: src/cpp/common/channel_filter.cc [hunk 19]
```diff
@@ -0,0 +1,120 @@
...
+                                      grpc_polling_entity *pollent) {
+  grpc_call_stack_ignore_set_pollset_or_pollset_set(exec_ctx, elem, pollent);
+}
+
+char *CallData::GetPeer(grpc_exec_ctx *exec_ctx, grpc_call_element *elem) {
+  return grpc_call_next_get_peer(exec_ctx, elem);
+}
+
+//
+// RegisterChannelFilter()
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.cc]: there's nothing related to RegisterChannelFilter here.

File: src/cpp/common/channel_filter.h [hunk 20]
```diff
@@ -0,0 +1,373 @@
...
+///       "name-of-filter", GRPC_SERVER_CHANNEL, INT_MAX, nullptr);
+/// \endcode
+///
+
+namespace grpc {
+
+/// A C++ wrapper for the \c grpc_metadata_batch struct.
+class MetadataBatch {
+ public:
+  explicit MetadataBatch(grpc_metadata_batch *batch) : batch_(batch) {}
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: comment plz. Is ownership taken?

File: src/cpp/common/channel_filter.h [hunk 21]
```diff
@@ -0,0 +1,373 @@
...
+  const_iterator end() const { return const_iterator(nullptr); }
+
+ private:
+  grpc_metadata_batch *batch_;  // Not owned.
+};
+
+/// A C++ wrapper for the \c grpc_transport_op struct.
+class TransportOp {
+ public:
+  explicit TransportOp(grpc_transport_op *op) : op_(op) {}
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: same. comment wrt ownership of argument.

File: src/cpp/common/channel_filter.h [hunk 22]
```diff
@@ -0,0 +1,373 @@
...
+ private:
+  grpc_transport_op *op_;  // Not owned.
+};
+
+/// A C++ wrapper for the \c grpc_transport_stream_op struct.
+class TransportStreamOp {
+ public:
+  explicit TransportStreamOp(grpc_transport_stream_op *op)
+      : op_(op),
+        send_initial_metadata_(op->send_initial_metadata),
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: why do we have all these member variables? they seem to be an alias of their corresponding `op_->` persona.

File: src/cpp/common/channel_filter.h [hunk 23]
```diff
@@ -0,0 +1,373 @@
...
+        recv_trailing_metadata_(op->recv_trailing_metadata) {}
+
+  grpc_transport_stream_op *op() const { return op_; }
+
+  grpc_closure *on_complete() const { return op_->on_complete; }
+  void set_on_complete(grpc_closure *closure) { op_->on_complete = closure; }
+
+  MetadataBatch *send_initial_metadata() {
+    return op_->send_initial_metadata == nullptr ? nullptr
+                                                 : &send_initial_metadata_;
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: why not simply return `op_->send_initial_metadata_`?

File: src/cpp/common/channel_filter.h [hunk 24]
```diff
@@ -0,0 +1,373 @@
...
+
+ private:
+  const char *peer_;
+};
+
+/// Represents call data.
+class CallData {
+ public:
+  virtual ~CallData() {}
+
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: comments on public interfaces please

File: src/cpp/common/channel_filter.h [hunk 25]
```diff
@@ -0,0 +1,373 @@
...
+  virtual char *GetPeer(grpc_exec_ctx *exec_ctx, grpc_call_element *elem);
+
+ protected:
+  explicit CallData(const ChannelData &) {}
+};
+
+namespace internal {
+
+// Defines static members for passing to C core.
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: `s://:///`

File: src/cpp/common/channel_filter.h [hunk 26]
```diff
@@ -0,0 +1,373 @@
...
+template <typename ChannelDataType, typename CallDataType>
+class ChannelFilter GRPC_FINAL {
+ public:
+  static const size_t channel_data_size = sizeof(ChannelDataType);
+
```
Comment (dgquintas) [inline src/cpp/common/channel_filter.h]: comments on publics

File: src/core/lib/channel/context.h (hunk 14 above)
Comment (markdroth) [inline src/core/lib/channel/context.h]: Done.

File: src/cpp/common/channel_filter.cc (hunk 15 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: I find these comments useful to help quickly visually find the right section of the file.

Reduced to a single line, but left a blank line afterwards.

File: src/cpp/common/channel_filter.cc (hunk 16 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: The two namespaces start at different points, so the blank line in between seems appropriate to me.  (It would be different if, for example, all of our code was in the namespace net::grpc, at which point all files would start and end with the same two lines of namespace wrapping.)

File: src/cpp/common/channel_filter.h (hunk 17 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Removed the extra comment lines.

File: src/cpp/common/channel_filter.h (hunk 18 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Done.

File: src/cpp/common/channel_filter.cc (hunk 19 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.cc]: The code here is internal code used by RegisterChannelFilter().  I've updated the comment to make that clear.

File: src/cpp/common/channel_filter.h (hunk 20 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Done.

File: src/cpp/common/channel_filter.h (hunk 21 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Done.

File: src/cpp/common/channel_filter.h (hunk 22 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: The goal here is to provide a more C++-like API for accessing metadata.  Thus, the member variables are C++ MetadataBatch objects, which are wrapped around the corresponding C grpc_metadata_batch structs.

File: src/cpp/common/channel_filter.h (hunk 23 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: As I mentioned above, the goal here is to provide a more idiomatic C++ API for accessing metadata.

File: src/cpp/common/channel_filter.h (hunk 24 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Done.

File: src/cpp/common/channel_filter.h (hunk 25 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Since this is just an internal function, not for external use, I was thinking that we don't actually want Doxygen to pick up the docstring for it.  Is there a reason to do so even for internal functions?

File: src/cpp/common/channel_filter.h (hunk 26 above)
Comment (markdroth) [inline src/cpp/common/channel_filter.h]: Added a comment saying that the members of this class correspond to those of the C grpc_channel_filter struct.

**Comment by dgquintas** [comment]
LGTM

**Comment by dgquintas** [comment]
It seems you need to regenerate projects (https://grpc-testing.appspot.com/job/gRPC_pull_requests/11549/config=opt,language=sanity,platform=linux/consoleText)

**Comment by markdroth** [comment]
I believe the remaining test failures are flakes, so I'm calling this ready to merge.

**Comment by dgquintas** [comment]
+1
