### ISSUE TITLE
Build failure in clang 16

### ISSUE THREAD

**Issue by laramiel** [grpc/grpc#34482]
In `@com_github_grpc_grpc//:tsi_base`, while building `src/core/tsi/transport_security_grpc.h` there is a `#include <grpc/slice_buffer.h>`.
 
With our  (http://github.com/google/tensorstore)  current build config in a docker container using clang, this fails with:

```
(05:03:09) ERROR: /tmpfs/home/.cache/bazel/_bazel_kbuilder/0a4c8b5856e211cadfadc78bc383ae28/external/com_github_grpc_grpc/BUILD:1760:16: Compiling src/core/tsi/transport_security_grpc.cc failed: (Exit 1): clang-17 failed: error executing command (from target @com_github_grpc_grpc//:tsi_base) 
  (cd /tmpfs/home/.cache/bazel/_bazel_kbuilder/0a4c8b5856e211cadfadc78bc383ae28/sandbox/processwrapper-sandbox/1193/execroot/tensorstore && \
  exec env - \
    PATH=/tmpfs/home/.cache/bazelisk/downloads/bazelbuild/bazel-6.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /opt/llvm/clang/bin/clang-17 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -nostdinc++ -I/opt/llvm/libcxx/include/c++/v1 -MD -MF bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/_objs/tsi_base/transport_security_grpc.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/_objs/tsi_base/transport_security_grpc.pic.o' -fPIC '-DBAZEL_CURRENT_REPOSITORY="com_github_grpc_grpc"' -iquote external/com_github_grpc_grpc -iquote bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc -iquote external/com_google_absl -iquote bazel-out/k8-fastbuild/bin/external/com_google_absl -isystem external/com_github_grpc_grpc/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem external/com_github_grpc_grpc/src/core/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/include -isystem external/com_github_grpc_grpc/src/core/src/core/ext/upb-generated -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/src/core/ext/upbdefs-generated -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/src/core/ext/upbdefs-generated '-fdiagnostics-color=always' -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-but-set-parameter -Wno-maybe-uninitialized -Wno-sequence-point -Wno-unknown-warning-option '-std=c++17' -fsized-deallocation -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-fmodule-name=@com_github_grpc_grpc//:tsi_base' '-fmodule-map-file=bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/tsi_base.cppmap' -fmodules-strict-decluse -Wprivate-header '-fmodule-map-file=external/local_config_cc/module.modulemap' '-fmodule-map-file=bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/gpr.cppmap' '-fmodule-map-file=bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/grpc_trace.cppmap' -c external/com_github_grpc_grpc/src/core/tsi/transport_security_grpc.cc -o bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/_objs/tsi_base/transport_security_grpc.pic.o)
# Configuration: 11d0eba0ed71206d4872113f48bfc78335256a73a7ba75004fd7d122c301d5a2
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_github_grpc_grpc/src/core/tsi/transport_security_grpc.cc:21:
external/com_github_grpc_grpc/src/core/tsi/transport_security_grpc.h:24:10: error: module @com_github_grpc_grpc//:tsi_base does not depend on a module exporting 'grpc/slice_buffer.h'
   24 | #include <grpc/slice_buffer.h>
      |          ^
1 error generated.
```

It appears to me that slice_buffer.h (https://github.com/grpc/grpc/blob/3f9417a775a72dc2e5a9e8061f7ae7e2c8425558/BUILD#L255)  is exposed in several places, but the indicated target file lacks a dependency on `//:grpc_public_hdrs` (https://github.com/grpc/grpc/blob/3f9417a775a72dc2e5a9e8061f7ae7e2c8425558/src/core/BUILD#L3137C4-L3137C4)

A similar build issue appears with `@com_github_grpc_grpc//:grpc++_binder`:

```
(05:04:26) ERROR: /tmpfs/home/.cache/bazel/_bazel_kbuilder/0a4c8b5856e211cadfadc78bc383ae28/external/com_github_grpc_grpc/BUILD:978:16: Compiling src/core/ext/transport/binder/wire_format/wire_reader_impl.cc failed: (Exit 1): clang-17 failed: error executing command (from target @com_github_grpc_grpc//:grpc++_binder) 
  (cd /tmpfs/home/.cache/bazel/_bazel_kbuilder/0a4c8b5856e211cadfadc78bc383ae28/sandbox/processwrapper-sandbox/1982/execroot/tensorstore && \
  exec env - \
    PATH=/tmpfs/home/.cache/bazelisk/downloads/bazelbuild/bazel-6.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /opt/llvm/clang/bin/clang-17 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -nostdinc++ -I/opt/llvm/libcxx/include/c++/v1 -MD -MF bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/grpc++_binder/wire_reader_impl.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/grpc++_binder/wire_reader_impl.pic.o' -fPIC -DCHROMIUM_ZLIB_NO_CHROMECONF -DCARES_STATICLIB '-DBAZEL_CURRENT_REPOSITORY="com_github_grpc_grpc"' -iquote external/com_github_grpc_grpc -iquote bazel-out/k8-opt/bin/external/com_github_grpc_grpc -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/com_google_googleapis -iquote bazel-out/k8-opt/bin/external/com_google_googleapis -iquote external/com_google_protobuf_upb -iquote bazel-out/k8-opt/bin/external/com_google_protobuf_upb -iquote external/com_google_protobuf_utf8_range -iquote bazel-out/k8-opt/bin/external/com_google_protobuf_utf8_range -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/net_zlib -iquote bazel-out/k8-opt/bin/external/net_zlib -iquote external/com_google_boringssl -iquote bazel-out/k8-opt/bin/external/com_google_boringssl -iquote external/com_github_cncf_udpa -iquote bazel-out/k8-opt/bin/external/com_github_cncf_udpa -iquote external/local_proto_mirror -iquote bazel-out/k8-opt/bin/external/local_proto_mirror -iquote external/com_github_cares_cares -iquote bazel-out/k8-opt/bin/external/com_github_cares_cares -iquote external/com_google_re2 -iquote bazel-out/k8-opt/bin/external/com_google_re2 -iquote external/envoy_api -iquote bazel-out/k8-opt/bin/external/envoy_api -Ibazel-out/k8-opt/bin/external/com_google_googleapis -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src -Ibazel-out/k8-opt/bin/external/com_github_grpc_grpc -Ibazel-out/k8-opt/bin/external/net_zlib/_virtual_includes/zlib -Ibazel-out/k8-opt/bin/external/net_zlib/_virtual_includes/zlib_opt_includes -Ibazel-out/k8-opt/bin/external/com_github_cncf_udpa -Ibazel-out/k8-opt/bin/external/local_proto_mirror -Ibazel-out/k8-opt/bin/external/envoy_api -Ibazel-out/k8-opt/bin/external/com_google_protobuf/_virtual_includes/protobuf -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/protobuf -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/protobuf_nowkt -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/protobuf_lite -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_align -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/stubs/_virtual_includes/lite -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/port_def -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_allocation_policy -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_config -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_cleanup -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/string_block -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/varint_shuffle -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/io -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/io_win32 -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/gzip_stream -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/stubs/_virtual_includes/stubs -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/printer -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/zero_copy_sink -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/tokenizer -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/any_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/api_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/source_context_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/type_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/empty_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/struct_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/wrappers_proto -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/compiler/_virtual_includes/importer -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/delimited_message_util -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/differencer -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/field_mask_util -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/json_util -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/json -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/parser -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/descriptor_traits -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/lexer -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/message_path -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/zero_copy_buffered_stream -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/untyped_message -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/type_resolver_util -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/descriptor_legacy -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/unparser -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/writer -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/time_util -isystem external/com_github_grpc_grpc/include -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem external/com_github_grpc_grpc/src/core/include -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/include -isystem external/com_github_grpc_grpc/src/core/src/core/ext/upb-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/src/core/ext/upbdefs-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/src/core/ext/upbdefs-generated -isystem external/com_google_boringssl/src/include -isystem bazel-out/k8-opt/bin/external/com_google_boringssl/src/include -isystem external/com_github_grpc_grpc/third_party/xxhash -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/third_party/xxhash -isystem external/com_github_grpc_grpc/third_party/address_sorting/include -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/third_party/address_sorting/include -isystem external/com_github_cares_cares -isystem bazel-out/k8-opt/bin/external/com_github_cares_cares -isystem external/com_github_cares_cares/include -isystem bazel-out/k8-opt/bin/external/com_github_cares_cares/include '-fdiagnostics-color=always' -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-but-set-parameter -Wno-maybe-uninitialized -Wno-sequence-point -Wno-unknown-warning-option '-fvisibility=hidden' '-std=c++17' -fsized-deallocation -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-fmodule-name=@com_github_grpc_grpc//:grpc++_binder' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/grpc++_binder.cppmap' -fmodules-strict-decluse -Wprivate-header '-fmodule-map-file=external/local_config_cc/module.modulemap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/config.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/debug_location.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/exec_ctx.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/gpr.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/gpr_platform.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/grpc.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/grpc++_base.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/grpc_base.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/grpc_client_channel.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/grpc_public_hdrs.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/orphanable.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/ref_counted_ptr.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/arena.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/channel_args.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/channel_args_preconditioning.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/channel_stack_type.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/default_event_engine.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/iomgr_fwd.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/iomgr_port.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/slice.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/slice_refcount.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/status_helper.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/transport_fwd.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/base/core_headers.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/cleanup/cleanup.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/container/flat_hash_map.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/functional/any_invocable.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/hash/hash.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/memory/memory.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/meta/type_traits.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/status/status.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/status/statusor.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/strings/strings.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/synchronization/synchronization.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/time/time.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/types/variant.cppmap' -c external/com_github_grpc_grpc/src/core/ext/transport/binder/wire_format/wire_reader_impl.cc -o bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/grpc++_binder/wire_reader_impl.pic.o)
# Configuration: f5138babd12d457d42947482e3ba8ba0fd4aef9b665759e4c4302475db183ebf
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_github_grpc_grpc/src/core/ext/transport/binder/wire_format/wire_reader_impl.cc:17:
external/com_github_grpc_grpc/src/core/ext/transport/binder/wire_format/wire_reader_impl.h:33:10: error: module @com_github_grpc_grpc//:grpc++_binder does not depend on a module exporting 'src/core/lib/gprpp/notification.h'
   33 | #include "src/core/lib/gprpp/notification.h"
      |          ^
1 error generated.
```

Which is exposed as `//core:notification`:
https://github.com/grpc/grpc/blob/3f9417a775a72dc2e5a9e8061f7ae7e2c8425558/src/core/BUILD#L2695

Likewise `@com_github_grpc_grpc//:iomgr_buffer_list` needs a dependency on `absl/types:optional`:

```
(05:05:04) ERROR: /tmpfs/home/.cache/bazel/_bazel_kbuilder/0a4c8b5856e211cadfadc78bc383ae28/external/com_github_grpc_grpc/BUILD:2633:16: Compiling src/core/lib/iomgr/buffer_list.cc failed: (Exit 1): clang-17 failed: error executing command (from target @com_github_grpc_grpc//:iomgr_buffer_list) 
  (cd /tmpfs/home/.cache/bazel/_bazel_kbuilder/0a4c8b5856e211cadfadc78bc383ae28/sandbox/processwrapper-sandbox/2291/execroot/tensorstore && \
  exec env - \
    PATH=/tmpfs/home/.cache/bazelisk/downloads/bazelbuild/bazel-6.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /opt/llvm/clang/bin/clang-17 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -nostdinc++ -I/opt/llvm/libcxx/include/c++/v1 -MD -MF bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/iomgr_buffer_list/buffer_list.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/iomgr_buffer_list/buffer_list.pic.o' -fPIC '-DBAZEL_CURRENT_REPOSITORY="com_github_grpc_grpc"' -iquote external/com_github_grpc_grpc -iquote bazel-out/k8-opt/bin/external/com_github_grpc_grpc -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/com_google_googleapis -iquote bazel-out/k8-opt/bin/external/com_google_googleapis -iquote external/com_google_protobuf_upb -iquote bazel-out/k8-opt/bin/external/com_google_protobuf_upb -iquote external/com_google_protobuf_utf8_range -iquote bazel-out/k8-opt/bin/external/com_google_protobuf_utf8_range -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -Ibazel-out/k8-opt/bin/external/com_google_googleapis -Ibazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/com_github_grpc_grpc/include -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem external/com_github_grpc_grpc/src/core/include -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/include -isystem external/com_github_grpc_grpc/src/core/src/core/ext/upb-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/src/core/ext/upbdefs-generated -isystem bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/src/core/ext/upbdefs-generated '-fdiagnostics-color=always' -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-but-set-parameter -Wno-maybe-uninitialized -Wno-sequence-point -Wno-unknown-warning-option '-fvisibility=hidden' '-std=c++17' -fsized-deallocation -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-fmodule-name=@com_github_grpc_grpc//:iomgr_buffer_list' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/iomgr_buffer_list.cppmap' -fmodules-strict-decluse -Wprivate-header '-fmodule-map-file=external/local_config_cc/module.modulemap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/gpr.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/iomgr_internal_errqueue.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/error.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/core/iomgr_port.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/strings/strings.cppmap' '-fmodule-map-file=bazel-out/k8-opt/bin/external/com_google_absl/absl/strings/str_format.cppmap' -c external/com_github_grpc_grpc/src/core/lib/iomgr/buffer_list.cc -o bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/iomgr_buffer_list/buffer_list.pic.o)
# Configuration: f5138babd12d457d42947482e3ba8ba0fd4aef9b665759e4c4302475db183ebf
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_github_grpc_grpc/src/core/lib/iomgr/buffer_list.cc:21:
external/com_github_grpc_grpc/src/core/lib/iomgr/buffer_list.h:24:10: error: module @com_github_grpc_grpc//:iomgr_buffer_list does not depend on a module exporting 'absl/types/optional.h'
   24 | #include "absl/types/optional.h"
      |          ^
1 error generated.
```

**Comment by laramiel** [comment]
My patch is going to be something like this:

```
diff -Nur a/BUILD b/BUILD
--- a/BUILD	2023-05-18 16:47:46
+++ b/BUILD	2023-09-26 01:24:28
@@ -1062,6 +1062,7 @@
         "//src/core:slice_refcount",
         "//src/core:status_helper",
         "//src/core:transport_fwd",
+        "//src/core:notification",
     ],
 )
 
@@ -1767,6 +1768,7 @@
     deps = [
         "gpr",
         "grpc_trace",
+        "grpc_public_hdrs",
     ],
 )
 
@@ -2633,6 +2635,7 @@
     external_deps = [
         "absl/strings",
         "absl/strings:str_format",
+        "absl/types:optional",
     ],
     tags = ["nofixdeps"],
     visibility = ["@grpc:iomgr_buffer_list"],
diff -Nur a/src/core/BUILD b/src/core/BUILD
--- a/src/core/BUILD	2023-05-18 16:47:46
+++ b/src/core/BUILD	2023-09-25 22:42:09
@@ -2847,6 +2847,7 @@
         "//:exec_ctx",
         "//:gpr",
         "//:tsi_base",
+        "//:grpc_public_hdrs",
     ],
 )
```

**Comment by coryan** [comment]
FWIW, I am seeing similar problems when trying to build with Clang >= 16, but Clang 15.x works fine.

**Comment by laramiel** [comment]
... After updating our gRPC to v1.58.1, this additional failure appears:

```
external/com_github_grpc_grpc/src/core/ext/xds/xds_client_stats.h:41:10: error: module @com_github_grpc_grpc//:xds_client does not depend on a module exporting 'src/core/lib/resolver/server_address.h'
   41 | #include "src/core/lib/resolver/server_address.h"
      |          ^
1 error generated.
```

Which requires `:server_address`.

**Comment by laramiel** [comment]
This does not entirely fix the bug. It only includes 4 of the 6 changes that were required.
It's still missing:

diff -u -Nur a/BUILD b/BUILD
--- a/BUILD	2023-09-13 20:33:23.000000000 +0000
+++ b/BUILD	2023-10-04 01:20:07.264833917 +0000
@@ -2075,6 +2084,7 @@
     external_deps = [
         "protobuf_headers",
         "protobuf",
+        "absl/status",
     ],
     language = "c++",
     public_hdrs = [
diff -u -Nur a/src/core/BUILD b/src/core/BUILD
--- a/src/core/BUILD	2023-09-13 20:33:23.000000000 +0000
+++ b/src/core/BUILD	2023-10-04 01:16:42.015957934 +0000
@@ -3125,6 +3125,7 @@
         "//:exec_ctx",
         "//:gpr",
         "//:tsi_base",
+        "//:grpc_public_hdrs",
     ],
 )
