### ISSUE TITLE
C++ Unable to link against the version 1.11.0

### ISSUE THREAD

**Issue by TCDigi** [grpc/grpc#15359]
### What version of gRPC and what language are you using?
 1.11.0 C++
 
### What operating system (Linux, Windows, …) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual studio 2015 x64
 
### What did you do?
I compiled grpc from sources with Visual Studio 2015 (x64) and I tried to link against the libs exactly like with the previous version (1.10.0).
 
### What did you expect to see?
 My application which links against the grpc 1.11.0 compiles.
 
### What did you see instead?
Error LNK2019 unresolved external symbol "public: __cdecl grpc::ServerBuilder::~ServerBuilder(void)" (??1ServerBuilder@grpc@@qeaa@XZ) referenced in function "public: __cdecl sparte::GrpcServer::GrpcServer(class std::shared_ptr const &,class std::shared_ptr const &,class std::shared_ptr const &)" (??0GrpcServer@@@qeaa@AEBV?$shared_ptr@VConfigManager@@@@std@@aebv?$shared_ptr@VVbsUnitaryFeaturesScheduler@@@@3@AEBV?$shared_ptr@VVbsPermanentFeaturesManager@rte@@@3@@z)

Error LNK2019 unresolved external symbol "public: class std::unique_ptr<class grpc::Server,struct std::default_delete > __cdecl grpc::ServerBuilder::BuildAndStart(void)" (?BuildAndStart@ServerBuilder@grpc@@qeaa?AV?$unique_ptr@VServer@grpc@@U?$default_delete@VServer@grpc@@@std@@@std@@xz) referenced in function "public: __cdecl ::GrpcServer::GrpcServer(class std::shared_ptr const &,class std::shared_ptr const &,class std::shared_ptr const &)" (??0GrpcServer@@@qeaa@AEBV?$shared_ptr@VConfigManager@@@@std@@aebv?$shared_ptr@VVbsUnitaryFeaturesScheduler@@@@3@AEBV?$shared_ptr@VVbsPermanentFeaturesManager@rte@@@3@@z)
 
### Anything else we should know about your project / environment?
For 1.10.0, I linked with the libs below and it worked without problem.
gpr.lib
grpc_unsecure.lib
grpc++_unsecure.lib
grpc++_cronet.lib
grpc++_error_details.lib
grpc++_reflection.lib
libprotobuf.lib
libprotobuf-lite.lib
libprotoc.lib
zlibstatic.lib

It doesn't work with these libs for 1.11.0 and I tried all the others.

**Comment by nicolasnoble** [comment]
@vjpai did we change the signature on BuildAndStart by any chance ?

@TCDigi Are you sure the whole of your project has been cleaned ? I want to make sure you're not using older files by mistake. Sometimes Visual Studio can do that to you.

**Comment by TCDigi** [comment]
@nicolasnoble Yes I tried during a long time to link. To be sure, I tried again from zero : compiling grpc again from sources, link again on the right libs. I tried lots of combinations of libs (when I link against some libs I have more than the 2 errors above by the way).

**Comment by nicolasnoble** [comment]
Ugh, I know what's going on. The ServerBuilder interface managed to slide into the secure version only of the lib.

**Comment by TCDigi** [comment]
Oh ok, so is this normal or will a correction be made?

**Comment by nicolasnoble** [comment]
This isn't normal, no. We need to fix this.

**Comment by nicolasnoble** [comment]
@mehrdada this is in fact a fairly bad one.

**Comment by srini100** [comment]
@nicolasnoble @vjpai  Does this block 1.13? Previous two releases went out with this blocker so I am included to remove that label.

**Comment by TCDigi** [comment]
This compilation problem is fix in 1.13.0 ?

**Comment by vjpai** [comment]
ico is trying to reproduce it but @TCDigi : I need some more info here. v 1.11.0 was the first version where BuildAndStart was a virtual function. This is an API extension but not an API breaker. It is, however, an ABI breaker (where we don't promise compatibility anyway). You mentioned that you rebuilt gRPC from sources, but for a truly clean build, you would need to have built your application from sources as well. Otherwise your old ".obj" files will reference the old non-virtual version of BuildAndStart, which would have a different name-mangling signature from the new virtual version. FWIW, the ServerBuilder structure itself would also be fundamentally different since it would now have a vtbl that it didn't have before, so even trying to allocate a ServerBuilder wouldn't work between old obj files and a new lib.

**Comment by vjpai** [comment]
Note that @nicolasnoble's earlier comments about ServerBuilder sliding into the secure only version were not correct, so this is not (at the current time) something that we can consider a release blocker.

**Comment by TCDigi** [comment]
Actually, I rebuilt my application from sources too. I compiled grpc from sources and I compiled my application to link against the new grpc libs. I tried lots of things, like clean my application to be sure to not link against the old grpc libs. I really tried from scratch.
