### ISSUE TITLE
from grpc_tools import _protoc_compiler fails on grpcio-tools v1.0.3

### ISSUE THREAD

**Issue by oc243** [grpc/grpc#9108]
With a clean install of grpcio-tools v1.0.3 from pypi  imports that have a transitive import of `from grpc_tools import _protoc_compiler` fail:
```from grpc.tools import protoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/grpc_tools/protoc.py", line 35, in <module>
    from grpc_tools import _protoc_compiler
ImportError: cannot import name _protoc_compiler

>>> from grpc_tools import protoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/grpc_tools/protoc.py", line 35, in <module>
    from grpc_tools import _protoc_compiler
ImportError: cannot import name _protoc_compiler

>>> from grpc.tools import command
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/grpc_tools/command.py", line 35, in <module>
    from grpc_tools import protoc
  File "/usr/local/lib/python2.7/dist-packages/grpc_tools/protoc.py", line 35, in <module>
    from grpc_tools import _protoc_compiler
ImportError: cannot import name _protoc_compiler
```

I suspect this bug was introduced in fb261bf7.

**Comment by soltanmm-google** [comment]
By clean, do you mean from an empty `virtualenv`? Or are you using the system install with site-libs placed in both `/usr/local` and `/usr`?

**Comment by soltanmm-google** [comment]
A `1.0.4` patch was put out; do you still see the problem?

**Comment by oc243** [comment]
Thanks @soltanmm-google that seems to have fixed it.
