### ISSUE TITLE
error: no matching function for call to ‘StrFormat(const char [22], const char*, char [64], int32_t&, long int&, const char*&, int&)’ 

### ISSUE THREAD

**Issue by dixitsatyam** [grpc/grpc#28463]
### What version of gRPC and what language are you using?
gRPC version : v1.38.0 
Language : C++

### What operating system (Linux, Windows,...) and version?
OS: CentOS Linux 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
compiler : gcc (GCC) 5.4.0

### What did you do?
currently i'm using v1.28.1 gRPC version , but now i want to upgrade to the latest.
So i followed below steps to build gRPC :

1.git clone -b v1.38.0 https://github.com/grpc/grpc
2.cd grpc
3.git submodule update --init
4.mkdir -p cmake/build
5.cd cmake/build
6. cmake3 -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
	  -DBUILD_SHARED_LIBS=ON       \
	  -DgRPC_ABSL_PROVIDER=module   \
	  -DgRPC_CARES_PROVIDER=module    \
      -DgRPC_PROTOBUF_PROVIDER=module \
      -DgRPC_RE2_PROVIDER=module      \
      -DgRPC_SSL_PROVIDER=module      \
      -DgRPC_ZLIB_PROVIDER=module \
      -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
      ../..
(note: MY_INSTALL_DIR is set to the appropriate directory)
7 .make

### What did you expect to see?
gRPC should successfully compiled and required libs should generated (grpc/libs/opt , grpc/libs/opt/protobuf  etc)

### What did you see instead?
when i trigger make command , compilation failed after sometime
![image](https://user-images.githubusercontent.com/47394025/148037541-956e384a-45bd-4495-9ef9-14e15c02f603.png)

### Anything else we should know about your project / environment?
no

Thnaks,
Satyam Dixit.

**Comment by dixitsatyam** [comment]
@jtattermusch can you please help here.

**Comment by dixitsatyam** [comment]
this is resolved when i upgrade my gcc version to 9.3.0
