### ISSUE TITLE
make buildtests fails on MacOS

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#13414]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
HEAD
 
### What operating system (Linux, Windows, …) and version?
 MacOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
`Apple LLVM version 9.0.0 (clang-900.0.38)`
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

`make buildtests`
 
### What did you expect to see?
 Everything get built
 
### What did you see instead?
``` 
In file included from third_party/cares/cares/ares__close_sockets.c:19:
third_party/cares/cares/ares.h:373:4: error: type name requires a specifier or qualifier
   ares_ssize_t(*arecvfrom)(ares_socket_t, void *, size_t, int, struct sockaddr *, ares_socklen_t *, void *);
   ^
third_party/cares/cares/ares.h:373:18: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
   ares_ssize_t(*arecvfrom)(ares_socket_t, void *, size_t, int, struct sockaddr *, ares_socklen_t *, void *);
                 ^
third_party/cares/cares/ares.h:373:16: error: function cannot return function type 'int (ares_socket_t, void *, size_t, int, struct sockaddr *,
      ares_socklen_t *, void *)' (aka 'int (int, void *, unsigned long, int, struct sockaddr *, unsigned int *, void *)')
   ares_ssize_t(*arecvfrom)(ares_socket_t, void *, size_t, int, struct sockaddr *, ares_socklen_t *, void *);
               ^
third_party/cares/cares/ares.h:374:4: error: type name requires a specifier or qualifier
   ares_ssize_t(*asendv)(ares_socket_t, const struct iovec *, int, void *);
   ^
third_party/cares/cares/ares.h:374:18: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
   ares_ssize_t(*asendv)(ares_socket_t, const struct iovec *, int, void *);
                 ^
third_party/cares/cares/ares.h:374:16: error: function cannot return function type 'int (ares_socket_t, const struct iovec *, int, void *)' (aka
      'int (int, const struct iovec *, int, void *)')
   ares_ssize_t(*asendv)(ares_socket_t, const struct iovec *, int, void *);
               ^
third_party/cares/cares/ares.h:374:4: error: duplicate member 'ares_ssize_t'
   ares_ssize_t(*asendv)(ares_socket_t, const struct iovec *, int, void *);
   ^
third_party/cares/cares/ares.h:373:4: note: previous declaration is here
   ares_ssize_t(*arecvfrom)(ares_socket_t, void *, size_t, int, struct sockaddr *, ares_socklen_t *, void *);
   ^
7 errors generated.
```

**Comment by ncteisen** [comment]
Just bisected it to #12305

**Comment by ncteisen** [comment]
This was a local issue. I had an old version of c-ares installed on my machine. Fix was as follows:
```
cd third_party/cares/cares
./buildconf
./configure
make uninstall
```

**Comment by ericgribkoff** [comment]
I encountered same problem and this was helpful. For future viewers: it's also possible to get this error with an old c-areas that's been installed via homebrew
