### ISSUE TITLE
 error: no matching function for call to ‘StrFormat(const char [45], const double&, double, const double&, const double&)’                                 moments.skewness, moments.kurtosis)

### ISSUE THREAD

**Issue by cjhlai** [grpc/grpc#24940]
OS:CentOS Linux release 7.7.1908
gcc version: 4.8.5 
cmake version 3.19.1
 when i run 
mkdir -p cmake/build
cd cmake/build
cmake ../.. -DBUILD_SHARED_LIBS=ON -DgRPC_INSTALL=ON
make -j$(nproc)

it returns errors like these:

[ 47%] Built target absl_random_distributions
[ 47%] Building CXX object third_party/protobuf/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o
Scanning dependencies of target absl_random_internal_distribution_test_util
Scanning dependencies of target absl_status
Scanning dependencies of target absl_flags_private_handle_accessor
[ 47%] Building CXX object third_party/abseil-cpp/absl/flags/CMakeFiles/absl_flags_marshalling.dir/marshalling.cc.o
[ 47%] Built target absl_examine_stack
[ 47%] Built target absl_synchronization
Scanning dependencies of target absl_random_internal_pool_urbg
Scanning dependencies of target absl_hashtablez_sampler
[ 47%] Building CXX object third_party/abseil-cpp/absl/flags/CMakeFiles/absl_flags_private_handle_accessor.dir/internal/private_handle_accessor.cc.o
[ 47%] Building CXX object third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_distribution_test_util.dir/internal/chi_square.cc.o
[ 47%] Building CXX object third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_pool_urbg.dir/internal/pool_urbg.cc.o
[ 47%] Building CXX object third_party/abseil-cpp/absl/container/CMakeFiles/absl_hashtablez_sampler.dir/internal/hashtablez_sampler.cc.o
[ 47%] Building CXX object third_party/abseil-cpp/absl/status/CMakeFiles/absl_status.dir/status.cc.o
In file included from /data/skywalking/grpc/third_party/abseil-cpp/absl/time/internal/cctz/include/cctz/civil_time.h:19:0,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/time/civil_time.h:76,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/time/time.h:88,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/time/clock.h:26,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/synchronization/internal/kernel_timeout.h:33,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/synchronization/mutex.h:71,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/container/internal/hashtablez_sampler.h:50,
                 from /data/skywalking/grpc/third_party/abseil-cpp/absl/container/internal/hashtablez_sampler.cc:15:
/data/skywalking/grpc/third_party/abseil-cpp/absl/time/internal/cctz/include/cctz/civil_time_detail.h:26:5: warning: "__cpp_constexpr" is not defined [-Wundef]
 #if __cpp_constexpr >= 201304 || (defined(_MSC_VER) && _MSC_VER >= 1910)
     ^
[ 47%] Building CXX object CMakeFiles/grpc_plugin_support.dir/src/compiler/cpp_generator.cc.o
[ 47%] Linking CXX shared library libabsl_flags_private_handle_accessor.so
[ 47%] Building CXX object third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_distribution_test_util.dir/internal/distribution_test_util.cc.o
[ 47%] Built target absl_flags_private_handle_accessor
[ 47%] Built target absl_failure_signal_handler
[ 47%] Linking CXX shared library libabsl_random_internal_pool_urbg.so
Scanning dependencies of target absl_flags_program_name
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc: In instantiation of ‘std::string absl::lts_2020_09_23::flags_internal::UnparseFloatingPointVal(T) [with T = float; std::string = std::basic_string<char>]’:
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:193:64:   required from here
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:179:66: error: no matching function for call to ‘StrFormat(const char [5], const int&, float&)’
       absl::StrFormat("%.*g", std::numeric_limits<T>::digits10, v);
                                                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:179:66: note: candidate is:
In file included from /data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:33:0:
/data/skywalking/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:179:66: note:   mismatched types ‘absl::lts_2020_09_23::FormatSpec<Args ...>’ and ‘const char [5]’
       absl::StrFormat("%.*g", std::numeric_limits<T>::digits10, v);
                                                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:191:73: error: no matching function for call to ‘StrFormat(const char [5], const int&, float&)’
   return absl::StrFormat("%.*g", std::numeric_limits<T>::max_digits10, v);
                                                                         ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:191:73: note: candidate is:
In file included from /data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:33:0:
/data/skywalking/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:191:73: note:   mismatched types ‘absl::lts_2020_09_23::FormatSpec<Args ...>’ and ‘const char [5]’
   return absl::StrFormat("%.*g", std::numeric_limits<T>::max_digits10, v);
                                                                         ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc: In instantiation of ‘std::string absl::lts_2020_09_23::flags_internal::UnparseFloatingPointVal(T) [with T = double; std::string = std::basic_string<char>]’:
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:194:65:   required from here
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:179:66: error: no matching function for call to ‘StrFormat(const char [5], const int&, double&)’
       absl::StrFormat("%.*g", std::numeric_limits<T>::digits10, v);
                                                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:179:66: note: candidate is:
In file included from /data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:33:0:
/data/skywalking/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_2020_09_23::StrFormat(absl::lts_2020_09_23::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:179:66: note:   mismatched types ‘absl::lts_2020_09_23::FormatSpec<Args ...>’ and ‘const char [5]’
       absl::StrFormat("%.*g", std::numeric_limits<T>::digits10, v);
                                                                  ^
/data/skywalking/grpc/third_party/abseil-cpp/absl/flags/marshalling.cc:191:73: error: no matching function for call to ‘StrFormat(const char [5], const int&, double

**Comment by cjhlai** [comment]
@nicolasnoble @hassox @timburks @blowmage need your help,tks

**Comment by stanley-cheung** [comment]
you need gcc version 4.9+. https://grpc.io/docs/

**Comment by cjhlai** [comment]
> you need gcc version 4.9+. https://grpc.io/docs/

Thanks @stanley-cheung ,but when i update gcc  to 8.3.1.it return another  error:
*** Error in `php': munmap_chunk(): invalid pointer: 0x00007ff61ad535d0 ***
======= Backtrace: =========
/usr/lib64/libc.so.6(+0x7f7c4)[0x7ff627e5f7c4]
/usr/local/lib/libprotobuf.so.25(_ZNSt10_HashtableISsSt4pairIKSsN6google8protobuf25FieldDescriptorProto_TypeEESaIS5_ENSt8__detail10_Select1stESt8equal_toISsESt4hashISsENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb1ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS7_10_Hash_nodeIS5_Lb1EEE+0xc9)[0x7ff61bfe7ed9]
/usr/local/lib/libprotobuf.so.25(_ZNSt8__detail9_Map_baseISsSt4pairIKSsN6google8protobuf25FieldDescriptorProto_TypeEESaIS6_ENS_10_Select1stESt8equal_toISsESt4hashISsENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_20_Prime_rehash_policyENS_17_Hashtable_traitsILb1ELb0ELb1EEELb1EEixEOSs+0xad)[0x7ff61bfe86dd]
/usr/local/lib64/libprotobuf.so.3.13.0.0(_ZNSt13unordered_mapISsN6google8protobuf25FieldDescriptorProto_TypeESt4hashISsESt8equal_toISsESaISt4pairIKSsS2_EEEixEOSs+0x2e)[0x7ff61a85617e]
/usr/local/lib64/libprotobuf.so.3.13.0.0(+0x4176bf)[0x7ff61a8476bf]
/usr/local/lib64/libprotobuf.so.3.13.0.0(+0x421f22)[0x7ff61a851f22]
/usr/local/lib64/libprotobuf.so.3.13.0.0(+0x421f55)[0x7ff61a851f55]
/lib64/ld-linux-x86-64.so.2(+0xf973)[0x7ff62aa3b973]
/lib64/ld-linux-x86-64.so.2(+0x1454e)[0x7ff62aa4054e]
/lib64/ld-linux-x86-64.so.2(+0xf784)[0x7ff62aa3b784]
/lib64/ld-linux-x86-64.so.2(+0x13b3b)[0x7ff62aa3fb3b]
/usr/lib64/libdl.so.2(+0xeeb)[0x7ff629615eeb]
/lib64/ld-linux-x86-64.so.2(+0xf784)[0x7ff62aa3b784]
/usr/lib64/libdl.so.2(+0x14ed)[0x7ff6296164ed]
/usr/lib64/libdl.so.2(dlopen+0x31)[0x7ff629615f81]
php(php_load_shlib+0x13)[0x75d413]
php(php_load_extension+0x71)[0x75d4c1]
php(zend_llist_apply+0x1e)[0x8421fe]
php[0x7f7c8a]
php(php_module_startup+0x7b1)[0x7f0dd1]
php[0x8d319d]
php[0x44ef4f]
/usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff627e02505]
php[0x44f324]
======= Memory map: ========
00400000-00c08000 r-xp 00000000 08:03 104884109                          /usr/local/php/bin/php
00e08000-00ec2000 r--p 00808000 08:03 104884109                          /usr/local/php/bin/php
00ec2000-00ed1000 rw-p 008c2000 08:03 104884109                          /usr/local/php/bin/php
00ed1000-00ef7000 rw-p 00000000 00:00 0 
0264c000-02704000 rw-p 00000000 00:00 0                                  [heap]
7ff615a1a000-7ff615a1b000 r-xp 00000000 08:03 35705452                   /usr/local/lib/libabsl_exponential_biased.so
7ff615a1b000-7ff615c1a000 ---p 00001000 08:03 35705452                   /usr/local/lib/libabsl_exponential_biased.so
7ff615c1a000-7ff615c1b000 r--p 00000000 08:03 35705452                   /usr/local/lib/libabsl_exponential_biased.so
7ff615c1b000-7ff615c1c000 rw-p 00001000 08:03 35705452                   /usr/local/lib/libabsl_exponential_biased.so
7ff615c1c000-7ff615c1e000 r-xp 00000000 08:03 35705461                   /usr/local/lib/libabsl_spinlock_wait.so
7ff615c1e000-7ff615e1d000 ---p 00002000 08:03 35705461                   /usr/local/lib/libabsl_spinlock_wait.so
7ff615e1d000-7ff615e1e000 r--p 00001000 08:03 35705461                   /usr/local/lib/libabsl_spinlock_wait.so
7ff615e1e000-7ff615e1f000 rw-p 00002000 08:03 35705461                   /usr/local/lib/libabsl_spinlock_wait.so
7ff615e1f000-7ff615e20000 r-xp 00000000 08:03 35705457                   /usr/local/lib/libabsl_log_severity.so
7ff615e20000-7ff61601f000 ---p 00001000 08:03 35705457                   /usr/local/lib/libabsl_log_severity.so
7ff61601f000-7ff616020000 r--p 00000000 08:03 35705457                   /usr/local/lib/libabsl_log_severity.so
7ff616020000-7ff616021000 rw-p 00001000 08:03 35705457                   /usr/local/lib/libabsl_log_severity.so
7ff616021000-7ff616024000 r-xp 00000000 08:03 35705460                   /usr/local/lib/libabsl_raw_logging_internal.so
7ff616024000-7ff616223000 ---p 00003000 08:03 35705460                   /usr/local/lib/libabsl_raw_logging_internal.so
7ff616223000-7ff616224000 r--p 00002000 08:03 35705460                   /usr/local/lib/libabsl_raw_logging_internal.so
7ff616224000-7ff616225000 rw-p 00003000 08:03 35705460                   /usr/local/lib/libabsl_raw_logging_internal.so
7ff616225000-7ff61622c000 r-xp 00000000 08:03 35705446                   /usr/local/lib/libabsl_base.so
7ff61622c000-7ff61642b000 ---p 00007000 08:03 35705446                   /usr/local/lib/libabsl_base.so
7ff61642b000-7ff61642c000 r--p 00006000 08:03 35705446                   /usr/local/lib/libabsl_base.so
7ff61642c000-7ff61642d000 rw-p 00007000 08:03 35705446                   /usr/local/lib/libabsl_base.so
7ff61642d000-7ff616432000 r-xp 00000000 08:03 35705458                   /usr/local/lib/libabsl_malloc_internal.so
7ff616432000-7ff616631000 ---p 00005000 08:03 35705458                   /usr/local/lib/libabsl_malloc_internal.so
7ff616631000-7ff616632000 r--p 00004000 08:03 35705458                   /usr/local/lib/libabsl_malloc_internal.so
7ff616632000-7ff616633000 rw-p 00005000 08:03 35705458                   /usr/local/lib/libabsl_malloc_internal.so
7ff616633000-7ff616683000 r-xp 00000000 08:03 35705472                   /usr/local/lib/libabsl_time_zone.so
7ff616683000-7ff616883000 ---p 00050000 08:03 35705472                   /usr/local/lib/libabsl_time_zone.so
7ff616883000-7ff616884000 r--p 00050000 08:03 35705472                   /usr/local/lib/libabsl_time_zone.so
7ff616884000-7ff616886000 rw-p 00051000 08:03 35705472                   /usr/local/lib/libabsl_time_zone.so
7ff616886000-7ff61688a000 r-xp 00000000 08:03 35705448                   /usr/local/lib/libabsl_civil_time.so
7ff61688a000-7ff616a89000 ---p 00004000 08:03 35705448                   /usr/local/lib/libabsl_civil_time.so
7ff616a89000-7ff616a8a000 r--p 00003000 08:03 35705448                   /usr/local/lib/libabsl_civil_time.so
7ff616a8a000-7ff616a8b000 rw-p 00004000 08:03 35705448                   /usr/local/lib/libabsl_civil_time.so
7ff616a8b000-7ff616a92000 r-xp 00000000 08:03 35705456                   /usr/local/lib/libabsl_int128.so
7ff616a92000-7ff616c92000 ---p 00007000 08:03 35705456                   /usr/local/lib/libabsl_int128.so
7ff616c92000-7ff616c93000 r--p 00007000 08:03 35705456                   /usr/local/lib/libabsl_int128.so
7ff616c93000-7ff616c94000 rw-p 00008000 08:03 35705456                   /usr/local/lib/libabsl_int128.so
7ff616c94000-7ff616ca8000 r-xp 00000000 08:03 35705470                   /usr/local/lib/libabsl_throw_delegate.so
7ff616ca8000-7ff616ea7000 ---p 00014000 08:03 35705470                   /usr/local/lib/libabsl_throw_delegate.so
7ff616ea7000-7ff616ea8000 r--p 00013000 08:03 35705470                   /usr/local/lib/libabsl_throw_delegate.so
7ff616ea8000-7ff616ea9000 rw-p 00014000 08:03 35705470                   /usr/local/lib/libabsl_throw_delegate.so
7ff616ea9000-7ff616eac000 r-xp 00000000 08:03 35705467                   /usr/local/lib/libabsl_strings_internal.so
7ff616eac000-7ff6170ab000 ---p 00003000 08:03 35705467                   /usr/local/lib/libabsl_strings_internal.so
7ff6170ab000-7ff6170ac000 r--p 00002000 08:03 35705467                   /usr/local/lib/libabsl_strings_internal.so
7ff6170ac000-7ff6170ad000 rw-p 00003000 08:03 35705467                   /usr/local/lib/libabsl_strings_internal.so
7ff6170ad000-7ff6170dd000 r-xp 00000000 08:03 35705466                   /usr/local/lib/libabsl_strings.so
7ff6170dd000-7ff6172dc000 ---p 00030000 08:03 35705466                   /usr/local/lib/libabsl_strings.so
7ff6172dc000-7ff6172dd000 r--p 0002f000 08:03 35705466                   /usr/local/lib/libabsl_strings.so
7ff6172dd000-7ff6172de000 rw-p 00030000 08:03 35705466                   /usr/local/lib/libabsl_strings.so
7ff6172de000-7ff617307000 r-xp 00000000 08:03 35705471                   /usr/local/lib/libabsl_time.so
7ff617307000-7ff617506000 ---p 00029000 08:03 35705471                   /usr/local/lib/libabsl_time.so
7ff617506000-7ff617507000 r--p 00028000 08:03 35705471                   /usr/local/lib/libabsl_time.so
7ff617507000-7ff617508000 rw-p 00029000 08:03 3Aborted (core dumped)

**Comment by stanley-cheung** [comment]
I am not sure how `php` is related to this? I thought you just ran `cmake` from the root directory of the repo? How did `php` come into play?

**Comment by screamingliu** [comment]
> you need gcc version 4.9+. https://grpc.io/docs/

gcc 4.9+ could really solve the problem, But I'm wondring about how this compile error corresponding with gcc version? absl:forMat didn't change from Last version 20200225， Last version20200225 we don't got this problem. Could do pls teach me? thank You so much.

**Comment by syslogic** [comment]
Also experiencing a similar issue (the error message brought me here). And how PHP is related is because PECL modules are being built against `php-devel` (as the documentation for Cloud Logging reads: `pecl install grpc
`). I'm on CentOS 8.x with GCC 4.8.5 and get the following stacktrace:

```
running: make
/bin/sh /var/tmp/pear-build-rootoceaBj/grpc-1.39.0/libtool --mode=compile g++ -I. -I/var/tmp/grpc -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/include -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/main -I/var/tmp/grpc -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/var/tmp/grpc/include -I/var/tmp/grpc/src/core/ext/upb-generated -I/var/tmp/grpc/src/core/ext/upbdefs-generated -I/var/tmp/grpc/src/php/ext/grpc -I/var/tmp/grpc/third_party/abseil-cpp -I/var/tmp/grpc/third_party/address_sorting/include -I/var/tmp/grpc/third_party/boringssl-with-bazel/src/include -I/var/tmp/grpc/third_party/re2 -I/var/tmp/grpc/third_party/upb -I/var/tmp/grpc/third_party/xxhash  -DHAVE_CONFIG_H  -std=c++11 -fno-exceptions -fno-rtti -g -O2   -fvisibility=hidden     -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0     -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1     -DGRPC_XDS_USER_AGENT_N
AME_SUFFIX='"PHP"'     -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX='"1.39.0"' -c /var/tmp/grpc/src/core/ext/filters/census/grpc_context.cc -o src/core/ext/filters/census/grpc_context.lo
libtool: compile:  g++ -I. -I/var/tmp/grpc -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/include -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/main -I/var/tmp/grpc -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/var/tmp/grpc/include -I/var/tmp/grpc/src/core/ext/upb-generated -I/var/tmp/grpc/src/core/ext/upbdefs-generated -I/var/tmp/grpc/src/php/ext/grpc -I/var/tmp/grpc/third_party/abseil-cpp -I/var/tmp/grpc/third_party/address_sorting/include -I/var/tmp/grpc/third_party/boringssl-with-bazel/src/include -I/var/tmp/grpc/third_party/re2 -I/var/tmp/grpc/third_party/upb -I/var/tmp/grpc/third_party/xxhash -DHAVE_CONFIG_H -std=c++11 -fno-exceptions -fno-rtti -g -O2 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"PHP\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.39.0\" -c /var/
tmp/grpc/src/core/ext/filters/census/grpc_context.cc  -fPIC -DPIC -o src/core/ext/filters/census/.libs/grpc_context.o
/bin/sh /var/tmp/pear-build-rootoceaBj/grpc-1.39.0/libtool --mode=compile g++ -I. -I/var/tmp/grpc -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/include -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/main -I/var/tmp/grpc -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/var/tmp/grpc/include -I/var/tmp/grpc/src/core/ext/upb-generated -I/var/tmp/grpc/src/core/ext/upbdefs-generated -I/var/tmp/grpc/src/php/ext/grpc -I/var/tmp/grpc/third_party/abseil-cpp -I/var/tmp/grpc/third_party/address_sorting/include -I/var/tmp/grpc/third_party/boringssl-with-bazel/src/include -I/var/tmp/grpc/third_party/re2 -I/var/tmp/grpc/third_party/upb -I/var/tmp/grpc/third_party/xxhash  -DHAVE_CONFIG_H  -std=c++11 -fno-exceptions -fno-rtti -g -O2   -fvisibility=hidden     -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0     -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1     -DGRPC_XDS_USER_AGENT_N
AME_SUFFIX='"PHP"'     -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX='"1.39.0"' -c /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.cc -o src/core/ext/filters/client_channel/backend_metric.lo
libtool: compile:  g++ -I. -I/var/tmp/grpc -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/include -I/var/tmp/pear-build-rootoceaBj/grpc-1.39.0/main -I/var/tmp/grpc -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/var/tmp/grpc/include -I/var/tmp/grpc/src/core/ext/upb-generated -I/var/tmp/grpc/src/core/ext/upbdefs-generated -I/var/tmp/grpc/src/php/ext/grpc -I/var/tmp/grpc/third_party/abseil-cpp -I/var/tmp/grpc/third_party/address_sorting/include -I/var/tmp/grpc/third_party/boringssl-with-bazel/src/include -I/var/tmp/grpc/third_party/re2 -I/var/tmp/grpc/third_party/upb -I/var/tmp/grpc/third_party/xxhash -DHAVE_CONFIG_H -std=c++11 -fno-exceptions -fno-rtti -g -O2 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"PHP\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.39.0\" -c /var/
tmp/grpc/src/core/ext/filters/client_channel/backend_metric.cc  -fPIC -DPIC -o src/core/ext/filters/client_channel/.libs/backend_metric.o
In file included from /var/tmp/grpc/src/core/ext/filters/client_channel/lb_policy.h:30:0,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.h:24,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.cc:19:
/var/tmp/grpc/src/core/ext/filters/client_channel/server_address.h: In member function 'virtual std::string grpc_core::ServerAddressWeightAttribute::ToString() const':
/var/tmp/grpc/src/core/ext/filters/client_channel/server_address.h:135:41: error: no matching function for call to 'StrFormat(const char [3], const uint32_t&)'
     return absl::StrFormat("%d", weight_);
                                         ^
/var/tmp/grpc/src/core/ext/filters/client_channel/server_address.h:135:41: note: candidate is:
In file included from /var/tmp/grpc/src/core/ext/filters/client_channel/server_address.h:28:0,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/lb_policy.h:30,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.h:24,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.cc:19:
/var/tmp/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_20210324::StrFormat(absl::lts_20210324::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
/var/tmp/grpc/third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
In file included from /var/tmp/grpc/src/core/ext/filters/client_channel/lb_policy.h:30:0,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.h:24,
                 from /var/tmp/grpc/src/core/ext/filters/client_channel/backend_metric.cc:19:
/var/tmp/grpc/src/core/ext/filters/client_channel/server_address.h:135:41: note:   mismatched types 'absl::lts_20210324::FormatSpec<Args ...>' and 'const char [3]'
     return absl::StrFormat("%d", weight_);
                                         ^
make: *** [src/core/ext/filters/client_channel/backend_metric.lo] Error 1
ERROR: `make' failed


```

**Comment by Peterisfar** [comment]
> you need gcc version 4.9+. https://grpc.io/docs/

my gcc version is 4.9.3, the bug still have

**Comment by Simoyd** [comment]
for other people who find this issue on google:
v1.33.2 compiles fine with gcc 4.8.5
v1.34.0 causes the `no matching function call` error outlined above

I myself need to support older platforms so 1.33.2 for me it is!

**Comment by dixitsatyam** [comment]
i have gcc 5.4.0 but still i'm getting compilation error.
![image](https://user-images.githubusercontent.com/47394025/146717798-519f44c5-193f-44a6-8bcf-5a6910b91e9e.png)

**Comment by dixitsatyam** [comment]
above error is comming for every release after v1.33.2 grpc release.
Following steps i followed to trigger build (example for v1.38.0 release):
git clone -b v1.38.0 https://github.com/grpc/grpc
cd grpc
git submodule update --init
mkdir -p cmake/build
cd cmake/build
cmake3 ../..
make

**Comment by dixitsatyam** [comment]
> > you need gcc version 4.9+. https://grpc.io/docs/
> 
> my gcc version is 4.9.3, the bug still have

@Peterisfar .. i'm also getting same bug , did you find the way to resolve this.
