### ISSUE TITLE
grpc 0.13.0 compile with gcc-4.4.7 fails on CentOS release 6.6

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc#6038]
The compile fails for me at:
```
[...]
[C]       Compiling src/core/channel/channel_stack.c
cc1: warnings being treated as errors
src/core/channel/channel_stack.c: In function 'grpc_channel_stack_element':
src/core/channel/channel_stack.c:90: error: declaration of 'index' shadows a global declaration
/usr/include/string.h:489: error: shadowed declaration is here
src/core/channel/channel_stack.c: In function 'grpc_call_stack_element':
src/core/channel/channel_stack.c:100: error: declaration of 'index' shadows a global declaration
/usr/include/string.h:489: error: shadowed declaration is here
```

**Comment by vjpai** [comment]
Closing this out as it was fixed earlier but not marked as such.
