### ISSUE TITLE
python client memory leak when using streaming API

### ISSUE THREAD

**Issue by d0m3nik** [grpc/grpc#12383]
### What version of gRPC and what language are you using?
 Latest gRPC version 1.4.x built from sources. Languages used: python, C++.
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu Linux 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.5.2
 
### What did you do?
Create a simple C++ server for streaming random numbers. The C++ client does not leak memory but the python client does. Example code and more details can be found in [grpc_memleak](https://github.com/d0m3nik/grpc_memleak)
 
### What did you expect to see?
The python client should not leak memory.
 
### What did you see instead?
Python client leaks memory. After some time the python interpreter raises a MemoryError.

**Comment by nicolasnoble** [comment]
Garbage collection issue ?

**Comment by nathanielmanistaatgoogle** [comment]
I don't understand "Latest gRPC version 1.4.x built from sources" - [isn't 1.7.x the latest in source](https://github.com/grpc/grpc/blob/31a4ebeded8574ba8aa42c64ebcf5a8e54a21046/src/python/grpcio/grpc_version.py#L17)?

How long is "some time"? Are you able to decrease that time by making changes to your code? What kinds of changes?

**Comment by d0m3nik** [comment]
"curl -L https://grpc.io/release" yields 1.4.x as the current version (https://github.com/grpc/grpc/blob/master/INSTALL.md). 

Trying to build the 1.6.x branch fails on Ubuntu 16.04 with gcc version 5.4.0:

src/compiler/php_generator.cc:154:39: error: ‘const class google::protobuf::FileOptions’ has no member named ‘php_namespace’

"Some time" is about 3 hours on an old laptop with 4GB RAM. This can be reduced to 4 minutes by restricting the physical and virtual memory to 100MB for the python client with cgroup (https://unix.stackexchange.com/questions/44985/limit-memory-usage-for-a-single-linux-process)

**Comment by nathanielmanistaatgoogle** [comment]
Since you're building from source: are you able to patch in [pull request 12249](https://github.com/grpc/grpc/pull/12249)? If so, does it have any effect on the leak you observe?

**Comment by mehrdada** [comment]
@d0m3nik We had forgotten to update `/release` version and it had slipped behind the actual latest version. It is now updated to 1.6.x.

**Comment by d0m3nik** [comment]
I cherry-picked c5e6cefc8d95031983e8dbfd8ece370ac618cc9d from pull request #12249 into branch 1.4.x, but I still observe the leak.

**Comment by djanku** [comment]
@d0m3nik Are you sure that you are really using patched version? Any output from valgrind/leaks?

**Comment by nathanielmanistaatgoogle** [comment]
@d0m3nik: please definitely stop working with `1.4.x`; work either with `master` or `1.6.x`.

**Comment by d0m3nik** [comment]
I rebuilt the example and reinstalled grpcio with:
1) grpc branch `1.6.x` with patch c5e6cefc8d95031983e8dbfd8ece370ac618cc9d from https://github.com/grpc
2) grpc branch `master` from https://github.com/djanku/grpc

In both versions the memory leak is still present.

**Comment by nathanielmanistaatgoogle** [comment]
@d0m3nik: thanks! And is that most recent finding with or without [pull request 12249](https://github.com/grpc/grpc/pull/12249) patched in?

**Comment by d0m3nik** [comment]
@nathanielmanistaatgoogle I just double checked: the changes from pull request #12249 = c5e6cefc8d95031983e8dbfd8ece370ac618cc9d were correctly patched into branch ` 1.6.x`

**Comment by nathanielmanistaatgoogle** [comment]
@d0m3nik: ahh, I should have seen that, but thank you for confirming.

**Comment by nathanielmanistaatgoogle** [comment]
I'm still not able to reproduce this.

Have you worked any further with it? Are you able to reproduce it with different Python versions like 2.7 and 3.6?

Thank you for the thorough reproduction instructions, but are you able to reduce them even further? Something that's really practical about our [examples](https://grpc.io/docs/quickstart/python.html) is that they fit inside a Python virtual environment - not that I don't love installing various versions of Protocol Buffers all over again, but are you able to simplify the leak set-up to `my_virtualenv/bin/pip install --upgrade grpcio`?

**Comment by nathanielmanistaatgoogle** [comment]
It would be quite surprising if the leak had anything to do with the serialization and deserialization performed by the `_pb2` module, so it would be simplifying to see that stripped away.

**Comment by parachutepy** [comment]
Has there been any resolution on the memory leaks wrt python streaming api? We continue to face this issue with grpcio==1.8.3. Can someone throw some light on this? 

A sample repo that we stumbled across when looking for info - https://github.com/d0m3nik/grpc_memleak

**Comment by nathanielmanistaatgoogle** [comment]
There have definitely been leak fixes since 1.8.3 - do you see any improvement if you work with [`grpcio` 1.10.0](https://pypi.python.org/pypi/grpcio/1.10.0)?

**Comment by nathanielmanistaatgoogle** [comment]
@parachutepy: my immediate thought is "take gRPC out of the problem". While gRPC and Protocol Buffers are intended for use with one another, they are separable, and in the course of investigating a bug it's definitely worth separating them. You say "the memory used to convert the 2MB protobuf message to python dict is around 500 MB when using the google.protobuf.json_format.MessageToDict" - do you need gRPC operating across the network for that to happen or is that a thing that you can get to happen when you construct that message in memory or load it from a file?

**Comment by parachutepy** [comment]
@nathanielmanistaatgoogle We did try to remove gRPC and use an intermediary file to hold the json/dict's, the memory usage comes down drastically(150-200MB). But the time for the file creation operation is around 6 minutes. 

Just to add a little background might help : We are trying to process data from a streaming gRPC api in an AWS Lambda fucntion. So  there is time constraint of 5 minutes and memory constraint of 3GB. So we are trying to get the best approach to solve this issue. Again, thanks for your response!

**Comment by nathanielmanistaatgoogle** [comment]
@parachutepy: since your scenario seems to involve greater-than-expected memory use rather than a leak of memory [I've broken it out into a separate issue](https://github.com/grpc/grpc/issues/14595). Let's continue our discussion there.

@d0m3nik: any update from your side? Are you still affected by this issue? Were you able to strip out the Protocol Buffers serialization and deserialization?

**Comment by srini100** [comment]
Removing proto serialization/deserialization has no affect. Memory is recovered if the streaming RPC is closed.

**Comment by srini100** [comment]
This issue is due to a bug in flow control logic (being fixed in #14747) in C-core because of which memory on receiving side can grow unbounded if the application is consuming the stream slower than it is received on the wire. The memory is freed when RPC terminates.  Due to this issue, you will see a sawtooth like pattern where memory usage grows with each streaming RPC until it terminates.

**Comment by srini100** [comment]
Fixed by #14747
