### PR TITLE
xds-k8s: Fix regression with returning multiple test servers

### PR DESCRIPTION
**Pull request by sergiitk**
Regression introduced in #26759 broke PSM Security tests:

```
Traceback (most recent call last):
  File "/tmpfs/src/github/grpc/tools/run_tests/xds_k8s_test_driver/tests/baseline_test.py", line 48, in test_traffic_director_grpc_setup
    test_server: _XdsTestServer = self.startTestServer()
  File "/tmpfs/src/github/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_k8s_testcase.py", line 321, in startTestServer
    test_server.set_xds_address(self.server_xds_host, self.server_xds_port)
AttributeError: 'list' object has no attribute 'set_xds_address'
```

https://source.cloud.google.com/results/invocations/5e777a0a-8786-4b49-b316-4dccf278f20a

### CODE REVIEW

**Comment by sergiitk** [comment]
Testing the fix: https://source.cloud.google.com/results/invocations/2e02e195-459b-4fc4-9588-3923f280e353

**Review by lidizheng — APPROVED** [review]
Thanks for the fix. My bad, I should have validate the change with the security Kokoro jobs as well.
