### PR TITLE
[Security] Restrict to OpenSSL 1.1.1 instead of 1.1.0

### PR DESCRIPTION
**Pull request by gtcooke94**
OpenSSL 1.1.1 is the version of importance, not 1.1.0 - fix this error causing a compilation issue with a build with OpenSSL 1.1.0g

### CODE REVIEW

**Review by aadikapur — APPROVED** [review]

File: src/core/tsi/ssl_transport_security.cc [hunk 1]
```diff
@@ -586,14 +586,14 @@ static void verified_root_cert_free(void* /*parent*/, void* ptr,
 }
 
 static void init_openssl(void) {
-#if OPENSSL_VERSION_NUMBER >= 0x10100000
+#if OPENSSL_VERSION_NUMBER >= 0x10101000L
   OPENSSL_init_ssl(OPENSSL_INIT_NO_ATEXIT, nullptr);
 #else
   SSL_library_init();
```
Comment (aadikapur) [inline src/core/tsi/ssl_transport_security.cc:592]: OPENSSL_init_ssl() was introduced in 1.1.0. Would this be equivalent to that or do we need to initialize with OPENSSL_init_ssl() in 1.1.0?

Comment (gtcooke94) [reply src/core/tsi/ssl_transport_security.cc:592]: It's an interesting question - realistically, I don't think we should support anything specifically OpenSSL1.1.0 - that adds a lot of complication. BoringSSL is forked off OpenSSL1.1.1, and we support OpenSSL 1.0.2, 1.1.1, and 3

1.1.0 is overall an odd version - I think we should consider fixing our CI so that it's either using 1.0.2 or 1.1.1

File: src/core/tsi/ssl_transport_security.cc
Comment (aadikapur) [inline src/core/tsi/ssl_transport_security.cc]: This should be changed to version 0x10101000L as well.

distrib tests are failing because g_openssl_mutexes are only defined for < 0x10100000.
```
T:\altsrc\github\grpc\workspace_cpp_windows_x86_cmake_as_externalproject\src\core\tsi\ssl_transport_security.cc(600,5): error C2065: 'g_openssl_mutexes': undeclared identifier [T:\altsrc\github\grpc\workspace_cpp_windows_x86_cmake_as_externalproject\example_build\grpc\src\grpc-build\grpc.vcxproj]
```

**Review by aadikapur — CHANGES_REQUESTED** [review]

**Review by aadikapur — APPROVED** [review]

**Review by ananda1066 — APPROVED** [review]
