### PR TITLE
Fix modulemap redefinition problem in Xcode 8.3

### LINKED ISSUE #10355: redefinition of module "openssl", swift project won't compiles in xcode 8.3
Hi, we have a production swift project used to be working in xcode 8.2 won't compile in xcode 8.3, which failed with: redefinition of module 'openssl'. 

Configuration stay untouched for months, hope it would be silly problem.

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

target 'flash' do
    pod 'Alamofire', '~> 4.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'BugfenderSDK', '~> 0.3.24'
    pod 'SDWebImage', '~> 3.8'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'SentrySwift'
    pod 'SwiftyJSON'
    pod 'FlashService', :path => "./FlashService"
end

target 'flashTests' do
end

target 'flashUITests' do
end
```

FlashService.podspec
```
Pod::Spec.new do |s|
  s.name     = 'FlashService'
  s.version  = '2.9.0.04'
  s.license  = 'MIT'
  s.authors  = { 'hosopy' => 'dev.hosopy@gmail.com' }
  s.homepage = 'https://github.com/hosopy'
  s.summary = 'gRPC test client'
  s.source = { :git => 'https://bitbucket.org/xxx/proto'}

  s.ios.deployment_target = '7.1'
  s.osx.deployment_target = '10.9'

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.2.0"

  # Pods directory corresponding to this app's Podfile, relative to the location of this podspec.
  pods_root = '../Pods'

  # Path where Cocoapods downloads protoc and the gRPC plugin.
  protoc_dir = "#{pods_root}/!ProtoCompiler"
  protoc = "#{protoc_dir}/protoc"
  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

  s.prepare_command = <<-CMD
    #{protoc} \
        --plugin=protoc-gen-grpc=#{plugin} \
        --objc_out=. \
        --grpc_out=. \
        -I . \
        -I #{protoc_dir} \
        -I ../../proto \
        ../../proto/*.proto
  CMD

  s.subspec 'Messages' do |ms|
    ms.source_files = '*.pbobjc.{h,m}'
    ms.header_mappings_dir = '.'
    ms.requires_arc = false
    ms.dependency 'Protobuf'
  end

  s.subspec 'Services' do |ss|
    ss.source_files = '*.pbrpc.{h,m}'
    ss.header_mappings_dir = '.'
    ss.requires_arc = true
    ss.dependency 'gRPC-ProtoRPC'
    ss.dependency "#{s.name}/Messages"
  end

  s.pod_target_xcconfig = {
      # This is needed by all pods that depend on Protobuf:
      'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
      # This is needed by all pods that depend on gRPC-RxLibrary:
      'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  }
end
```

### PR DESCRIPTION
**Pull request by muxi**
Workaround to an Xcode 8.3 known issue that makes the error "redefinition of module openssl" (refer to #10355). Renaming the modulemap file to something other than module.modulemap 

Fixes #10355

### CODE REVIEW

**Comment by muxi** [comment]
Failed test:
gRPC_interop_pull_requests - #10614

**Comment by jcanizales** [comment]
@muxi and @makdharma  As a general rule when making changes and when reviewing them: When code is deleted, use git blame to find out why was it there in the first place. In this case, git blame says https://github.com/grpc/grpc/commit/ccb184068d21758f905ecc3bfd42a2f9626dd5ee, from PR https://github.com/grpc/grpc/pull/7264 which fixed bug https://github.com/grpc/grpc/issues/7262. I expect that bug is now alive again.
