### ISSUE TITLE
nanopb in Release 0.14.1

### ISSUE THREAD

**Issue by zuyu** [grpc/grpc#6600]
I am working on [installing the release 0.14.1 using `brew`](https://github.com/zuyu/homebrew-grpc/commit/4a4be265f7537c17d02be569b1ef8ac3fd220845), and encountered some build errors regarding `nanopb`:

```
==> Downloading https://github.com/grpc/grpc/archive/release-0_14_1.tar.gz
Already downloaded: /Library/Caches/Homebrew/grpc-0.14.1.tar.gz
==> make install prefix=/usr/local/Cellar/grpc/0.14.1
Last 15 lines from /Users/zzhang/Library/Logs/Homebrew/grpc/01.make:
make: *** Waiting for unfinished jobs....
[C]       Compiling src/core/ext/lb_policy/grpclb/proto/grpc/lb/v0/load_balancer.pb.c
In file included from src/core/ext/lb_policy/grpclb/load_balancer_api.c:34:
In file included from ./src/core/ext/lb_policy/grpclb/load_balancer_api.h:40:
./src/core/ext/lb_policy/grpclb/proto/grpc/lb/v0/load_balancer.pb.h:38:10: fatal error: 'third_party/nanopb/pb.h' file not found
#include "third_party/nanopb/pb.h"
         ^
1 error generated.
make: *** [/private/tmp/grpc-20160515-59014-1oprmd3/grpc-release-0_14_1/objs/opt/src/core/ext/lb_policy/grpclb/load_balancer_api.o] Error 1
In file included from src/core/ext/lb_policy/grpclb/proto/grpc/lb/v0/load_balancer.pb.c:36:
./src/core/ext/lb_policy/grpclb/proto/grpc/lb/v0/load_balancer.pb.h:38:10: fatal error: 'third_party/nanopb/pb.h' file not found
#include "third_party/nanopb/pb.h"
         ^
1 error generated.
make: *** [/private/tmp/grpc-20160515-59014-1oprmd3/grpc-release-0_14_1/objs/opt/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v0/load_balancer.pb.o] Error 1
```

One fix could be to include the whole source code of `nanopb` under `third_party/nanopb` within the [release tarball file](https://github.com/zuyu/grpc/releases/download/release-0_14_1/release-0_14_1-w-nanopb.tar.gz).

Note that pre-installing `nanopb-generator` does not help, as the [`brew` formula](https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/nanopb-generator.rb) does  not install any headers, but also depends on `protobuf`, which would introduce system conflicts with `protbuf-3-beta` used in `grpc`.

This issue is also related to #6083.
