### ISSUE TITLE
Failure when build grpc from source

### ISSUE THREAD

**Issue by jeanphorn** [grpc/grpc#12589]
Anyone help? Thx!

env: centos6.5 x64 
I have installed clang with version clang-3.4.2-4.el6.x86_64
```
[C]       Compiling third_party/boringssl/crypto/aes/key_wrap.c
In file included from third_party/boringssl/crypto/aes/key_wrap.c:56:
third_party/boringssl/crypto/aes/../internal.h:123:22: error: stdalign.h: No such file or directory
```

**Comment by jeanphorn** [comment]
when I upgrade gcc to 4.8, it solved.
