### PR TITLE
[Python] Fix -Werror=unused-result error triggered by Cythonized code

### LINKED ISSUE #43308: [Python] `-Werror=unused-result` triggered by Cythonized code
### What version of gRPC and what language are you using?

The one TensorFlow downloads, but issues exists on current master, see below

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC 14.3

### What did you do?

Compile TensorFlow which adds `-Werror=unused-result`

Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you expect to see?

No warnings/errors.

### What did you see instead?

Compilation failed with 

```
bazel-out/k8-opt/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp:78264:15: error: ignoring return value of 'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
78264 |   (void)(write(__pyx_v_fd, __pyx_k_1, 1));
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Anything else we should know about your project / environment?

The issue is at https://github.com/grpc/grpc/blob/76b0613cc8f5422e071dccb7f06cb1c4767d76d5/src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi#L31

The result of `write` must be checked or at least stored and that discarded. The most sensible approach would be to check for `-1`
See also https://github.com/cython/cython/issues/7934

### PR DESCRIPTION
**Pull request by asheshvidyut**
# Description

Fixes #43308

When we pass `-Werror=unused-result`, during building `cygrpc.so`, Cython code errors out with following stack trace - 

```
ERROR: ~/cython/BUILD.bazel:25:12: Compiling src/python/grpcio/grpc/_cython/cygrpc.cpp failed: (Exit 1): clang failed: error executing CppCompile command (from target //src/python/grpcio/grpc/_cython:cygrpc.so) /usr/lib/llvm-19/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 ... (remaining 140 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
bazel-out/k8-opt/bin/src/python/grpcio/grpc/_cython/cygrpc.cpp:1297:9: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
 1297 |         write(fd, "1", 1);
      |         ^~~~~ ~~~~~~~~~~
1 error generated.
```

# Testing

## Manual

On linux machine below command fails on main branch but passes on this branch

```
bazel build -c opt \
  --copt="-Werror=unused-result" \
  --cxxopt="-Werror=unused-result" \
  //src/python/grpcio/grpc/_cython:cygrpc.so
```

### CODE REVIEW

File: src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi [hunk 1]
```diff
@@ -28,7 +28,10 @@ cdef extern from *:
     #ifdef _WIN32
         send((SOCKET)fd, "1", 1, 0);
     #else
-        write(fd, "1", 1);
+        // Discard the return value via a variable to satisfy
+        // __attribute__((warn_unused_result)) under -Werror=unused-result.
+        ssize_t rc = write(fd, "1", 1);
```
Comment (sergiitk) [inline src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi:33]: (improvement) I noticed Cython emits `warning: src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi:38:42: Declarations should not be declared inline.` (introduced in #41400).

I suggest moving `inline` to the embedded C definition (`static inline void`) in a follow-up PR:

```diff
diff --git a/src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi b/src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi
index d50702565d..3c07ad79b5 100644
--- a/src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi
+++ b/src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pxd.pxi
@@ -24,7 +24,7 @@ cdef extern from *:
     #include <unistd.h>
     #endif

-    static void _unified_socket_write_impl(int fd) {
+    static inline void _unified_socket_write_impl(int fd) {
     #ifdef _WIN32
         send((SOCKET)fd, "1", 1, 0);
     #else
@@ -35,7 +35,7 @@ cdef extern from *:
     #endif
     }
     """
-    inline void _unified_socket_write_impl(int fd) nogil
+    void _unified_socket_write_impl(int fd) nogil


 cdef void _unified_socket_write(int fd) noexcept nogil
```

**Review by sergiitk — APPROVED** [review]
