### ISSUE TITLE
C++ Interop server doesn't build with Protobuf 3.0.0-beta-4

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#7479]
From Travis run https://travis-ci.org/grpc/grpc/jobs/145978781 of PR updating the protobuf submodule https://github.com/grpc/grpc/pull/7475 :

```
[PROTOC]  Generating protobuf CC file from src/proto/grpc/testing/empty.proto
[CXX]     Compiling /Users/travis/build/grpc/grpc/gens/src/proto/grpc/testing/empty.pb.cc
In file included from /Users/travis/build/grpc/grpc/gens/src/proto/grpc/testing/empty.pb.cc:13:
third_party/protobuf/src/google/protobuf/wire_format_lite_inl.h:352:17: error: comparison of integers of different signs: 'const uint32' (aka 'const unsigned int') and 'int' [-Werror,-Wsign-compare]
  if (new_bytes != length) return false;
      ~~~~~~~~~ ^  ~~~~~~
third_party/protobuf/src/google/protobuf/wire_format_lite_inl.h:415:1: note: in instantiation of function template specialization 'google::protobuf::internal::WireFormatLite::ReadPackedFixedSizePrimitive<unsigned int, google::protobuf::internal::WireFormatLite::FieldType::TYPE_FIXED32>' requested here
READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE(uint32, TYPE_FIXED32)
^
third_party/protobuf/src/google/protobuf/wire_format_lite_inl.h:411:10: note: expanded from macro 'READ_REPEATED_PACKED_FIXED_SIZE_PRIMITIVE'
  return ReadPackedFixedSizePrimitive<                                         \
         ^
```

**Comment by yang-g** [comment]
This seems like a protobuf issue. I just created https://github.com/google/protobuf/issues/1813

**Comment by jcanizales** [comment]
It's solved in Protobuf 3.0.0 GA.
