### ISSUE TITLE
undefined reference to absl

### ISSUE THREAD

**Issue by chxdeng** [grpc/grpc#33401]
### What version of gRPC and what language are you using?
C++ grpc 1.55.1

### What operating system (Linux, Windows,...) and versionLinux/?
Linux/Ubuntu

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc/g++

### What did you do?

Build static grpc libraries as below

```
cmake ../../ -DgRPC_INSTALL=ON   -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DgRPC_SSL_PROVIDER=/usr/local/lib -DgRPC_ZLIB_PROVIDER=/usr/lib/x86_64-linux-gnu -DgRPC_RE2_PROVIDER=/usr/lib/x86_64-linux-gnu -DgRPC_CARES_PROVIDER=/usr/lib/x86_64-linux-gnu -DCMAKE_CXX_STANDARD=17 -DABSL_PROPAGATE_CXX_STD=ON
```

Then linking my program with the static grpc libs.

```
-L/usr/local/lib `pkg-config --libs grpc++` -L/usr/local/lib -lprotobuf
```

### What did you expect to see?

No linking error

### What did you see instead?

When linking my program with static grpc library, seeing error below
/usr/bin/ld: text_format.cc:(.text._ZN6google8protobuf10TextFormat6Parser10ParserImpl9SkipFieldEv[_ZN6google8protobuf10TextFormat6Parser10ParserImpl9SkipFieldEv]+0x957): undefined reference to `absl::lts_20230125::log_internal::LogMessage::~LogMessage()'
/usr/bin/ld: /usr/local/lib/libprotobuf.a(text_format.cc.o): in function `google::protobuf::TextFormat::Parser::ParserImpl::ConsumeFieldValue(google::protobuf::Message*, google::protobuf::Reflection const*, google::protobuf::FieldDescriptor const*)':
text_format.cc:(.text._ZN6google8protobuf10TextFormat6Parser10ParserImpl17ConsumeFieldValueEPNS0_7MessageEPKNS0_10ReflectionEPKNS0_15FieldDescriptorE[_ZN6google8protobuf10TextFormat6Parser10ParserImpl17ConsumeFieldValueEPNS0_7MessageEPKNS0_10ReflectionEPKNS0_15FieldDescriptorE]+0x175c): undefined reference to `absl::lts_20230125::log_internal::LogMessageFatal::LogMessageFatal(char const*, int)'
/usr/bin/ld: text_format.cc:(.text._ZN6google8protobuf10TextFormat6Parser10ParserImpl17ConsumeFieldValueEPNS0_7MessageEPKNS0_10ReflectionEPKNS0_15FieldDescriptorE[_ZN6google8protobuf10TextFormat6Parser10ParserImpl17ConsumeFieldValueEPNS0_7MessageEPKNS0_10ReflectionEPKNS0_15FieldDescriptorE]+0x1773): undefined reference to `absl::lts_20230125::log_internal::LogMessageFatal::~LogMessageFatal()'
/usr/bin/ld: /usr/local/lib/libprotobuf.a(text_format.cc.o): in function `google::protobuf::TextFormat::Parser::ParserImpl::ConsumeField(google::protobuf::Message*)':
text_format.cc:(.text._ZN6google8protobuf10TextFormat6Parser10ParserImpl12ConsumeFieldEPNS0_7MessageE[_ZN6google8protobuf10TextFormat6Parser10ParserImpl12ConsumeFieldEPNS0_7MessageE]+0x1869): undefined reference to `absl::lts_20230125::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, std::basic_string_view<char, std::char_traits<char> >)'
/usr/bin/ld: text_format.cc:(.text._ZN6google8protobuf10TextFormat6Parser10ParserImpl12ConsumeFieldEPNS0_7MessageE[_ZN6google8protobuf10TextFormat6Parser10ParserImpl12ConsumeFieldEPNS0_7MessageE]+0x1871): undefined reference to `absl::lts_20230125::log_internal::LogMessageFatal::~LogMessageFatal()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:29: my_program] Error 1

It worked fine with version 1.53.1 and 1.54.2.

### Anything else we should know about your project / environment?

It worked fine with version 1.53.1 and 1.54.2.

**Comment by veblush** [comment]
Would you share what version of abseil and protobuf you used when building this?

**Comment by veblush** [comment]
I suggest using the same version of those that gRPC 1.55.x used. Check [third_party](https://github.com/grpc/grpc/tree/v1.55.x/third_party) directory.

**Comment by chxdeng** [comment]
> I suggest using the same version of those that gRPC 1.55.x used. Check [third_party](https://github.com/grpc/grpc/tree/v1.55.x/third_party) directory.

Please see the cmake command I posted. In the cmake command, I am not specifying abseil lib. The build will use the abeil in third_party directory. And as I mentioned, the same build process worked fine in 1.54.1 and earlier versions.

**Comment by 3699394** [comment]
having the same issue, but we can add the static libs from abseil manually

**Comment by harsh-im** [comment]
@chxdeng Hey, I am facing similar problem, have you found out any solution?

**Comment by chxdeng** [comment]
You can manually add the libraries when compiling your code as pointed out
by the previous post.

**Comment by harsh-im** [comment]
@chxdeng previous post?

**Comment by mehrshad-kh** [comment]
I'm facing the same problem. @3699394, could you explain how to add the static libraries?

**Comment by mehrshad-kh** [comment]
I modified my CMakeLists.txt file according to [this][1] answer on Stack Overflow. No such problems anymore.

[1]: https://stackoverflow.com/a/68133837/12660318

**Comment by mehrshad-kh** [comment]
Following my previous comment, see [here][1] for an explanation.
I believe the issue can now be closed.

[1]: https://stackoverflow.com/a/76940745/12660318
