### PR TITLE
Fix compatibility for MSVC 19.32. (`fatal error C1001: Internal compiler error`)

### LINKED ISSUE #30458: Unable to build with MSVC 19.32 with `/std:latest` and `/Zc:__cplusplus` : `fatal error C1001: Internal compiler error`
### What version of gRPC and what language are you using?

v1.48.0

### What operating system (Linux, Windows,...) and version?

Windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC:  19.32.31332.0

### What did you do?

Building with cmake.

```bash
'C:/Program Files/CMake/bin/cmake.exe' '../../../../a/cmake-toolset/cmake-toolset/test/third_party/packages/grpc-v1.48.0' '-Wno-dev' '-DCMAKE_INSTALL_PREFIX=D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc' '-G' 'Visual Studio 17 2022' '-DCMAKE_EXE_LINKER_FLAGS=/machine:x64' '-DCMAKE_MODULE_LINKER_FLAGS=/machine:x64' '-DCMAKE_SHARED_LINKER_FLAGS=/machine:x64' '-DCMAKE_STATIC_LINKER_FLAGS=/machine:x64' '-DCMAKE_SYSTEM_VERSION=10.0.22621.0' '-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON' '-DCMAKE_EXPORT_PACKAGE_REGISTRY=OFF' '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<NOT:$<STREQUAL:,static>>:DLL>' '-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /nologo /utf-8 /MP' '-DCMAKE_C_FLAGS_DEBUG= /Zi /Ob0 /Od /RTC1 /D_DEBUG /Z7' '-DCMAKE_C_FLAGS_RELEASE= /O2 /Ob2 /DNDEBUG /Oi /Z7 /Gy' '-DCMAKE_C_FLAGS_RELWITHDEBINFO= /Zi /O2 /Ob1 /DNDEBUG /Oi /Z7 /Gy' '-DCMAKE_C_FLAGS_MINSIZEREL= /O1 /Ob1 /DNDEBUG /Ox /Z7 /Gy' '-DCMAKE_C_STANDARD_LIBRARIES=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib bcrypt.lib dinput8.lib imm32.lib iphlpapi.lib psapi.lib secur32.lib setupapi.lib shlwapi.lib strmiids.lib version.lib vfw32.lib winmm.lib wsock32.lib userenv.lib Ws2_32.lib wldap32.lib crypt32.lib' '-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /EHsc /nologo /utf-8 /MP /Zc:__cplusplus /GR' '-DCMAKE_CXX_FLAGS_DEBUG= /Zi /Ob0 /Od /RTC1 /D_DEBUG /Z7' '-DCMAKE_CXX_FLAGS_RELEASE= /O2 /Ob2 /DNDEBUG /Oi /Z7 /Gy' '-DCMAKE_CXX_FLAGS_RELWITHDEBINFO= /Zi /O2 /Ob1 /DNDEBUG /Oi /Z7 /Gy' '-DCMAKE_CXX_FLAGS_MINSIZEREL= /O1 /Ob1 /DNDEBUG /Ox /Z7 /Gy' '-DCMAKE_CXX_STANDARD_LIBRARIES=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib bcrypt.lib dinput8.lib imm32.lib iphlpapi.lib psapi.lib secur32.lib setupapi.lib shlwapi.lib strmiids.lib version.lib vfw32.lib winmm.lib wsock32.lib userenv.lib Ws2_32.lib wldap32.lib crypt32.lib' '-A' 'x64' '-DCMAKE_POLICY_DEFAULT_CMP0091=NEW' '-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_C_STANDARD=17' '-DCMAKE_CXX_STANDARD=23' '-DCMAKE_POLICY_DEFAULT_CMP0075=NEW' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_FIND_ROOT_PATH=D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/lib64/cmake;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/lib/cmake;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/cmake;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/share;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/share/cmake' '-DCMAKE_PREFIX_PATH=D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/lib64/cmake;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/lib/cmake;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/cmake;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/share;D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/share/cmake' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DgRPC_INSTALL=ON' '-DBUILD_SHARED_LIBS=OFF' '-DCMAKE_BUILD_TYPE=Release' '-DgRPC_INSTALL_CSHARP_EXT=OFF' '-DgRPC_GFLAGS_PROVIDER=none' '-DgRPC_BENCHMARK_PROVIDER=none' '-DgRPC_BUILD_TESTS=OFF' '-DgRPC_BUILD_CODEGEN=ON' '-DgRPC_MSVC_STATIC_RUNTIME=OFF' '-DgRPC_ABSL_PROVIDER=package' '-DgRPC_CARES_PROVIDER=package' '-DgRPC_PROTOBUF_PROVIDER=package' '-DgRPC_PROTOBUF_PACKAGE_TYPE=CONFIG' '-DgRPC_RE2_PROVIDER=package' '-DgRPC_ZLIB_PROVIDER=package' '-DgRPC_SSL_PROVIDER=package' '-D_gRPC_PROTOBUF_PROTOC_EXECUTABLE=D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/bin/protoc.exe' '-DProtobuf_PROTOC_EXECUTABLE=D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/bin/protoc.exe' '-DPROTOBUF_PROTOC_EXECUTABLE=D:/a/cmake-toolset/cmake-toolset/test/third_party/install/windows-amd64-msvc/bin/protoc.exe'
```

### What did you expect to see?

Build success.

### What did you see instead?

```
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src/core/lib/promise/detail/basic_seq.h(481,1): fatal error C1001: Internal compiler error. [D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
  (compiler file 'msc1.cpp', line 1693)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com/
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\security\credentials\composite\composite_credentials.cc)
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src/core/lib/promise/detail/basic_seq.h(466): message : while compiling class template member function 'absl::lts_20211102::variant<grpc_core::Pending,T> grpc_core::promise_detail::BasicSeqIter<grpc_core::promise_detail::TrySeqTraits,grpc_composite_call_credentials::GetRequestMetadata::<lambda_1>,grpc_core::MetadataHandle<grpc_core::ServerMetadata>,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>::PollNonEmpty(void)' [D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
          with
          [
              T=absl::lts_20211102::StatusOr<grpc_core::ClientMetadataHandle>,
              _Ty=grpc_core::RefCountedPtr<grpc_call_credentials>
          ] (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\security\credentials\composite\composite_credentials.cc)
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src/core/lib/promise/detail/basic_seq.h(462): message : see reference to function template instantiation 'absl::lts_20211102::variant<grpc_core::Pending,T> grpc_core::promise_detail::BasicSeqIter<grpc_core::promise_detail::TrySeqTraits,grpc_composite_call_credentials::GetRequestMetadata::<lambda_1>,grpc_core::MetadataHandle<grpc_core::ServerMetadata>,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>::PollNonEmpty(void)' being compiled [D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
          with
          [
              T=absl::lts_20211102::StatusOr<grpc_core::ClientMetadataHandle>,
              _Ty=grpc_core::RefCountedPtr<grpc_call_credentials>
          ] (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\security\credentials\composite\composite_credentials.cc)
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\security\credentials\composite\composite_credentials.cc(61): message : see reference to class template instantiation 'grpc_core::promise_detail::BasicSeqIter<grpc_core::promise_detail::TrySeqTraits,grpc_composite_call_credentials::GetRequestMetadata::<lambda_1>,grpc_core::MetadataHandle<grpc_core::ServerMetadata>,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>' being compiled [D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
          with
          [
              _Ty=grpc_core::RefCountedPtr<grpc_call_credentials>
          ]
  INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
cl : command line error D8040: error creating or communicating with child process [D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
  grpc_csharp_plugin.vcxproj -> D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\Release\grpc_csharp_plugin.exe
  grpc_node_plugin.vcxproj -> D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\Release\grpc_node_plugin.exe
  grpc_objective_c_plugin.vcxproj -> D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\Release\grpc_objective_c_plugin.exe
  grpc_php_plugin.vcxproj -> D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\Release\grpc_php_plugin.exe
  grpc_python_plugin.vcxproj -> D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\Release\grpc_python_plugin.exe
  grpc_ruby_plugin.vcxproj -> D:\cmake-toolset\ceb3605\grpc-v1.48.0\windows-amd64-msvc\Release\grpc_ruby_plugin.exe
```

```
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc(118,13): error C2679: binary '==': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src/core/lib/slice/slice_internal.h(101,13): message : could be 'bool operator ==(const grpc_slice &,const grpc_slice &)' (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\guiddef.h(192,15): message : or       'bool operator ==(const GUID &,const GUID &)' (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\variant(1682,27): message : or       'bool std::operator ==(std::monostate,std::monostate) noexcept' [found using argument-dependent lookup] (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\guiddef.h(192,15): message : or 'bool operator ==(const GUID &,const GUID &)' [synthesized expression 'y == x'] (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\variant(1682,27): message : or 'bool std::operator ==(std::monostate,std::monostate) noexcept' [synthesized expression 'y == x'] (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src/core/lib/slice/slice_internal.h(101,13): message : or 'bool operator ==(const grpc_slice &,const grpc_slice &)' [synthesized expression 'y == x'] (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\xstring(1740,27): message : or       'bool std::operator ==<char,std::char_traits<char>,2>(const std::basic_string_view<char,std::char_traits<char>>,const std::basic_string_view<char,std::char_traits<char>>) noexcept' (compiling source file D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc) [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
D:\a\cmake-toolset\cmake-toolset\test\third_party\packages\grpc-v1.48.0\src\core\lib\iomgr\resolve_address_windows.cc(118,13): message : while trying to match the argument list '(absl::lts_20211102::string_view, int)' [D:\cmake-toolset\fd370a7\grpc-v1.48.0\windows-amd64-msvc\grpc_unsecure.vcxproj]
```

### Anything else we should know about your project / environment?

https://github.com/atframework/cmake-toolset/runs/7604851855
https://github.com/atframework/cmake-toolset/runs/7624863648

### PR DESCRIPTION
**Pull request by owent**
Fixes #30458

### CODE REVIEW

**Comment by drfloob** [comment]
Reassigning to @ctiller for the promise Seq changes.

File: src/core/lib/promise/detail/basic_seq.h [hunk 1]
```diff
@@ -404,8 +414,7 @@ class BasicSeq {
 // At each element, the accumulator A and the current value V is passed to some
 // function of type F as f(V, A); f is expected to return a promise that
 // resolves to Traits::WrappedType.
-template <template <typename Wrapped> class Traits, typename F, typename Arg,
-          typename Iter>
+template <class Traits, typename F, typename Arg, typename Iter>
```
Comment (ctiller) [inline src/core/lib/promise/detail/basic_seq.h:417]: If we're going this far, could we also just remove the `typename F, typename Arg, typename Iter` from this type, so that we end up with `template <class Traits> class BasicSeqIter` (same for the others here)

Comment (owent) [reply src/core/lib/promise/detail/basic_seq.h]: Done

**Comment by owent** [comment]
I'm not sure but is this PR cause the problems of failed CI jobs?This PR do not change any logical code but change the type traits for compilers.And the message seems to be a networking problem.

**Comment by owent** [comment]
> @owent The sanity check failure is valid, the others are test infrastructure issues. Please see https://source.cloud.google.com/results/invocations/912f23a3-4184-458b-bd6f-1d23edd9d4e4/log
> 
> I'm not sure what the easiest way is for you to run our IWYU and clang-format scripts, @ctiller we should probably document that for external contributors. You can try running, in order:
> 
> * `./tools/distrib/iwyu.sh`
> * `./tools/distrib/clang_format_code.sh`
> * `./tools/buildgen/generate_projects.sh`
> 
> These have some build requirements (python3 environment with mako and pyyaml, and I believe you need docker installed). Or let me know, and I can do the fix if you'd like.

I have latest version of clang-format, what's the version of clang-format in CI environment?

**Comment by owent** [comment]
> @owent The sanity check failure is valid, the others are test infrastructure issues. Please see https://source.cloud.google.com/results/invocations/912f23a3-4184-458b-bd6f-1d23edd9d4e4/log
> 
> I'm not sure what the easiest way is for you to run our IWYU and clang-format scripts, @ctiller we should probably document that for external contributors. You can try running, in order:
> 
>     * `./tools/distrib/iwyu.sh`
> 
>     * `./tools/distrib/clang_format_code.sh`
> 
>     * `./tools/buildgen/generate_projects.sh`
> 
> 
> These have some build requirements (python3 environment with mako and pyyaml, and I believe you need docker installed). Or let me know, and I can do the fix if you'd like.

Sure, it's nice if you can help me to fix the style. I have run `./tools/distrib/iwyu.sh` on my Linux system with docker installed, it shows:

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/data/home/owent/.cache/bazel/_bazel_owent/6ba95f281405cea14ad82a97ebe953e6/execroot/com_github_grpc_grpc'
Traceback (most recent call last):
  File "/local-code/iwyu/iwyu_tool.py", line 502, in <module>
    sys.exit(_bootstrap(sys.argv))
  File "/local-code/iwyu/iwyu_tool.py", line 497, in _bootstrap
    return main(args.dbpath, args.source, args.verbose,
  File "/local-code/iwyu/iwyu_tool.py", line 437, in main
    return execute(invocations, verbose, formatter, jobs, max_load_average)
  File "/local-code/iwyu/iwyu_tool.py", line 368, in execute
    proc = invocation.start(verbose)
  File "/local-code/iwyu/iwyu_tool.py", line 322, in start
    return Process.start(self)
  File "/local-code/iwyu/iwyu_tool.py", line 270, in start
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/data/home/owent/.cache/bazel/_bazel_owent/6ba95f281405cea14ad82a97ebe953e6/execroot/com_github_grpc_grpc'
```

But the path ls existed.

```bash
[owent@VM-144-59-centos grpc]$ ls /data/home/owent/.cache/bazel/_bazel_owent/6ba95f281405cea14ad82a97ebe953e6/execroot/com_github_grpc_grpc
AUTHORS             CONTRIBUTING.md  Makefile            Rakefile            bazel-out                 compile_commands_for_iwyu.json  examples                gRPC.podspec  iwyu                    requirements.txt  summerofcode
BUILD               GOVERNANCE.md    NOTICE.txt          SECURITY.md         build_autogenerated.yaml  composer.json                   external                grpc.bzl      iwyu_build              setup.cfg         templates
BUILDING.md         Gemfile          OWNERS              TROUBLESHOOTING.md  build_config.rb           config.m4                       gRPC-C++.podspec        grpc.def      iwyu_files.txt          setup.py          test
CMakeLists.txt      LICENSE          PYTHON-MANIFEST.in  WORKSPACE           build_handwritten.yaml    config.w32                      gRPC-Core.podspec       grpc.gemspec  iwyu_files0.txt         spm-core-include  third_party
CODE-OF-CONDUCT.md  MAINTAINERS.md   Package.swift       _metadata.py        cmake                     doc                             gRPC-ProtoRPC.podspec   grpc.gyp      package.xml             spm-cpp-include   tools
CONCEPTS.md         MANIFEST.md      README.md           bazel               compile_commands.json     etc                             gRPC-RxLibrary.podspec  include       requirements.bazel.txt  src
```

And the version of docker and python is here:

```bash
[owent@VM-144-59-centos grpc]$ docker --version
Docker version 20.10.8, build 3967b7d
[owent@VM-144-59-centos grpc]$ python3 --version
Python 3.6.8
```

**Comment by drfloob** [comment]
@owent can you modify the PR to allow edits by maintainers? There should be a checkbox for it on the right. I'll push a fix to your branch.

**Comment by owent** [comment]
image
Sorry，but I don't see any check box, Is it should be right here?

**Review by drfloob — APPROVED** [review]

**Review by ctiller — APPROVED** [review]

**Comment by drfloob** [comment]
@owent thanks for adding me, I took care of the formatting issues. The PR looks good, merging!
