### ISSUE TITLE
Protobuf 3.7.0 generates code with unused variables

### ISSUE THREAD

**Issue by GuanLuo** [grpc/grpc#18803]
### What version of gRPC and what language are you using?
 gRPC version is v1.20.0 and the language is C++
 
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
 
### What did you do?
I ran the script for building gRPC from source
``` Makefile
git clone -b $(shell curl -L https://grpc.io/release) https://github.com/grpc/grpc $(LIBGRPCDIR)/grpc
cd $(LIBGRPCDIR)/grpc && git submodule update --checkout --init
$(MAKE) -j"$(nproc)" prefix=$(LIBGRPCDIR) install
```
### What did you expect to see?
 The build succeed. I used the same script on v1.19.0 and it built successfully, just not on v1.20.0
 
### What did you see instead?
I received the following error:
``` bash
Makefile:2924: recipe for target '/workspace/build/grpc/grpc/objs/opt//workspace/build/grpc/grpc/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.o' failed
--
/workspace/build/grpc/grpc/gens/src/proto/grpc/channelz/channelz.pb.cc:1462:13: error: 'dynamic_init_dummy_src_2fproto_2fgrpc_2fchannelz_2fchannelz_2eproto' defined but not used [-Werror=unused-variable]
static bool dynamic_init_dummy_src_2fproto_2fgrpc_2fchannelz_2fchannelz_2eproto = []() { AddDescriptors_src_2fproto_2fgrpc_2fchannelz_2fchannelz_2eproto(); return true; }();
^
cc1plus: all warnings being treated as errors
```
 There are other errors in different "pb.cc" files, they are similar to the one I posted (`defined but not used`)

**Comment by nicolasnoble** [comment]
This is weird, it doesn't happen on our normal CIs, and this compiler version and warning are fairly common. @jtattermusch have we seen this before in artifact tests?

**Comment by mehrdada** [comment]
@GuanLuo  Do you have a `protoc` preinstalled somewhere else on the machine you're trying this on?

**Comment by GuanLuo** [comment]
@mehrdada No, the script I posted is part of a docker build on top of Ubuntu 16.04 image. And `protoc` isn't installed on the actual machine neither. However, it does install gRPC for Python before building gRPC from source (for C++), will that cause version conflict? The following is the Dockerfile (removed unrelated detail):
```Dockerfile
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
            software-properties-common \
            autoconf \
            automake \
            build-essential \
            curl \
            libcurl3-dev \
            git \
            libopencv-dev \
            libopencv-core-dev \
            libtool \
            pkg-config \
            python \
            python-dev

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip install --upgrade setuptools grpcio-tools

RUN git clone -b $(curl -L https://grpc.io/release) \
    https://github.com/grpc/grpc grpc && \
	cd grpc && \
    git submodule update --checkout --init && \
    make -j8 install

```

**Comment by nicolasnoble** [comment]
I just realized this really is on protobuf, and not grpc. I'm going to transfer the issue there.

**Comment by mehrdada** [comment]
@nicolasnoble @jtattermusch this might be a good thing to add to distribtests.

**Comment by jtattermusch** [comment]
> @nicolasnoble @jtattermusch this might be a good thing to add to distribtests.

If this is in the protobuf codebase, protobuf should test for this themselves.

**Comment by GuanLuo** [comment]
Hi all, if you are going to transfer the issue to gRPC, do you mind to add a reference so that I know where to look for updates? Thanks.
