### ISSUE TITLE
Trying to build examples from Quickstart gRPC for C++. Got error: undefined reference to `grpc_alts_is_running_on_gcp()'

### ISSUE THREAD

**Issue by agarusa** [grpc/grpc#30113]
### What version of gRPC and what language are you using?

I am following the [Quickstart](https://grpc.io/docs/languages/cpp/quickstart/) instructions to install gRPC for cpp. From this line, I conclude I am working with v1.46.3:

`git clone --recurse-submodules -b v1.46.3 --depth 1 --shallow-submodules https://github.com/grpc/grpc`

### What operating system (Linux, Windows,...) and version?

Ubuntu 18.04.6 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
cmake version 3.19.6
GNU Make 4.1 / Built for x86_64-pc-linux-gnu

### What did you do?
First, I tried installing with Bazel ("bazel build :all"). It couldn't find my gcc path and I had to add this as a variable. But I couldn't build examples (maybe I should install somehow?) so I moved to build with CMake.

I was following Quickstart instructions. I did the "Build and install gRPC and Protocol Buffers" part - with only 1 difference - I run "make -j3" because "make -j" seemed to spawn a lot processes and hanged dead my i5-3570(4/4) with 8Gb. I installed and restarted pc.

I then tried to build examples. I got errors. (I tried this after building gRPC+PB and with clean grpc repository clone - the same result).

### What did you expect to see?
Executable files greeter_server and greeter_client in the working directory.

### What did you see instead?
I saw this:

> ...
> [ 55%] Linking CXX executable greeter_async_server
> /home/broot/.local/lib/libgrpc.a(google_c2p_resolver.cc.o): In function `grpc_core::(anonymous > namespace)::GoogleCloud2ProdResolver::GoogleCloud2ProdResolver(grpc_core::ResolverArgs)':
> google_c2p_resolver.cc:(.text+0x13f9): undefined reference to `grpc_alts_is_running_on_gcp()'
>...
> make: *** [all] Error 2

Just for context - full output:

> **broot@broot:~/grpc/examples/cpp/helloworld/cmake/build$** cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR ../..
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> CMake Warning (dev) at /home/broot/.local/lib/cmake/protobuf/protobuf-options.cmake:6 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   For compatibility with older versions of CMake, option is clearing the
>   normal variable 'protobuf_MODULE_COMPATIBLE'.
> Call Stack (most recent call first):
>   /home/broot/.local/lib/cmake/protobuf/protobuf-config.cmake:2 (include)
>   /home/broot/grpc/examples/cpp/cmake/common.cmake:101 (find_package)
>   CMakeLists.txt:24 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Using protobuf 3.19.4.0
> -- Using gRPC 1.46.3
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/broot/grpc/examples/cpp/helloworld/cmake/build
> **broot@broot: ~ /grpc/examples/cpp/helloworld/cmake/build$** make -j3
> [  5%] Generating helloworld.pb.cc, helloworld.pb.h, helloworld.grpc.pb.cc, helloworld.grpc.pb.h
> Scanning dependencies of target hw_grpc_proto
> [ 11%] Building CXX object CMakeFiles/hw_grpc_proto.dir/helloworld.grpc.pb.cc.o
> [ 16%] Building CXX object CMakeFiles/hw_grpc_proto.dir/helloworld.pb.cc.o
> [ 22%] Linking CXX static library libhw_grpc_proto.a
> [ 22%] Built target hw_grpc_proto
> Scanning dependencies of target greeter_async_client
> Scanning dependencies of target greeter_async_server
> Scanning dependencies of target greeter_async_client2
> [ 27%] Building CXX object CMakeFiles/greeter_async_client.dir/greeter_async_client.cc.o
> [ 33%] Building CXX object CMakeFiles/greeter_async_client2.dir/greeter_async_client2.cc.o
> [ 38%] Building CXX object CMakeFiles/greeter_async_server.dir/greeter_async_server.cc.o
> [ 44%] Linking CXX executable greeter_async_client
> [ 50%] Linking CXX executable greeter_async_client2
> [ 55%] Linking CXX executable greeter_async_server
> /home/broot/.local/lib/libgrpc.a(google_c2p_resolver.cc.o): In function `grpc_core::(anonymous namespace)::GoogleCloud2ProdResolver::GoogleCloud2ProdResolver(grpc_core::ResolverArgs)':
> google_c2p_resolver.cc:(.text+0x13f9): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(google_default_credentials.cc.o):(.data.rel+0x0): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(alts_credentials.cc.o): In function `grpc_alts_credentials_create_customized(grpc_alts_credentials_options const*, char const*, bool)':
> alts_credentials.cc:(.text+0x401): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(alts_credentials.cc.o): In function `grpc_alts_server_credentials_create_customized(grpc_alts_credentials_options const*, char const*, bool)':
> alts_credentials.cc:(.text+0x48b): undefined reference to `grpc_alts_is_running_on_gcp()'
> collect2: error: ld returned 1 exit status
> CMakeFiles/greeter_async_client2.dir/build.make:159: recipe for target 'greeter_async_client2' failed
> make[2]: *** [greeter_async_client2] Error 1
> CMakeFiles/Makefile2:189: recipe for target 'CMakeFiles/greeter_async_client2.dir/all' failed
> make[1]: *** [CMakeFiles/greeter_async_client2.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> /home/broot/.local/lib/libgrpc.a(google_c2p_resolver.cc.o): In function `grpc_core::(anonymous namespace)::GoogleCloud2ProdResolver::GoogleCloud2ProdResolver(grpc_core::ResolverArgs)':
> google_c2p_resolver.cc:(.text+0x13f9): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(google_default_credentials.cc.o):(.data.rel+0x0): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(alts_credentials.cc.o): In function `grpc_alts_credentials_create_customized(grpc_alts_credentials_options const*, char const*, bool)':
> alts_credentials.cc:(.text+0x401): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(alts_credentials.cc.o): In function `grpc_alts_server_credentials_create_customized(grpc_alts_credentials_options const*, char const*, bool)':
> alts_credentials.cc:(.text+0x48b): undefined reference to `grpc_alts_is_running_on_gcp()'
> collect2: error: ld returned 1 exit status
> CMakeFiles/greeter_async_client.dir/build.make:159: recipe for target 'greeter_async_client' failed
> make[2]: *** [greeter_async_client] Error 1
> CMakeFiles/Makefile2:135: recipe for target 'CMakeFiles/greeter_async_client.dir/all' failed
> make[1]: *** [CMakeFiles/greeter_async_client.dir/all] Error 2
> /home/broot/.local/lib/libgrpc.a(google_c2p_resolver.cc.o): In function `grpc_core::(anonymous namespace)::GoogleCloud2ProdResolver::GoogleCloud2ProdResolver(grpc_core::ResolverArgs)':
> google_c2p_resolver.cc:(.text+0x13f9): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(google_default_credentials.cc.o):(.data.rel+0x0): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(alts_credentials.cc.o): In function `grpc_alts_credentials_create_customized(grpc_alts_credentials_options const*, char const*, bool)':
> alts_credentials.cc:(.text+0x401): undefined reference to `grpc_alts_is_running_on_gcp()'
> /home/broot/.local/lib/libgrpc.a(alts_credentials.cc.o): In function `grpc_alts_server_credentials_create_customized(grpc_alts_credentials_options const*, char const*, bool)':
> alts_credentials.cc:(.text+0x48b): undefined reference to `grpc_alts_is_running_on_gcp()'
> collect2: error: ld returned 1 exit status
> CMakeFiles/greeter_async_server.dir/build.make:159: recipe for target 'greeter_async_server' failed
> make[2]: *** [greeter_async_server] Error 1
> CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/greeter_async_server.dir/all' failed
> make[1]: *** [CMakeFiles/greeter_async_server.dir/all] Error 2
> Makefile:102: recipe for target 'all' failed
> make: *** [all] Error 2
> broot@broot:~/grpc/examples/cpp/helloworld/cmake/build$

### Anything else we should know about your project / environment?

All I can add is this:
Quickstart example is built smoothly when instead of Ubuntu18 I load my PC into the Windows system and then log into [WSL2] Ubuntu 20.04.2 LTS with "cmake version 3.19.6" and "GNU Make 4.2.1" and "gcc 9.3.0" (though I still need to build gRPC with "make -j3" command, so my i5-3570+8Gb wouldn't die). "Helloworld" example is built and run nicely.

**Comment by agarusa** [comment]
Yes, for bazel I use CC=/usr/bin/gcc. But this is built attempt with make (and cmake). **Third try with clean build worked as intended** - I think I made some mess while fighting my out-of-memory kind of errors on "make -j" command. Installed it clean with "make -j3". Thanks, closing.
