### ISSUE TITLE
python distribtest.python_dev_linux_x64_alpine3.7 broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16462]
Failing in 100% of cases starting from 
https://source.cloud.google.com/results/invocations/eb8e98b8-91b3-41ea-a7e8-8125dd8b39a7/targets/github%2Fgrpc/tests

```
  gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/nanopb -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c src/python/grpcio/grpc/_cython/cygrpc.cpp -o python_build/temp.linux-x86_64-2.7/src/python/grpcio/grpc/_cython/cygrpc.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread
  cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
  In file included from ./src/core/lib/iomgr/sockaddr_custom.h:25:0,
                   from ./src/core/lib/iomgr/sockaddr.h:28,
                   from src/python/grpcio/grpc/_cython/cygrpc.cpp:1358:
  ./src/core/lib/iomgr/port.h:63:27: fatal error: linux/version.h: No such file or directory
   #include <linux/version.h>
                             ^
  compilation terminated.
```

Most likely the offending PR is https://github.com/grpc/grpc/pull/15941.
Marking as release blocker we're planning to cut the release branch very soon and we cannot release with broken distribtests.

**Comment by jtattermusch** [comment]
CC @AspirinSJL  @mehrdada

**Comment by nicolasnoble** [comment]
Aaaah, alpine Linux...

**Comment by AspirinSJL** [comment]
Has https://github.com/grpc/grpc/pull/16463 fixed this issue?

**Comment by mehrdada** [comment]
I triggered an artifact build to see if distribtests pass now https://source.cloud.google.com/results/invocations/ef9db026-b1b4-4007-a20e-5e4f24c2c237/targets

**Comment by AspirinSJL** [comment]
https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests is green again. Closing this issue.
