### ISSUE TITLE
redefinition of module "openssl", swift project won't compiles in xcode 8.3

### ISSUE THREAD

**Issue by fabware** [grpc/grpc#10355]
Hi, we have a production swift project used to be working in xcode 8.2 won't compile in xcode 8.3, which failed with: redefinition of module 'openssl'. 

Configuration stay untouched for months, hope it would be silly problem.

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

target 'flash' do
    pod 'Alamofire', '~> 4.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'BugfenderSDK', '~> 0.3.24'
    pod 'SDWebImage', '~> 3.8'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'SentrySwift'
    pod 'SwiftyJSON'
    pod 'FlashService', :path => "./FlashService"
end

target 'flashTests' do
end

target 'flashUITests' do
end
```

FlashService.podspec
```
Pod::Spec.new do |s|
  s.name     = 'FlashService'
  s.version  = '2.9.0.04'
  s.license  = 'MIT'
  s.authors  = { 'hosopy' => 'dev.hosopy@gmail.com' }
  s.homepage = 'https://github.com/hosopy'
  s.summary = 'gRPC test client'
  s.source = { :git => 'https://bitbucket.org/xxx/proto'}

  s.ios.deployment_target = '7.1'
  s.osx.deployment_target = '10.9'

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.2.0"

  # Pods directory corresponding to this app's Podfile, relative to the location of this podspec.
  pods_root = '../Pods'

  # Path where Cocoapods downloads protoc and the gRPC plugin.
  protoc_dir = "#{pods_root}/!ProtoCompiler"
  protoc = "#{protoc_dir}/protoc"
  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

  s.prepare_command = <<-CMD
    #{protoc} \
        --plugin=protoc-gen-grpc=#{plugin} \
        --objc_out=. \
        --grpc_out=. \
        -I . \
        -I #{protoc_dir} \
        -I ../../proto \
        ../../proto/*.proto
  CMD

  s.subspec 'Messages' do |ms|
    ms.source_files = '*.pbobjc.{h,m}'
    ms.header_mappings_dir = '.'
    ms.requires_arc = false
    ms.dependency 'Protobuf'
  end

  s.subspec 'Services' do |ss|
    ss.source_files = '*.pbrpc.{h,m}'
    ss.header_mappings_dir = '.'
    ss.requires_arc = true
    ss.dependency 'gRPC-ProtoRPC'
    ss.dependency "#{s.name}/Messages"
  end

  s.pod_target_xcconfig = {
      # This is needed by all pods that depend on Protobuf:
      'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
      # This is needed by all pods that depend on gRPC-RxLibrary:
      'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  }
end
```

**Comment by swfeng** [comment]
I ran into this issue as well. After looking around, it seems to be a naming issue for the modulemap file, where Xcode 8.3 apparently changed it so that framework declarations with the same name seemingly need to have the same filename too.

Specifically, there are two modulemap files defining the openssl framework:
1) `Pods/BoringSSL/include/openssl/module.modulemap`
2) `Pods/Target Support Files/BoringSSL/BoringSSL.modulemap`.

I got around this issue by renaming module.modulemap to BoringSSL.modulemap, and now it builds again.

ResearchKit seems to have had a similar issue. They got around this by renaming the modulemap file to ResearchKit.modulemap.
https://github.com/ResearchKit/ResearchKit/issues/922

This hack works, but hopefully there'll be a proper fix once we finally know the root cause.

**Comment by cristianbica** [comment]
As a workaround I've cloned and renamed the module_name in BoringSSL podspec: https://github.com/cristianbica/boringssl-podspec/blob/master/BoringSSL.podspec

and used this in my Podfile

```
  pod 'BoringSSL', podspec: "https://raw.githubusercontent.com/cristianbica/boringssl-podspec/master/BoringSSL.podspec"
```

If you intend to do this workaround until the problem is fixed please copy the podspec on your own repo as I might delete it at some point.

**Comment by cristianbica** [comment]
While it would be nice if in the BoringSSL.podspec the module_name is changed to something not generic this is an Xcode known bug. According to the Xcode 8.3 release notes ([here](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html)):

> When building a framework that has module maps in both the source and the install directories that define the same module, the compiler will show a redefinition message. (28638816)
> Workaround: Rename the module map file in the source directory to a non-default name (the default name is module.modulemap or module.map), and set the Module Map File build setting to the renamed module map.
>

**Comment by fabware** [comment]
@swfeng You save my life, I got around this as you advised. Thank you very much.

Glad root cause is found @cristianbica , hope it can be fixed soon.

**Comment by muxi** [comment]
It would be great if anyone can help confirm if #10631 fixes this problem.

**Comment by cristianbica** [comment]
@muxi it works with:

```
pod 'BoringSSL', podspec: "https://raw.githubusercontent.com/grpc/grpc/master/src/objective-c/BoringSSL.podspec"
```

Probably BoringSSL 8.1 needs to be pushed to cocoapods

**Comment by jcanizales** [comment]
Should this be reopened on account of https://github.com/grpc/grpc/pull/10689?

**Comment by swfeng** [comment]
Haven't checked on BoringSSL 8.1. Cocoapods version is now 8.2 and seems to work without any problems for my projects.
