### ISSUE TITLE
npm install grpc doesn't work on fresh Ubuntu 15.10

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4131]
I just tried this on a fresh VM running Ubuntu 15.10 and this failed, so I assume there are packages missing....

``` sh
$ npm install -g grpc
|
> grpc@0.11.1 install /usr/local/lib/node_modules/grpc
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
../ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../ext/call.cc:562:36: error: ‘GRPC_PROPAGATE_DEFAULTS’ was not declared in this scope
       gpr_uint32 propagate_flags = GRPC_PROPAGATE_DEFAULTS;
                                    ^
../ext/call.cc:583:67: error: cannot convert ‘grpc_call*’ to ‘grpc_completion_queue*’ for argument ‘2’ to ‘grpc_call* grpc_channel_create_call(grpc_channel*, grpc_completion_queue*, const char*, const char*, gpr_timespec)’
             *host_override, MillisecondsToTimespec(deadline), NULL);
                                                                   ^
In file included from ../ext/call.cc:41:0:
/usr/include/grpc/grpc.h:61:16: note: class type ‘grpc_call’ is incomplete
 typedef struct grpc_call grpc_call;
                ^
../ext/call.cc:588:57: error: cannot convert ‘grpc_call*’ to ‘grpc_completion_queue*’ for argument ‘2’ to ‘grpc_call* grpc_channel_create_call(grpc_channel*, grpc_completion_queue*, const char*, const char*, gpr_timespec)’
             NULL, MillisecondsToTimespec(deadline), NULL);
                                                         ^
In file included from ../ext/call.cc:41:0:
/usr/include/grpc/grpc.h:61:16: note: class type ‘grpc_call’ is incomplete
 typedef struct grpc_call grpc_call;
                ^
../ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::StartBatch(Nan::NAN_METHOD_ARGS_TYPE)’:
../ext/call.cc:640:12: error: ‘__gnu_cxx::__alloc_traits<std::allocator<grpc_op> >::value_type {aka struct grpc_op}’ has no member named ‘reserved’
     ops[i].reserved = NULL;
            ^
../ext/call.cc:677:58: error: too many arguments to function ‘grpc_call_error grpc_call_start_batch(grpc_call*, const grpc_op*, size_t, void*)’
           callback, op_vector.release(), resources), NULL);
                                                          ^
In file included from ../ext/call.cc:41:0:
/usr/include/grpc/grpc.h:420:17: note: declared here
 grpc_call_error grpc_call_start_batch(grpc_call *call, const grpc_op *ops,
                 ^
../ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::Cancel(Nan::NAN_METHOD_ARGS_TYPE)’:
../ext/call.cc:689:68: error: too many arguments to function ‘grpc_call_error grpc_call_cancel(grpc_call*)’
   grpc_call_error error = grpc_call_cancel(call->wrapped_call, NULL);
                                                                    ^
In file included from ../ext/call.cc:41:0:
/usr/include/grpc/grpc.h:448:17: note: declared here
 grpc_call_error grpc_call_cancel(grpc_call *call);
                 ^
../ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::CancelWithStatus(Nan::NAN_METHOD_ARGS_TYPE)’:
../ext/call.cc:712:72: error: too many arguments to function ‘grpc_call_error grpc_call_cancel_with_status(grpc_call*, grpc_status_code, const char*)’
   grpc_call_cancel_with_status(call->wrapped_call, code, *details, NULL);
                                                                        ^
In file included from ../ext/call.cc:41:0:
/usr/include/grpc/grpc.h:456:17: note: declared here
 grpc_call_error grpc_call_cancel_with_status(grpc_call *call,
                 ^
../ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::GetPeer(Nan::NAN_METHOD_ARGS_TYPE)’:
../ext/call.cc:721:53: error: ‘grpc_call_get_peer’ was not declared in this scope
   char *peer = grpc_call_get_peer(call->wrapped_call);
                                                     ^
grpc.target.mk:106: recipe for target 'Release/obj.target/grpc/ext/call.o' failed
make: *** [Release/obj.target/grpc/ext/call.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/grpc/build'
```

**Comment by murgatroid99** [comment]
The next release will actually make this work.

**Comment by jgeewax** [comment]
By 'release' do you mean push to NPM or push of code? Any ETA ?

**Comment by murgatroid99** [comment]
I mean push to NPM. And we don't have an exact ETA because it is gated on a particular change being made in all C-based languages. I expect it this month, but I can't guarantee that.

**Comment by murgatroid99** [comment]
gRPC 0.12.0 has been published to NPM, and it now does not depend on the debian packages. Can you check if that fixed the problem for you?
