### PR TITLE
Use deps rather than uses.

### LINKED ISSUE #10909: Mac c++ Examples Crash
Trying to run the examples after a clean install from head on Mac:

```
$ ./greeter_client
D0428 10:29:41.701786000 140736243426240 ev_posix.c:107]               Using polling engine: poll
D0428 10:29:41.702424000 140736243426240 dns_resolver.c:316]           Using native dns resolver
E0428 10:29:41.702558000 140736243426240 sync_posix.c:60]              assertion failed: pthread_mutex_lock(mu) == 0
Abort trap: 6
```

And the server:
```
$ ./greeter_server
I0428 10:30:09.715859000 140736243426240 server_builder.cc:258]        Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
D0428 10:30:09.716590000 140736243426240 ev_posix.c:107]               Using polling engine: poll
D0428 10:30:09.716631000 140736243426240 dns_resolver.c:316]           Using native dns resolver
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by yang-g**
Stop pulling in c source files in c++ file group to avoid duplicate symbols.

This was introduced in #10382

This seems to fix #10909.

### CODE REVIEW

**Comment by ncteisen** [comment]
Just pulled this down. It does indeed fix the problem on my machine as well

**Comment by yang-g** [comment]
Known test issues:
#10169
#11223
#11216
#9542
#11252
