### ISSUE TITLE
grpc C++ v1.4.0 fails on macOS

### ISSUE THREAD

**Issue by bsegault** [grpc/grpc#11581]
Hi,

## Environment

I'm using gRPC C++ on Linux, Windows and macOS, and I encountered issue #7830 on macOS. I understood that it was resolved in recent release 1.4.0.

All results are from macOS Sierra, with 
```
$ cc -v   
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

## Issue description

When trying to compiling gRPC using the given makefile, I get the following error (complete build log bellow:
```
No rule to make target `src/core/lib/channel/compress_filter.h', needed by `/Users/starburst/dev/satellite-library/third-party/grpc/objs/opt/src/core/lib/surface/init.o'.
```
I tried using cmake, but it fails when using zlib:

```
[  2%] Building CXX object third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/zero_copy_stream_impl.cc.o
In file included from grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc:38:
In file included from grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.h:48:
grpc/third_party/zlib/zlib.h:1420:9: error: unknown type name 'z_size_t'
ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
```

Both cmake and make compile in v1.3.2. It seems the issue was introduced between v1.3.2 and 7569676ffe68597201c91ac2f17390ec1c3d7063.

I will try as soon as I can to check if I can reproduce this issue on Linux and isolate the commit that introduced the error. Thanks for any help :-)

## Complete build log and actions
```
$ g co v1.4.0 
warning: unable to rmdir third_party/thrift: Directory not empty
M	third_party/protobuf
M	third_party/zlib
Previous HEAD position was c80d3321d0... Merge pull request #11073 from stanley-cheung/bump-to-1_3_2
HEAD is now at 869e373466... Merge pull request #11567 from muxi/fix-objc-memory-leak-v14
$ git submodule update --init                                                               
Submodule path 'third_party/protobuf': checked out 'a6189acd18b00611c1dc7042299ad75486f08a1a'
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
$ make
[MAKE]    Generating cache.mk
[C]       Compiling src/core/lib/profiling/basic_timers.c
[C]       Compiling src/core/lib/profiling/stap_timers.c
[C]       Compiling src/core/lib/support/alloc.c
[C]       Compiling src/core/lib/support/arena.c
[C]       Compiling src/core/lib/support/atm.c
[C]       Compiling src/core/lib/support/avl.c
[C]       Compiling src/core/lib/support/backoff.c
[C]       Compiling src/core/lib/support/cmdline.c
[C]       Compiling src/core/lib/support/cpu_iphone.c
[C]       Compiling src/core/lib/support/cpu_linux.c
[C]       Compiling src/core/lib/support/cpu_posix.c
[C]       Compiling src/core/lib/support/cpu_windows.c
[C]       Compiling src/core/lib/support/env_linux.c
[C]       Compiling src/core/lib/support/env_posix.c
[C]       Compiling src/core/lib/support/env_windows.c
[C]       Compiling src/core/lib/support/histogram.c
[C]       Compiling src/core/lib/support/host_port.c
[C]       Compiling src/core/lib/support/log.c
[C]       Compiling src/core/lib/support/log_android.c
[C]       Compiling src/core/lib/support/log_linux.c
[C]       Compiling src/core/lib/support/log_posix.c
[C]       Compiling src/core/lib/support/log_windows.c
[C]       Compiling src/core/lib/support/mpscq.c
[C]       Compiling src/core/lib/support/murmur_hash.c
[C]       Compiling src/core/lib/support/stack_lockfree.c
[C]       Compiling src/core/lib/support/string.c
[C]       Compiling src/core/lib/support/string_posix.c
[C]       Compiling src/core/lib/support/string_util_windows.c
[C]       Compiling src/core/lib/support/string_windows.c
[C]       Compiling src/core/lib/support/subprocess_posix.c
[C]       Compiling src/core/lib/support/subprocess_windows.c
[C]       Compiling src/core/lib/support/sync.c
[C]       Compiling src/core/lib/support/sync_posix.c
[C]       Compiling src/core/lib/support/sync_windows.c
[C]       Compiling src/core/lib/support/thd.c
[C]       Compiling src/core/lib/support/thd_posix.c
[C]       Compiling src/core/lib/support/thd_windows.c
[C]       Compiling src/core/lib/support/time.c
[C]       Compiling src/core/lib/support/time_posix.c
[C]       Compiling src/core/lib/support/time_precise.c
[C]       Compiling src/core/lib/support/time_windows.c
[C]       Compiling src/core/lib/support/tls_pthread.c
[C]       Compiling src/core/lib/support/tmpfile_msys.c
[C]       Compiling src/core/lib/support/tmpfile_posix.c
[C]       Compiling src/core/lib/support/tmpfile_windows.c
[C]       Compiling src/core/lib/support/wrap_memcpy.c
make: *** No rule to make target `src/core/lib/channel/compress_filter.h', needed by `/Users/starburst/dev/satellite-library/third-party/grpc/objs/opt/src/core/lib/surface/init.o'.  Stop.
make: *** Waiting for unfinished jobs....
```

**Comment by mehrdada** [comment]
Do you have a similar problem with a clean `git clone --recursive https://github.com/grpc/grpc -b v1.4.0`? 

I just tried both `cmake .; make -j12` and `make` on two clean clones and they work just fine. FYI, My system is quite clean macOS 10.12.5 with the following `brew` packages installed (out on which I suspect `libtool`, `shtool`, `autoconf`, `automake`, `pkg-config`, `gflags` may be relevant:

```
$ brew list
autoconf		icu4c			node
automake		irssi			openssl
bazel			libevent		pcre
cmake			libffi			pkg-config
coreutils		libpng			pv
docker			libssh2			s-lang
gettext			libtool			shtool
gflags			makedepend		tmux
glib			midnight-commander	wget
```

**Comment by yang-g** [comment]
Try make clean and then make.

**Comment by mehrdada** [comment]
I'm going to close this issue. Please let us know if you are experiencing build issues on a clean tree. Thanks!

**Comment by tinganho** [comment]
I'm still seeing this issue on my Mac. I tried with make clean and then make. But the error didn't dissapear. I use gRPC by cloning the repo under `third_party/` and then I add one line of `
add_subdirectory(third_party/grpc)` in my CMakeLists.txt file. 

These are my commands:
```
mkdir debug
cd debug

cmake --version 
cmake version 3.9.1

cmake -DCMAKE_BUILD_TYPE=Debug ..

make 
```
And this is the error from `make`:

```
In file included from /Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc:38:
In file included from /Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.h:48:
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1420:9: error: unknown type
      name 'z_size_t'
ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
        ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1420:49: error: unknown type
      name 'z_size_t'
ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
                                                ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1420:64: error: unknown type
      name 'z_size_t'
ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
                                                               ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1454:9: error: unknown type
      name 'z_size_t'
ZEXTERN z_size_t ZEXPORT gzfwrite OF((voidpc buf, z_size_t size,
        ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1454:51: error: unknown type
      name 'z_size_t'
ZEXTERN z_size_t ZEXPORT gzfwrite OF((voidpc buf, z_size_t size,
                                                  ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1455:39: error: unknown type
      name 'z_size_t'
                                      z_size_t nitems, gzFile file));
                                      ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1708:37: error: unknown type
      name 'z_size_t'
                                    z_size_t len));
                                    ^
/Users/tinganho/Workspace/l10ns/third_party/grpc/third_party/zlib/zlib.h:1743:35: error: unknown type
      name 'z_size_t'
                                  z_size_t len));
                                  ^
8 errors generated.
make[2]: *** [third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o] Error 1
make[1]: *** [third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tinganho** [comment]
Related https://github.com/madler/zlib/issues/133.

I fixed this issue by just renaming `third_party/grpc/third_party/zlib/zconf.h.include` to `third_party/grpc/third_party/zlib/zconf.h`.

**Comment by mtl1979** [comment]
@tinganho FYI add_subdirectory() should always have two parameters as cmake-generated files in subproject don't get added to include path otherwise. This is because of strict rules in relative paths. Renaming zconf.h.included to zconf.h will ignore any platform dependent fixes in zlib.

**Comment by tinganho** [comment]
What should the second argument be?

**Comment by mtl1979** [comment]
@tinganho When you include zlib, it should be "${CMAKE_CURRENT_BINARY_DIR}/zlib_build", for any other subprojects, just replace "zlib_build" with project name + "_build". This makes sure binary directories of subprojects are subdirectories of binary directory of main project. Binary directory contains all generated files, not just libraries (static or dynamic) or executables.

**Comment by tinganho** [comment]
@mtl1979 I had time now to try your suggested solution. It doesn't seem to work. Even though, I added it to grpc project.

**Comment by mtl1979** [comment]
@tinganho I can't tell what goes wrong and why until I try it locally. I've done it once before with another project and it worked correctly.

**Comment by tinganho** [comment]
@mtl1979 Never mind, after having read the thread in madler/zlib#133 again, I now understand the 2nd argument. It gets a compiled `zconf.h` file in the binary dir. And anyone using grpc with `add_subdirectory()` needs to include the `zconf.h` manually. So one just need to include it manually by `include_directories(${CMAKE_CURRENT_BINARY_DIR}/third_party/grpc/third_party/zlib)`

Thanks for the help!

**Comment by mtl1979** [comment]
@tinganho The second parameter just automates adding the generated files to include and linker search paths ;) Like I said, it only works correctly if all subprojects recursively use it.

**Comment by l33ds** [comment]
Hey guys, could you help me realized how and where was this resolved?
I'm using GRPC 1.6.0 in my project and I get a similar error (attached).
I can see that zconf.h is being changed into zconf.h.including in the build process.
Do I need to update my GRPC? Why does it only happen to some people?
Thanks!!!

FAILED: /usr/bin/c++   -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_CONFIG_H=1 -DHAVE_PTHREAD -DHAVE_ZLIB -D_GNU_SOURCE=1 -isystem /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib -Isrc/common/third_party/grpc/third_party/protobuf -I/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src -std=c++14 -g -D_DEBUG -fPIC -MMD -MT src/common/third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o -MF src/common/third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o.d -o src/common/third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o -c /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc
In file included from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.h:48:0,
                 from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc:38:
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1420:9: error: ‘z_size_t’ does not name a type
 ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
         ^
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1454:9: error: ‘z_size_t’ does not name a type
 ZEXTERN z_size_t ZEXPORT gzfwrite OF((voidpc buf, z_size_t size,
         ^
In file included from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:34:0,
                 from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.h:48,
                 from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc:38:
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1707:33: error: ‘z_size_t’ has not been declared
 ZEXTERN uLong ZEXPORT adler32_z OF((uLong adler, const Bytef *buf,
                                 ^
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1742:31: error: ‘z_size_t’ has not been declared
 ZEXTERN uLong ZEXPORT crc32_z OF((uLong adler, const Bytef *buf,

**Comment by l33ds** [comment]
Hey guys, could you help me realized how and where was this resolved?
I'm using GRPC 1.6.0 in my project and I get a similar error (attached).
I can see that zconf.h is being changed into zconf.h.including in the build process.
Do I need to update my GRPC? Why does it only happen to some people?
Thanks!!!

FAILED: /usr/bin/c++   -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_CONFIG_H=1 -DHAVE_PTHREAD -DHAVE_ZLIB -D_GNU_SOURCE=1 -isystem /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib -Isrc/common/third_party/grpc/third_party/protobuf -I/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src -std=c++14 -g -D_DEBUG -fPIC -MMD -MT src/common/third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o -MF src/common/third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o.d -o src/common/third_party/grpc/third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/io/gzip_stream.cc.o -c /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc
In file included from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.h:48:0,
                 from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc:38:
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1420:9: error: ‘z_size_t’ does not name a type
 ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
         ^
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1454:9: error: ‘z_size_t’ does not name a type
 ZEXTERN z_size_t ZEXPORT gzfwrite OF((voidpc buf, z_size_t size,
         ^
In file included from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:34:0,
                 from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.h:48,
                 from /mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/protobuf/src/google/protobuf/io/gzip_stream.cc:38:
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1707:33: error: ‘z_size_t’ has not been declared
 ZEXTERN uLong ZEXPORT adler32_z OF((uLong adler, const Bytef *buf,
                                 ^
/mnt/hgfs/Code/Agent/src/common/third_party/grpc/third_party/zlib/zlib.h:1742:31: error: ‘z_size_t’ has not been declared
 ZEXTERN uLong ZEXPORT crc32_z OF((uLong adler, const Bytef *buf,

**Comment by mtl1979** [comment]
@l33ds It should not happen to people who have installed zlib development package as that includes both zlib.h and zconf.h files. It might happen if those two files end up from two incompatible versions of zlib.

**Comment by jtattermusch** [comment]
A bit of reasoning to conclude:
I think the problem with missing `zconf.h` header only happens if you are trying to use both cmake and make in the same working directory:

1. the first time you build with cmake, this conditions gets triggered:
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/CMakeLists.txt#L69
and zconf.h gets renamed for "safety purposes"

2. third_party/zlib stays dirty (as it can be seen with `git status`):
```
~/github/grpc/third_party/zlib$ git status
HEAD detached at cacf7f1
Changes not staged for commit:
	deleted:    zconf.h
Untracked files:
	zconf.h.included
``` 

3. when you later try to build using some other build system than cmake (e.g. just `make` from gRPC project root), the zconf.h will be missing and you will get the error messages about "z_size_t" not being declared (and others).

The remedy if you want to use multiple build systems (cmake and e.g. make) in the same working directory, make sure to clean you third_party/zlib after you're done with cmake:
`~/github/grpc/third_party/zlib$  mv zconf.h.included zconf.h`  and after that `git status` should say `nothing to commit, working tree clean`
